// packages/react/core/src/components/slider/examples/controlled.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Slider } from '../index'

export function SliderControlledExample() {
  const [value, setValue] = useState([10])

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <Button variant="outlined" onClick={() => setValue([0])}>
          Set 0
        </Button>
        <Button variant="outlined" onClick={() => setValue([50])}>
          Set 50
        </Button>
        <Button variant="outlined" onClick={() => setValue([100])}>
          Set 100
        </Button>
        <span className="text-sm text-gray-ff">
          value:
          {' '}
          {value[0]}
        </span>
      </div>

      <Slider
        className="w-90"
        min={0}
        max={100}
        step={1}
        value={value}
        onValueChange={details => setValue(details.value)}
      >
        <Slider.TooltipThumb index={0} />
      </Slider>
    </div>
  )
}

// packages/vue/core/src/components/toggle-group/examples/controlled.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import { ToggleGroup, ToggleGroupItem } from '../index'

const value = ref<string[]>(['b'])
</script>

<template>
  <div class="flex flex-col gap-3">
    <div class="flex items-center gap-2">
      <Button variant="outlined" @click="value = ['a']">
        Set A
      </Button>
      <Button variant="outlined" @click="value = ['b']">
        Set B
      </Button>
      <Button variant="outlined" @click="value = ['c']">
        Set C
      </Button>
      <span class="text-sm text-gray-ff">value: {{ value }}</span>
    </div>

    <ToggleGroup v-model="value" type="single">
      <ToggleGroupItem value="a">
        A
      </ToggleGroupItem>
      <ToggleGroupItem value="b">
        B
      </ToggleGroupItem>
      <ToggleGroupItem value="c">
        C
      </ToggleGroupItem>
    </ToggleGroup>
  </div>
</template>
