// packages/react/core/src/components/skeleton/Skeleton.tsx
import type { SkeletonProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useMemo } from 'react'

export const Skeleton = forwardRef<HTMLDivElement, SkeletonProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      variant = 'pulse',
      shape = 'rect',
      children,
      ...props
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const variants = useMemo(() => ({ variant, shape }), [variant, shape])
    const crafts = useCraft(theme, 'tvSkeleton', variants, craft)

    return (
      <ark.div
        ref={ref}
        className={crafts(cxc(className))}
        data-shape={shape}
        data-variant={variant}
        {...props}
      >
        {children}
      </ark.div>
    )
  },
)

Skeleton.displayName = 'Skeleton'

// packages/vue/core/src/components/skeleton/Skeleton.vue
<script setup lang="ts">
import type { SkeletonProps } from '.'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  variant = 'pulse',
  shape = 'rect',
  theme: propsTheme,
  craft,
} = defineProps<SkeletonProps>()

// theme
const theme = useTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvSkeleton', () => ({
  variant,
  shape,
}), () => craft)
</script>

<template>
  <div
    :class="crafts(cxc(propsClass))"
    :data-shape="shape"
    :data-variant="variant"
  >
    <slot />
  </div>
</template>
