// packages/react/core/src/components/button/Button.tsx
import type { MouseEvent } from 'react'
import type { ButtonProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useRipple } from '@raxium/react/hooks/useRipple'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useComposedRefs } from '@raxium/react/utils'
import { getNodeCssVar } from '@raxium/shared/css'
import { cxc } from '@raxium/themes/utils'
import { LoaderCircle } from 'lucide-react'
import { forwardRef, useMemo, useRef } from 'react'

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      variant = 'solid',
      color = 'primary',
      disabled,
      ripple = false,
      loading = false,
      asChild = false,
      ui,
      tooltip: _tooltip,
      loadingIndicator,
      children,
      onClick,
      ...props
    },
    forwardedRef,
  ) => {
    const hostRef = useRef<HTMLButtonElement>(null)
    const ref = useComposedRefs(forwardedRef, hostRef)
    const theme = useTheme(propsTheme)
    const variants = useMemo(
      () => ({ variant, color, loading }),
      [variant, color, loading],
    )
    const crafts = useCraft(theme, 'tvButton', variants, craft)
    const { onRipple, Ripple } = useRipple(hostRef, {
      enabled: ripple && !disabled,
      color: () => getNodeCssVar(hostRef.current, '--rui-ripple-color', 'transparent'),
    })

    function handleClick(event: MouseEvent<HTMLButtonElement>) {
      onRipple(event)
      onClick?.(event)
    }

    return (
      <ark.button
        ref={ref}
        className={crafts.root(cxc(ui?.root, className))}
        disabled={disabled}
        data-variant={variant}
        data-color={color}
        data-ripple={ripple ? true : undefined}
        data-loading={loading ? true : undefined}
        data-size={theme.size}
        asChild={asChild}
        onClick={handleClick}
        {...props}
      >
        {loading && (
          loadingIndicator ?? (
            <LoaderCircle className={crafts.loading(cxc(ui?.loading))} />
          )
        )}
        {children}
        {ripple ? <Ripple /> : null}
      </ark.button>
    )
  },
)

Button.displayName = 'Button'

// packages/vue/core/src/components/button/Button.vue
<script setup lang="ts">
import type { ButtonProps } from '.'
import { useForwardExpose } from '@ark-ui/vue'
import { ark } from '@ark-ui/vue/factory'
import { LoaderCircle } from '@lucide/vue'
import { getNodeCssVar } from '@raxium/shared/css'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables/useCraft'
import { useRipple } from '@raxium/vue/composables/useRipple'
import { useTheme } from '@raxium/vue/composables/useTheme'
import { computed } from 'vue'

const {
  variant = 'solid',
  color = 'primary',
  class: propsClass,
  theme: propsTheme,
  craft,
  disabled,
  ripple = false,
  loading = false,
  asChild = false,
  ui,
} = defineProps<ButtonProps>()

const emits = defineEmits<{
  click: [event: MouseEvent]
}>()
const slots = defineSlots<{
  default?: () => any
  tooltip?: () => any
  loading?: () => any
}>()

const { forwardRef, currentElement } = useForwardExpose()
const rippleColor = computed(() => {
  return getNodeCssVar(currentElement.value, '--rui-ripple-color', 'transparent')
})
const { onRipple, Ripple } = useRipple(currentElement, {
  enabled: ripple && !disabled,
  color: rippleColor,
})

function onClick(event: MouseEvent) {
  onRipple(event)
  emits('click', event)
}

// theme — useCraft pre-binds variants so slot calls only need { class }
const theme = useTheme(
  () => propsTheme,
  undefined,
  () => craft,
)
const crafts = useCraft(theme, 'tvButton', () => ({
  variant,
  color,
  loading,
}))
</script>

<template>
  <ark.button
    :ref="forwardRef"
    :class="crafts.root(cxc(ui?.root, propsClass))"
    :disabled="disabled"
    :data-variant="variant"
    :data-color="color"
    :data-ripple="ripple ? true : undefined"
    :data-loading="loading ? true : undefined"
    :data-size="theme.size"
    :as-child="asChild"
    @click="onClick"
  >
    <slot
      v-if="loading"
      name="loading"
    >
      <LoaderCircle :class="crafts.loading(cxc(ui?.loading))" />
    </slot>
    <slot />
    <Ripple v-if="ripple" />
  </ark.button>
</template>
