// packages/react/core/src/components/progress/examples/circle-and-arc.tsx
import { THEME_SIZE } from '@raxium/shared/constant'
import { useState } from 'react'
import { Progress } from '../index'

export function ProgressCircleAndArcExample() {
  const [value] = useState(70)

  return (
    <div className="w-full flex flex-col gap-6">
      <div className="flex flex-col gap-3">
        <div className="text-sm text-gray-ff">Circle (default)</div>
        <div className="flex items-center gap-4">
          {THEME_SIZE.map(size => (
            <Progress key={String(size)} value={value}>
              <Progress.Circle theme={{ size }} />
            </Progress>
          ))}
          <Progress value={value}>
            <Progress.Circle theme={{ size: 120 }} />
          </Progress>
        </div>
      </div>

      <div className="flex flex-col gap-3">
        <div className="text-sm text-gray-ff">Circle (transfer)</div>
        <div className="flex items-center gap-4">
          {THEME_SIZE.map(size => (
            <Progress key={`t-${String(size)}`} value={value}>
              <Progress.Circle theme={{ size }} variant="transfer" />
            </Progress>
          ))}
        </div>
      </div>

      <div className="flex flex-col gap-3">
        <div className="text-sm text-gray-ff">Arc (transfer + theta)</div>
        <div className="flex items-center gap-4">
          {THEME_SIZE.map(size => (
            <Progress key={`a-${String(size)}`} value={value}>
              <Progress.Arc theme={{ size }} variant="transfer" theta={60} />
            </Progress>
          ))}
          <Progress value={value}>
            <Progress.Arc theme={{ size: 120 }} variant="transfer" theta={120} />
          </Progress>
        </div>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/progress/examples/circle-and-arc.vue
<script setup lang="ts">
import { THEME_SIZE } from '@raxium/shared/constant'
import { ref } from 'vue'
import { Progress, ProgressArc, ProgressCircle } from '../index'

const value = ref(70)
</script>

<template>
  <div class="w-full flex flex-col gap-6">
    <div class="flex flex-col gap-3">
      <div class="text-sm text-gray-ff">
        Circle (default)
      </div>
      <div class="flex items-center gap-4">
        <Progress
          v-for="size in THEME_SIZE"
          :key="String(size)"
          :model-value="value"
        >
          <ProgressCircle :theme="{ size }" />
        </Progress>
        <Progress :model-value="value">
          <ProgressCircle :theme="{ size: 120 }" />
        </Progress>
      </div>
    </div>

    <div class="flex flex-col gap-3">
      <div class="text-sm text-gray-ff">
        Circle (transfer)
      </div>
      <div class="flex items-center gap-4">
        <Progress
          v-for="size in THEME_SIZE"
          :key="`t-${String(size)}`"
          :model-value="value"
        >
          <ProgressCircle
            :theme="{ size }"
            variant="transfer"
          />
        </Progress>
      </div>
    </div>

    <div class="flex flex-col gap-3">
      <div class="text-sm text-gray-ff">
        Arc (transfer + theta)
      </div>
      <div class="flex items-center gap-4">
        <Progress
          v-for="size in THEME_SIZE"
          :key="`a-${String(size)}`"
          :model-value="value"
        >
          <ProgressArc
            :theme="{ size }"
            variant="transfer"
            :theta="60"
          />
        </Progress>
        <Progress :model-value="value">
          <ProgressArc
            :theme="{ size: 120 }"
            variant="transfer"
            :theta="120"
          />
        </Progress>
      </div>
    </div>
  </div>
</template>
