// packages/react/core/src/components/progress/examples/linear-variants.tsx
import { useState } from 'react'
import { Progress } from '../index'

export function ProgressLinearVariantsExample() {
  const [value] = useState(45)

  return (
    <div className="w-full flex flex-col gap-4">
      <div className="flex items-center gap-4">
        <Progress className="w-80" value={value}>
          <Progress.Linear variant="default" />
        </Progress>
        <span className="text-sm text-gray-ff">default</span>
      </div>

      <div className="flex items-center gap-4">
        <Progress className="w-80" value={value}>
          <Progress.Linear variant="robbin" />
        </Progress>
        <span className="text-sm text-gray-ff">robbin</span>
      </div>

      <div className="flex items-center gap-4">
        <Progress className="w-80" value={value}>
          <Progress.Linear variant="transfer" />
        </Progress>
        <span className="text-sm text-gray-ff">transfer</span>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/progress/examples/linear-variants.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Progress, ProgressLinear } from '../index'

const value = ref(45)
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="flex items-center gap-4">
      <Progress class="w-80" :model-value="value">
        <ProgressLinear variant="default" />
      </Progress>
      <span class="text-sm text-gray-ff">default</span>
    </div>

    <div class="flex items-center gap-4">
      <Progress class="w-80" :model-value="value">
        <ProgressLinear variant="robbin" />
      </Progress>
      <span class="text-sm text-gray-ff">robbin</span>
    </div>

    <div class="flex items-center gap-4">
      <Progress class="w-80" :model-value="value">
        <ProgressLinear variant="transfer" />
      </Progress>
      <span class="text-sm text-gray-ff">transfer</span>
    </div>
  </div>
</template>
