// packages/react/core/src/components/progress/examples/sizes-and-orientation.tsx
import { THEME_SIZE } from '@raxium/shared/constant'
import { useState } from 'react'
import { Progress } from '../index'

export function ProgressSizesAndOrientationExample() {
  const [value] = useState(65)

  return (
    <div className="w-full flex flex-col gap-6">
      <div className="flex flex-col gap-3">
        <div className="text-sm text-gray-ff">Horizontal sizes</div>
        {THEME_SIZE.map(size => (
          <Progress
            key={String(size)}
            className="w-80"
            value={value}
            theme={{ size }}
          >
            <Progress.Linear />
          </Progress>
        ))}
      </div>

      <div className="flex flex-col gap-3">
        <div className="text-sm text-gray-ff">Vertical sizes</div>
        <div className="flex items-end gap-6">
          {THEME_SIZE.map(size => (
            <Progress
              key={`v-${String(size)}`}
              className="h-30"
              orientation="vertical"
              value={value}
              theme={{ size }}
            >
              <Progress.Linear />
            </Progress>
          ))}
        </div>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/progress/examples/sizes-and-orientation.vue
<script setup lang="ts">
import { THEME_SIZE } from '@raxium/shared/constant'
import { ref } from 'vue'
import { Progress, ProgressLinear } from '../index'

const value = ref(65)
</script>

<template>
  <div class="w-full flex flex-col gap-6">
    <div class="flex flex-col gap-3">
      <div class="text-sm text-gray-ff">
        Horizontal sizes
      </div>
      <Progress
        v-for="size in THEME_SIZE"
        :key="String(size)"
        class="w-80"
        :model-value="value"
        :theme="{ size }"
      >
        <ProgressLinear />
      </Progress>
    </div>

    <div class="flex flex-col gap-3">
      <div class="text-sm text-gray-ff">
        Vertical sizes
      </div>
      <div class="flex items-end gap-6">
        <Progress
          v-for="size in THEME_SIZE"
          :key="`v-${String(size)}`"
          class="h-30"
          orientation="vertical"
          :model-value="value"
          :theme="{ size }"
        >
          <ProgressLinear />
        </Progress>
      </div>
    </div>
  </div>
</template>
