// packages/vue/core/src/components/select/Select.vue
<script setup lang="ts" generic="T extends CollectionItem">
import type { CollectionItem, UseSelectProps } from '@ark-ui/vue/select'
import type { SelectEmits, SelectProps } from '.'
import { Select, useSelect } from '@ark-ui/vue/select'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useConfig } from '@raxium/vue/composables/useConfig'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { defaults } from 'es-toolkit/compat'
import { computed, mergeProps } from 'vue'

const {
  class: propsClass,
  theme: propsTheme,
  craft,
  lazyMount = undefined,
  unmountOnExit = undefined,
  ...props
} = defineProps<SelectProps<T>>()
const emits = defineEmits<SelectEmits<T>>()
const selectConfig = useConfig('select', () => ({ lazyMount, unmountOnExit }))
const forwarded = useForwardProps(props)
const selectRoot = useSelect<T>(
  computed(
    () =>
      mergeProps(forwarded.value as Record<string, unknown>, {
        positioning: defaults(
          { ...(forwarded.value.positioning ?? {}) },
          { placement: selectConfig.value?.placement },
        ),
      }) as unknown as UseSelectProps<T>,
  ),
  emits,
)

// theme
const theme = useTheme(
  () => propsTheme,
  () => selectConfig.value?.theme,
)
const themed = useThemeCraft(theme, 'tvSelect', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvSelect')

// expose
defineExpose({ $api: selectRoot })
useForwardExpose()
</script>

<template>
  <Select.RootProvider
    :value="selectRoot"
    :lazy-mount="selectConfig?.lazyMount"
    :unmount-on-exit="selectConfig?.unmountOnExit"
    :class="crafts.root(cxc(propsClass))"
  >
    <slot />
    <Select.HiddenSelect />
  </Select.RootProvider>
</template>

// packages/react/core/src/components/select/Select.tsx
import type { CollectionItem } from '@ark-ui/react/select'
import type { SelectProps } from './props'
import { Select as ArkSelect } from '@ark-ui/react/select'
import { useConfig } from '@raxium/react/hooks/useConfig'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { defaults } from 'es-toolkit/compat'
import { useMemo } from 'react'

export function SelectRoot<T extends CollectionItem>({
  className,
  theme: propsTheme,
  craft,
  lazyMount,
  unmountOnExit,
  positioning,
  children,
  ...props
}: SelectProps<T>) {
  const selectConfig = useConfig('select', { lazyMount, unmountOnExit })
  const mergedPositioning = useMemo(
    () => defaults({ ...(positioning ?? {}) }, { placement: selectConfig?.placement }),
    [positioning, selectConfig?.placement],
  )
  const theme = useTheme(propsTheme, selectConfig?.theme)
  const themed = useThemeCraft(theme, 'tvSelect', craft)
  const crafts = useCraft(themed, 'tvSelect')

  return (
    <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
      <ArkSelect.Root
        className={crafts.root(cxc(className))}
        lazyMount={selectConfig?.lazyMount}
        unmountOnExit={selectConfig?.unmountOnExit}
        positioning={mergedPositioning}
        {...props}
      >
        {children}
        <ArkSelect.HiddenSelect />
      </ArkSelect.Root>
    </ProvideComponentTheme>
  )
}

SelectRoot.displayName = 'Select'
