// packages/vue/core/src/components/select/SelectItemGroup.vue
<script setup lang="ts">
import type { SelectItemGroupProps } from '.'
import { Select } from '@ark-ui/vue/select'
import { useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  label,
  ui,
  ...props
} = defineProps<SelectItemGroupProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvSelect')
</script>

<template>
  <Select.ItemGroup
    v-bind="forwarded"
    :class="crafts.itemGroup(cxc(ui?.root, propsClass))"
  >
    <slot name="label">
      <Select.ItemGroupLabel :class="crafts.itemGroupLabel(cxc(ui?.label))">
        {{ label }}
      </Select.ItemGroupLabel>
    </slot>
    <slot />
  </Select.ItemGroup>
</template>

// packages/react/core/src/components/select/SelectItemGroup.tsx
import type { SelectItemGroupProps } from './props'
import { Select as ArkSelect } from '@ark-ui/react/select'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const SelectItemGroup = forwardRef<HTMLDivElement, SelectItemGroupProps>(
  ({ className, theme: propsTheme, label, ui, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvSelect')

    return (
      <ArkSelect.ItemGroup
        ref={ref}
        className={crafts.itemGroup(cxc(ui?.root, className))}
        {...props}
      >
        {label != null && label !== '' && (
          <ArkSelect.ItemGroupLabel className={crafts.itemGroupLabel(cxc(ui?.label))}>
            {label}
          </ArkSelect.ItemGroupLabel>
        )}
        {children}
      </ArkSelect.ItemGroup>
    )
  },
)

SelectItemGroup.displayName = 'Select.ItemGroup'
