// packages/vue/core/src/components/select/SelectTrigger.vue
<script setup lang="ts">
import type { SelectTriggerProps } from '.'
import { Select } from '@ark-ui/vue/select'
import { useForwardProps } from '@ark-ui/vue/utils'
import { ChevronDown, CircleX } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  clearable,
  ...props
} = defineProps<SelectTriggerProps>()
const forwarded = useForwardProps(props)

const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvSelect')
</script>

<template>
  <Select.Control>
    <Select.Trigger
      v-bind="forwarded"
      :class="crafts.trigger(cxc(propsClass))"
    >
      <slot />
      <Select.ClearTrigger
        v-if="clearable"
        :class="crafts.clearTrigger()"
      >
        <slot name="clearIcon">
          <CircleX />
        </slot>
      </Select.ClearTrigger>
      <Select.Indicator :class="crafts.indicator()">
        <slot name="indicator">
          <ChevronDown />
        </slot>
      </Select.Indicator>
    </Select.Trigger>
  </Select.Control>
</template>

// packages/react/core/src/components/select/SelectTrigger.tsx
import type { SelectTriggerProps } from './props'
import { Select as ArkSelect } from '@ark-ui/react/select'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { ChevronDown, CircleX } from 'lucide-react'
import { forwardRef } from 'react'

export const SelectTrigger = forwardRef<HTMLButtonElement, SelectTriggerProps>(
  (
    {
      className,
      theme: propsTheme,
      clearable,
      clearIcon,
      indicator,
      children,
      ...props
    },
    ref,
  ) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvSelect')

    return (
      <ArkSelect.Control>
        <ArkSelect.Trigger
          ref={ref}
          className={crafts.trigger(cxc(className))}
          {...props}
        >
          {children}
          {clearable && (
            <ArkSelect.ClearTrigger className={crafts.clearTrigger()}>
              {clearIcon ?? <CircleX />}
            </ArkSelect.ClearTrigger>
          )}
          <ArkSelect.Indicator className={crafts.indicator()}>
            {indicator ?? <ChevronDown />}
          </ArkSelect.Indicator>
        </ArkSelect.Trigger>
      </ArkSelect.Control>
    )
  },
)

SelectTrigger.displayName = 'Select.Trigger'
