// packages/vue/core/src/components/tabs/examples/controlled.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import { Tabs, TabsContent, TabsIndicator, TabsList, TabsTrigger } from '../index'

const value = ref('tab-7')
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="flex items-center gap-2">
      <Button variant="outlined" @click="value = 'tab-1'">
        Tab 1
      </Button>
      <Button variant="outlined" @click="value = 'tab-7'">
        Tab 7
      </Button>
      <Button variant="outlined" @click="value = 'tab-10'">
        Tab 10
      </Button>
      <span class="text-sm text-gray-ff">value: {{ value }}</span>
    </div>

    <Tabs v-model="value">
      <TabsList class="w-90">
        <TabsTrigger v-for="index in 10" :key="index" :value="`tab-${index}`">
          Tab {{ index }}
        </TabsTrigger>
        <TabsIndicator />
      </TabsList>

      <TabsContent v-for="index in 10" :key="index" :value="`tab-${index}`">
        Content {{ index }}
      </TabsContent>
    </Tabs>
  </div>
</template>

// packages/react/core/src/components/tabs/examples/controlled.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Tabs } from '../index'

const items = Array.from({ length: 10 }, (_, i) => {
  const n = i + 1
  return { value: `tab-${n}`, label: `Tab ${n}`, content: `Content ${n}` }
})

export function TabsControlledExample() {
  const [value, setValue] = useState('tab-7')

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <Button variant="outlined" onClick={() => setValue('tab-1')}>
          Tab 1
        </Button>
        <Button variant="outlined" onClick={() => setValue('tab-7')}>
          Tab 7
        </Button>
        <Button variant="outlined" onClick={() => setValue('tab-10')}>
          Tab 10
        </Button>
        <span className="text-sm text-gray-ff">
          value:
          {' '}
          {value}
        </span>
      </div>

      <Tabs value={value} onValueChange={details => setValue(details.value)}>
        <Tabs.List className="w-90">
          {items.map(item => (
            <Tabs.Trigger key={item.value} value={item.value}>
              {item.label}
            </Tabs.Trigger>
          ))}
          <Tabs.Indicator />
        </Tabs.List>
        {items.map(item => (
          <Tabs.Content key={item.value} value={item.value}>
            {item.content}
          </Tabs.Content>
        ))}
      </Tabs>
    </div>
  )
}
