// packages/react/core/src/components/accordion/Accordion.tsx
import type { AccordionProps } from './props'
import { Accordion as ArkAccordion } from '@ark-ui/react/accordion'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const AccordionRoot = forwardRef<HTMLDivElement, AccordionProps>(
  ({ className, theme: propsTheme, craft, children, ...props }, ref) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvAccordion', craft)
    const crafts = useCraft(themed, 'tvAccordion')

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkAccordion.Root
          ref={ref}
          className={crafts.root(cxc(className))}
          {...props}
        >
          {children}
        </ArkAccordion.Root>
      </ProvideComponentTheme>
    )
  },
)

AccordionRoot.displayName = 'Accordion'

// packages/vue/core/src/components/accordion/Accordion.vue
<script setup lang="ts">
import type { AccordionRootEmits, UseAccordionReturn } from '@ark-ui/vue/accordion'
import type { UnwrapRef } from 'vue'
import type { AccordionProps } from '.'
import { Accordion, useAccordion } from '@ark-ui/vue/accordion'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'

const { class: propsClass, theme: propsTheme, craft, ...props } = defineProps<AccordionProps>()
const emit = defineEmits<AccordionRootEmits>()
defineSlots<{
  default: (props: UnwrapRef<UseAccordionReturn>) => unknown
}>()
const forwarded = useForwardProps(props)
const accordion = useAccordion(forwarded, emit) as UseAccordionReturn

const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvAccordion', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvAccordion')

defineExpose({ $api: accordion })
useForwardExpose()
</script>

<template>
  <Accordion.RootProvider
    :value="accordion"
    :class="crafts.root(cxc(propsClass))"
  >
    <slot v-bind="accordion" />
  </Accordion.RootProvider>
</template>
