// packages/react/core/src/components/accordion/AccordionItem.tsx
import type { AccordionItemProps } from './props'
import { Accordion as ArkAccordion } from '@ark-ui/react/accordion'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const AccordionItem = forwardRef<HTMLDivElement, AccordionItemProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvAccordion')

    return (
      <ArkAccordion.Item
        ref={ref}
        className={crafts.item(cxc(className))}
        {...props}
      >
        {children}
      </ArkAccordion.Item>
    )
  },
)

AccordionItem.displayName = 'Accordion.Item'

// packages/vue/core/src/components/accordion/AccordionItem.vue
<script setup lang="ts">
import type { AccordionItemProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Accordion } from '@ark-ui/vue/accordion'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<AccordionItemProps>()
const forwarded = useForwardProps(props)

const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvAccordion')
</script>

<template>
  <Accordion.Item
    v-bind="forwarded"
    :class="crafts.item(cxc(propsClass))"
  >
    <slot />
  </Accordion.Item>
</template>
