// packages/react/core/src/components/badge/Badge.tsx
import type { Ref } from 'react'
import type { BadgeProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useMemo } from 'react'

export const Badge = forwardRef<HTMLElement, BadgeProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      as = 'div',
      asChild,
      variant,
      children,
      ...props
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const variants = useMemo(() => ({ variant }), [variant])
    const crafts = useCraft(theme, 'tvBadge', variants, craft)
    const classNameResolved = crafts(cxc(className))

    switch (as) {
      case 'sup':
        return (
          <ark.sup
            ref={ref}
            className={classNameResolved}
            data-variant={variant}
            asChild={asChild}
            {...props}
          >
            {children}
          </ark.sup>
        )
      case 'div':
        return (
          <ark.div
            ref={ref as Ref<HTMLDivElement>}
            className={classNameResolved}
            data-variant={variant}
            asChild={asChild}
            {...props}
          >
            {children}
          </ark.div>
        )
      default: {
        const _exhaustive: never = as
        return _exhaustive
      }
    }
  },
)

Badge.displayName = 'Badge'

// packages/vue/core/src/components/badge/Badge.vue
<script setup lang="ts">
import type { BadgeProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { ark } from '@ark-ui/vue/factory'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables/useCraft'
import { useTheme } from '@raxium/vue/composables/useTheme'

const {
  craft,
  class: propsClass,
  theme: propsTheme,
  as = 'div',
  asChild,
  variant,
  ...props
} = defineProps<BadgeProps>()
const forwarded = useForwardProps(props)

// theme — tvBadge is base-only, so crafts() returns a string
const theme = useTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvBadge', () => ({ variant }), () => craft)
</script>

<template>
  <component
    :is="as === 'div' ? ark.div : ark.sup"
    v-bind="forwarded"
    :class="crafts(cxc(propsClass))"
    :data-variant="variant"
    :as-child="asChild"
  >
    <slot />
  </component>
</template>
