// packages/vue/core/src/components/input/examples/states.vue
<script setup lang="ts">
import { Input } from '../index'
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <Input class="w-60" placeholder="Clearable" clearable />
    <Input class="w-60" placeholder="Disabled" disabled />
    <Input class="w-60" placeholder="Readonly" readonly default-value="1234567890" :maxlength="10" />
  </div>
</template>

// packages/react/core/src/components/input/examples/states.tsx
import { Input } from '../index'

export function InputStatesExample() {
  return (
    <div className="w-full flex flex-col gap-3">
      <Input className="w-60" placeholder="Clearable" clearable />
      <Input className="w-60" placeholder="Disabled" disabled />
      <Input
        className="w-60"
        placeholder="Readonly"
        readOnly
        defaultValue="1234567890"
        maxLength={10}
      />
    </div>
  )
}
