// packages/vue/core/src/components/hotkey/Hotkey.vue
<script setup lang="ts">
import type { HotkeyProps } from '.'
import { ark } from '@ark-ui/vue/factory'
import { useForwardExpose } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme } from '@raxium/vue/composables'
import { isEmpty, without } from 'es-toolkit/compat'
import { computed, nextTick, reactive, ref, watch, watchEffect } from 'vue'
import { CodesMap, isAccebilityCode, isAssistCode, isDeleteCode, isMainCode } from './keycode'

const {
  class: propsClass,
  hotkey,
  placeholder: propsPlaceholder = '',
  disabled,
  readonly,
  theme: propsTheme,
  craft,
  ui,
} = defineProps<HotkeyProps>()

const emits = defineEmits<{
  'update:hotkey': [value: string]
  'focus': [event: Event]
  'blur': [event: Event]
  'error': [error: Error]
  'cancel': [keycodes: string[], hotkey: string]
  'change': [keycodes: string[], hotkey: string]
}>()
const { forwardRef, currentElement } = useForwardExpose()

const isFocus = ref(false)
const inputState = computed(() => {
  if (disabled)
    return 'disabled'
  if (readonly)
    return 'readonly'
  return isFocus.value ? 'focused' : 'blur'
})

function onFocus(event: Event) {
  isFocus.value = true
  moveSelectionArchor()
  emits('focus', event)
}
function onBlur(event: Event) {
  isFocus.value = false
  setInnerHotkey()
  resetData()
  emits('blur', event)
}

const innerHotkey = ref(hotkey)
const placeholder = ref('')

function setInnerHotkey(hk?: string) {
  const _hotkey = hk || hotkey
  const _placeholder
    = typeof propsPlaceholder === 'function' ? propsPlaceholder(isFocus.value) : propsPlaceholder
  if (isEmpty(_hotkey)) {
    if (isFocus.value) {
      placeholder.value = _placeholder || 'Press hotkey'
    }
    else {
      placeholder.value = _placeholder || 'No hotkey assigned'
    }
  }
  innerHotkey.value = _hotkey
}
watch(() => hotkey, setInnerHotkey, { immediate: true })

const keydownRecord = reactive({
  mainCode: '',
  assistCodes: [] as string[],
})
const judgeKeyArr = ref([] as string[])
const resultCodeArr = ref([] as string[])
function onKeydown(event: KeyboardEvent) {
  const { keyCode, code, repeat } = event
  event.preventDefault()
  event.stopPropagation()
  // ESC || backspace
  if (!repeat && (isDeleteCode(code) || isAccebilityCode(code)))
    return false
  // 消除repeat
  if (repeat)
    return false
  // keyCode 出现大于等于229的情况 代表该hotkey被占用, 无法识别keydown, 但是在keyup中可以捕获
  if (keyCode >= 229)
    return false
  // 如果记录了 mainKey return
  if (keydownRecord.mainCode === code)
    return false
  // 如果记录了 assist key return

  if (keydownRecord.assistCodes.includes(code))
    return false

  // 记录下过滤后的 code 信息
  if (isMainCode(code)) {
    keydownRecord.mainCode = code
  }
  else if (isAssistCode(code)) {
    keydownRecord.assistCodes.push(code)
  }

  judgeKeyArr.value = [...judgeKeyArr.value, code]

  // 处理输入框显示
  moveSelectionArchor()
  const assistStr = keydownRecord.assistCodes.reduce((acc, c) => {
    return acc === '' ? CodesMap[c].name : `${acc} + ${CodesMap[c].name}`
  }, '')

  innerHotkey.value = keydownRecord.mainCode
    ? `${
      isEmpty(assistStr)
        ? CodesMap[keydownRecord.mainCode].name
        : `${assistStr} + ${CodesMap[keydownRecord.mainCode].name}`
    }`
    : assistStr
}

const keyupSet = ref<Set<string>>(new Set())
function onKeyUp(event: KeyboardEvent) {
  const { code } = event
  event.preventDefault()
  event.stopPropagation()
  if (isAccebilityCode(code)) {
    code === 'Escape' && currentElement.value?.blur()
    return
  }
  if (isDeleteCode(code)) {
    // ESC || backspace
    if (innerHotkey.value) {
      innerHotkey.value = ''
      resetData()
      emits('update:hotkey', '')
      emits('cancel', [], 'ESC')
      emits('change', [], 'ESC')
    }
    return
  }

  // 因为热键冲突的原因, keydown无法捕获到主键(mainCode), 但在keyup中可以捕获到
  // 所以记录一份keyup set用于补充主键
  keyupSet.value.add(code)

  // 依次清空judge array, 从而触发watch
  if (judgeKeyArr.value.includes(code)) {
    judgeKeyArr.value.splice(judgeKeyArr.value.indexOf(code), 1)
  }
}

const IMELocked = ref(false)
function onInput() {
  IMELocked.value = true
  setInnerHotkey()
}

/**
 * 将光标移至末尾。原生 input 上不应用 document Selection（rangeCount 常为 0，getRangeAt(0) 抛 IndexSizeError）。
 */
function moveSelectionArchor() {
  nextTick(() => {
    const el = currentElement.value
    if (!(el instanceof HTMLInputElement) && !(el instanceof HTMLTextAreaElement))
      return
    try {
      const len = el.value?.length ?? 0
      el.focus()
      el.setSelectionRange(len, len)
    }
    catch {
      /* readonly / disabled */
    }
  })
}

function resetData() {
  keydownRecord.mainCode = ''
  keydownRecord.assistCodes = []
  keyupSet.value.clear()
  judgeKeyArr.value = []
  resultCodeArr.value = []
}

watchEffect((cleanup) => {
  if (judgeKeyArr.value.length === 0 && inputState.value === 'focused') {
    if (IMELocked.value) {
      // 如果IME是输入状态 直接返回
      IMELocked.value = false
      setInnerHotkey()
      if (currentElement.value) {
        ;(currentElement.value as HTMLInputElement).value = innerHotkey.value
        currentElement.value.blur()
      }
      emits('error', new Error('IME is active, please close it before inputing'))
      return
    }
    // keydown未捕获到maincode
    if (!keydownRecord.mainCode) {
      // 在keyup Set中找一个主键
      let keyupMainCode = null
      keyupSet.value.forEach((c) => {
        isMainCode(c) && (keyupMainCode = c)
      })
      // 仍然没找到主键, 还原设置
      if (!keyupMainCode) {
        setInnerHotkey()
        resetData()
        return
      }
      // 否则, 重新记录keydown中的mainCode
      keydownRecord.mainCode = keyupMainCode
    }

    // resultCodeArr.value = []
    if (isEmpty(keydownRecord.assistCodes)) {
      // keydown未捕获assistCode, 给一个默认值
      resultCodeArr.value = keydownRecord.assistCodes = ['ControlLeft', 'ShiftLeft']
    }
    else {
      // 如果有, 需要重排 assist code 顺序
      if (
        keydownRecord.assistCodes.includes('ControlLeft')
        || keydownRecord.assistCodes.includes('ControlRight')
      ) {
        resultCodeArr.value.push('ControlLeft')
      }
      if (
        keydownRecord.assistCodes.includes('AltLeft')
        || keydownRecord.assistCodes.includes('AltRight')
      ) {
        resultCodeArr.value.push('AltLeft')
      }
      if (
        keydownRecord.assistCodes.includes('ShiftLeft')
        || keydownRecord.assistCodes.includes('ShiftRight')
      ) {
        resultCodeArr.value.push('ShiftLeft')
      }
      resultCodeArr.value = resultCodeArr.value.concat(
        without(
          keydownRecord.assistCodes,
          'ControlLeft',
          'ControlRight',
          'AltLeft',
          'AltRight',
          'ShiftLeft',
          'ShiftRight',
        ),
      )
    }
    resultCodeArr.value.push(keydownRecord.mainCode)
    innerHotkey.value = resultCodeArr.value.map(c => CodesMap[c].name).join(' + ')
    emits('update:hotkey', innerHotkey.value)
    emits('change', resultCodeArr.value, innerHotkey.value)
    currentElement.value?.blur()
    cleanup(resetData)
  }
})

// theme
const theme = useTheme(() => propsTheme, undefined, () => craft)
const crafts = useCraft(theme, 'tvHotkey')
</script>

<template>
  <ark.div
    :class="crafts.root(cxc(ui?.root, propsClass))"
    :data-placeholder="placeholder"
    :data-state="inputState"
  >
    <ark.input
      :ref="forwardRef"
      :class="crafts.input(cxc(ui?.input))"
      :disabled="disabled ? true : undefined"
      :spellcheck="false"
      :data-state="inputState"
      :readonly="readonly ? true : undefined"
      :placeholder="placeholder"
      :value="innerHotkey"
      aria-label="Hotkey input"
      @focus="onFocus"
      @blur="onBlur"
      @keydown="onKeydown"
      @keyup="onKeyUp"
      @input="onInput"
    />
    <ark.span class="sr-only">
      {{ innerHotkey }}
    </ark.span>
  </ark.div>
</template>

// packages/react/core/src/components/hotkey/Hotkey.tsx
import type { HotkeyProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { composeRefs } from '@raxium/react/utils/compose-refs'
import { cxc } from '@raxium/themes/utils'
import { isEmpty, without } from 'es-toolkit/compat'
import { forwardRef, useEffect, useLayoutEffect, useRef, useState } from 'react'
import { CodesMap, isAccebilityCode, isAssistCode, isDeleteCode, isMainCode } from './keycode'

type InputState = 'disabled' | 'readonly' | 'focused' | 'blur'

function placeholderText(
  placeholder: HotkeyProps['placeholder'],
  focused: boolean,
  empty: boolean,
): string {
  const custom = typeof placeholder === 'function' ? placeholder(focused) : (placeholder ?? '')
  if (!empty)
    return custom
  return custom || (focused ? 'Press hotkey' : 'No hotkey assigned')
}

export const Hotkey = forwardRef<HTMLInputElement, HotkeyProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      hotkey: hotkeyProp,
      defaultHotkey = '',
      placeholder: propsPlaceholder = '',
      disabled,
      readOnly,
      ui,
      onHotkeyChange,
      onFocus,
      onBlur,
      onError,
      onCancel,
      onChange,
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const crafts = useCraft(theme, 'tvHotkey', undefined, craft)
    const inputRef = useRef<HTMLInputElement>(null)
    const [focused, setFocused] = useState(false)
    const focusedRef = useRef(false)
    const [display, setDisplay] = useState(hotkeyProp ?? defaultHotkey)
    const committedRef = useRef(hotkeyProp ?? defaultHotkey)
    const imeLockedRef = useRef(false)
    const keydownRecordRef = useRef({ mainCode: '', assistCodes: [] as string[] })
    const judgeKeyArrRef = useRef<string[]>([])
    const resultCodeArrRef = useRef<string[]>([])
    const keyupSetRef = useRef(new Set<string>())

    const inputState: InputState = disabled
      ? 'disabled'
      : readOnly
        ? 'readonly'
        : focused
          ? 'focused'
          : 'blur'
    const placeholder = placeholderText(propsPlaceholder, focused, isEmpty(display))

    useEffect(() => {
      if (hotkeyProp === undefined)
        return
      committedRef.current = hotkeyProp
      if (!focusedRef.current)
        setDisplay(hotkeyProp)
    }, [hotkeyProp])

    function resetData() {
      keydownRecordRef.current = { mainCode: '', assistCodes: [] }
      keyupSetRef.current.clear()
      judgeKeyArrRef.current = []
      resultCodeArrRef.current = []
    }

    function restoreDisplay(next?: string) {
      const value = next ?? committedRef.current
      setDisplay(value)
    }

    function emitHotkey(next: string) {
      committedRef.current = next
      setDisplay(next)
      onHotkeyChange?.(next)
    }

    function moveSelectionArchor() {
      const el = inputRef.current
      if (!el)
        return
      try {
        const len = el.value?.length ?? 0
        el.focus()
        el.setSelectionRange(len, len)
      }
      catch {
        /* readonly / disabled */
      }
    }

    useLayoutEffect(() => {
      if (focused)
        moveSelectionArchor()
    }, [display, focused])

    function tryCommit() {
      if (judgeKeyArrRef.current.length !== 0 || !focusedRef.current)
        return

      if (imeLockedRef.current) {
        imeLockedRef.current = false
        restoreDisplay()
        inputRef.current?.blur()
        onError?.(new Error('IME is active, please close it before inputing'))
        return
      }

      const record = keydownRecordRef.current
      if (!record.mainCode) {
        let keyupMainCode: string | null = null
        keyupSetRef.current.forEach((c) => {
          if (isMainCode(c))
            keyupMainCode = c
        })
        if (!keyupMainCode) {
          restoreDisplay()
          resetData()
          return
        }
        record.mainCode = keyupMainCode
      }

      if (isEmpty(record.assistCodes)) {
        resultCodeArrRef.current = record.assistCodes = ['ControlLeft', 'ShiftLeft']
      }
      else {
        const ordered: string[] = []
        if (record.assistCodes.includes('ControlLeft') || record.assistCodes.includes('ControlRight'))
          ordered.push('ControlLeft')
        if (record.assistCodes.includes('AltLeft') || record.assistCodes.includes('AltRight'))
          ordered.push('AltLeft')
        if (record.assistCodes.includes('ShiftLeft') || record.assistCodes.includes('ShiftRight'))
          ordered.push('ShiftLeft')
        resultCodeArrRef.current = ordered.concat(
          without(
            record.assistCodes,
            'ControlLeft',
            'ControlRight',
            'AltLeft',
            'AltRight',
            'ShiftLeft',
            'ShiftRight',
          ),
        )
      }
      resultCodeArrRef.current.push(record.mainCode)
      const next = resultCodeArrRef.current.map(c => CodesMap[c].name).join(' + ')
      emitHotkey(next)
      onChange?.(resultCodeArrRef.current, next)
      inputRef.current?.blur()
      resetData()
    }

    return (
      <ark.div
        className={crafts.root(cxc(ui?.root, className))}
        data-placeholder={placeholder}
        data-state={inputState}
      >
        <ark.input
          ref={composeRefs(ref, inputRef)}
          className={crafts.input(cxc(ui?.input))}
          disabled={disabled ? true : undefined}
          spellCheck={false}
          data-state={inputState}
          readOnly={readOnly ? true : undefined}
          placeholder={placeholder}
          value={display}
          aria-label="Hotkey input"
          onFocus={(event) => {
            focusedRef.current = true
            setFocused(true)
            onFocus?.(event)
          }}
          onBlur={(event) => {
            focusedRef.current = false
            setFocused(false)
            restoreDisplay()
            resetData()
            onBlur?.(event)
          }}
          onKeyDown={(event) => {
            const { keyCode, code, repeat } = event
            event.preventDefault()
            event.stopPropagation()
            if (!repeat && (isDeleteCode(code) || isAccebilityCode(code)))
              return
            if (repeat)
              return
            if (keyCode >= 229)
              return
            const record = keydownRecordRef.current
            if (record.mainCode === code)
              return
            if (record.assistCodes.includes(code))
              return
            if (isMainCode(code))
              record.mainCode = code
            else if (isAssistCode(code))
              record.assistCodes.push(code)

            judgeKeyArrRef.current = [...judgeKeyArrRef.current, code]

            const assistStr = record.assistCodes.reduce((acc, c) => {
              return acc === '' ? CodesMap[c].name : `${acc} + ${CodesMap[c].name}`
            }, '')
            setDisplay(
              record.mainCode
                ? (isEmpty(assistStr)
                    ? CodesMap[record.mainCode].name
                    : `${assistStr} + ${CodesMap[record.mainCode].name}`)
                : assistStr,
            )
          }}
          onKeyUp={(event) => {
            const { code } = event
            event.preventDefault()
            event.stopPropagation()
            if (isAccebilityCode(code)) {
              if (code === 'Escape')
                inputRef.current?.blur()
              return
            }
            if (isDeleteCode(code)) {
              if (display) {
                emitHotkey('')
                resetData()
                onCancel?.([], 'ESC')
                onChange?.([], 'ESC')
              }
              return
            }

            keyupSetRef.current.add(code)
            const idx = judgeKeyArrRef.current.indexOf(code)
            if (idx !== -1)
              judgeKeyArrRef.current.splice(idx, 1)
            tryCommit()
          }}
          onInput={() => {
            imeLockedRef.current = true
            restoreDisplay()
            tryCommit()
          }}
        />
        <ark.span className="sr-only">{display}</ark.span>
      </ark.div>
    )
  },
)

Hotkey.displayName = 'Hotkey'
