// packages/react/core/src/components/menu/MenuContent.tsx
import type { CSSProperties } from 'react'
import type { MenuContentProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { Menu as ArkMenu } from '@ark-ui/react/menu'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useTeleportedDepthOwner } from '@raxium/react/hooks/useDepth'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTeleportDetection } from '@raxium/react/hooks/useTeleportDetection'
import { useThemeAttrs } from '@raxium/react/hooks/useThemeAttrs'
import { cn, cxc } from '@raxium/themes/utils'
import { forwardRef, useMemo } from 'react'
import { splitMenuArrow } from './split-menu-arrow'

export const MenuContent = forwardRef<HTMLDivElement, MenuContentProps>(
  ({ className, theme: propsTheme, ui, children, ...props }, ref) => {
    const { isTeleported, setElementRef } = useTeleportDetection()
    const depth = useTeleportedDepthOwner({
      type: 'menu',
      active: isTeleported,
      fallbackZIndex: 'var(--z-dropdown, var(--z-index))',
    })
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvMenu')
    const themeAttrs = useThemeAttrs(theme)
    const { arrows, rest } = useMemo(() => splitMenuArrow(children), [children])

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <ArkMenu.Positioner
          ref={setElementRef}
          className={cn(ui?.positioner)}
          style={{ '--rui-z-index': isTeleported ? depth.zIndex : 'auto' } as CSSProperties}
        >
          <ArkMenu.Content
            ref={ref}
            className={crafts.content(cxc(ui?.content, className))}
            {...props}
            {...themeAttrs}
          >
            {arrows}
            <ark.div
              className={crafts.contentInner(cxc(ui?.inner))}
              {...themeAttrs}
            >
              {rest}
            </ark.div>
          </ArkMenu.Content>
        </ArkMenu.Positioner>
      </ProvideStructuralComponentTheme>
    )
  },
)

MenuContent.displayName = 'Menu.Content'

// packages/vue/core/src/components/menu/MenuContent.vue
<script setup lang="ts">
import type { MenuContentProps } from '.'
import { useForwardExpose } from '@ark-ui/vue'
import { Menu } from '@ark-ui/vue/menu'
import { useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import {
  useCraft,
  useInheritedTheme,
  useProvideStructuralComponentTheme,
  useTeleportDetection,
  useTeleportedDepthOwner,
  useThemeAttrs,
} from '@raxium/vue/composables'
import {
  checkContextVNodePosition,
  excludeVNodesByName,
  findVNodeByName,
} from '@raxium/vue/utils/vnode'
import { computed, useSlots } from 'vue'

const { class: propsClass, theme: propsTheme, ui, ...props } = defineProps<MenuContentProps>()
const forwarded = useForwardProps<MenuContentProps, { asChild?: boolean }>(props)

const slots = useSlots()
const defaultSlots = computed(() => slots.default?.())
checkContextVNodePosition(defaultSlots.value, 'MenuContext', 'MenuContent')
const arrowNode = computed(() => findVNodeByName(defaultSlots.value, 'MenuArrow'))
const otherNodes = computed(() => excludeVNodesByName(defaultSlots.value, 'MenuArrow'))

// teleport detection
const { isTeleported, setElementRef: setPositionerRef } = useTeleportDetection()
const depth = useTeleportedDepthOwner({
  type: 'menu',
  active: isTeleported,
  fallbackZIndex: 'var(--z-dropdown, var(--z-index))',
})

// theme
const theme = useInheritedTheme(() => propsTheme)
useProvideStructuralComponentTheme(theme, () => propsTheme)
const crafts = useCraft(theme, 'tvMenu')
const themeAttrs = useThemeAttrs(theme)
const positionerStyle = computed(() => ({
  '--rui-z-index': isTeleported.value ? depth.zIndex.value : 'auto',
}))

// forward expose
const { forwardRef } = useForwardExpose()
</script>

<template>
  <Menu.Positioner
    :ref="setPositionerRef"
    :class="[ui?.positioner]"
    :style="positionerStyle"
  >
    <Menu.Content
      v-bind="{ ...forwarded, ...themeAttrs }"
      :ref="forwardRef"
      :class="crafts.content(cxc(ui?.content, propsClass))"
    >
      <template v-if="arrowNode">
        <component :is="arrowNode" />
      </template>
      <div :class="crafts.contentInner(cxc(ui?.inner))">
        <template
          v-for="node in otherNodes"
          :key="node.key"
        >
          <component :is="node" />
        </template>
      </div>
    </Menu.Content>
  </Menu.Positioner>
</template>
