// packages/react/core/src/components/dialog/DialogBackdrop.tsx
import type { DialogBackdropProps } from './props'
import { useDialogContext } from '@ark-ui/react/dialog'
import { ark } from '@ark-ui/react/factory'
import { usePresence } from '@ark-ui/react/presence'
import { useConfig } from '@raxium/react/hooks/useConfig'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { useComposedRefs } from '@raxium/react/utils'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const DialogBackdrop = forwardRef<HTMLDivElement, DialogBackdropProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const dialog = useDialogContext()
    const dialogConfig = useConfig('dialog')
    const presence = usePresence({
      present: dialog.open,
      lazyMount: dialogConfig?.lazyMount,
      unmountOnExit: dialogConfig?.unmountOnExit,
    })
    const composedRef = useComposedRefs(presence.ref, ref)
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvDialog')

    if (presence.unmounted)
      return null

    return (
      <ark.div
        ref={composedRef}
        {...dialog.getBackdropProps()}
        {...presence.getPresenceProps()}
        className={crafts.backdrop(cxc(className))}
        {...props}
      >
        {children}
      </ark.div>
    )
  },
)

DialogBackdrop.displayName = 'Dialog.Backdrop'

// packages/vue/core/src/components/dialog/DialogBackdrop.vue
<script setup lang="ts">
import type { DialogBackdropProps } from '.'
import { useForwardExpose } from '@ark-ui/vue'
import { useDialogContext } from '@ark-ui/vue/dialog'
import { ark } from '@ark-ui/vue/factory'
import { usePresence } from '@ark-ui/vue/presence'
import { cxc } from '@raxium/themes/utils'
import { useConfig, useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { computed, mergeProps, useAttrs } from 'vue'

defineOptions({
  inheritAttrs: false,
})

const { class: propsClass, theme: propsTheme, asChild } = defineProps<DialogBackdropProps>()

const dialog = useDialogContext()
const dialogConfig = useConfig('dialog')
const presence = usePresence(
  computed(() => ({
    present: dialog.value.open,
    lazyMount: dialogConfig.value?.lazyMount,
    unmountOnExit: dialogConfig.value?.unmountOnExit,
  })),
)
const attrs = useAttrs()

const mergedProps = computed(() => {
  const parts: Array<Record<string, unknown>> = [
    dialog.value.getBackdropProps() as Record<string, unknown>,
    presence.value.presenceProps as Record<string, unknown>,
    attrs as unknown as Record<string, unknown>,
  ]
  return mergeProps(...parts)
})

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvDialog')

// expose
useForwardExpose()
</script>

<template>
  <ark.div
    v-if="!presence.unmounted"
    v-bind="mergedProps"
    :class="crafts.backdrop(cxc(propsClass))"
    :as-child="asChild"
  >
    <slot />
  </ark.div>
</template>
