// packages/react/core/src/components/dialog/Dialog.tsx
import type { DialogProps } from './props'
import type { DialogTriggerFrom } from './dialog-intercept-context'
import { Dialog as ArkDialog } from '@ark-ui/react/dialog'
import { useConfig } from '@raxium/react/hooks/useConfig'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { useCallback, useMemo, useRef } from 'react'
import { DialogInterceptContext, TriggerFrom } from './dialog-intercept-context'
import { useDialogOpenState } from './use-dialog-open-state'

export function DialogRoot({
  className: _className,
  theme: propsTheme,
  craft,
  lazyMount,
  unmountOnExit,
  beforeClose,
  open: openProp,
  defaultOpen,
  onOpenChange,
  onEscapeKeyDown,
  onInteractOutside,
  children,
  ...props
}: DialogProps) {
  const dialogConfig = useConfig('dialog', { lazyMount, unmountOnExit })
  const triggerFromRef = useRef<DialogTriggerFrom>(undefined)
  const setTriggerFrom = useCallback((from: DialogTriggerFrom) => {
    triggerFromRef.current = from
  }, [])
  const intercept = useMemo(
    () => ({ triggerFromRef, setTriggerFrom }),
    [setTriggerFrom],
  )
  const getTriggerFrom = useCallback(() => triggerFromRef.current, [])
  const { open, handleOpenChange } = useDialogOpenState({
    open: openProp,
    defaultOpen,
    beforeClose,
    onOpenChange,
    getTriggerFrom,
  })
  const theme = useTheme(propsTheme, dialogConfig?.theme)
  const themed = useThemeCraft(theme, 'tvDialog', craft)

  return (
    <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
      <DialogInterceptContext.Provider value={intercept}>
        <ArkDialog.Root
          open={open}
          lazyMount={dialogConfig?.lazyMount}
          unmountOnExit={dialogConfig?.unmountOnExit}
          onOpenChange={handleOpenChange}
          onEscapeKeyDown={(event) => {
            setTriggerFrom(TriggerFrom.ESCAPE)
            onEscapeKeyDown?.(event)
          }}
          onInteractOutside={(event) => {
            setTriggerFrom(TriggerFrom.OUTSIDE)
            onInteractOutside?.(event)
          }}
          {...props}
        >
          {children}
        </ArkDialog.Root>
      </DialogInterceptContext.Provider>
    </ProvideComponentTheme>
  )
}

DialogRoot.displayName = 'Dialog'

// packages/vue/core/src/components/dialog/Dialog.vue
<script setup lang="ts">
import type { UseDialogProps, UseDialogReturn } from '@ark-ui/vue/dialog'
import type { ComputedRef } from 'vue'
import type { DialogEmits, DialogProps } from '.'
import type {
  DialogInterceptContext,
  DialogTriggerFrom,
  FocusOutsideEvent,
  InteractOutsideEvent,
  OpenChangeDetails,
  PointerDownOutsideEvent,
  RequestDismissEvent,
} from './dialog-intercept-context'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { Dialog, useDialog } from '@ark-ui/vue/dialog'
import { useConfig } from '@raxium/vue/composables/useConfig'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { useTheme } from '@raxium/vue/composables/useTheme'
import { useThemeCraft } from '@raxium/vue/composables/useThemeCraft'
import { computed, nextTick, ref } from 'vue'
import { TriggerFrom } from './dialog-intercept-context'
import DialogInterceptProvider from './DialogInterceptProvider.vue'

const {
  class: propsClass,
  theme: propsTheme,
  lazyMount = undefined,
  unmountOnExit = undefined,
  craft,
  beforeClose,
  ...props
} = defineProps<DialogProps>()
const emits = defineEmits<DialogEmits>()

const dialogConfig = useConfig(
  'dialog',
  computed(() => ({ lazyMount, unmountOnExit })),
)
const forwarded = useForwardProps(props) as ComputedRef<
  UseDialogProps & { onExitComplete?: () => void }
>
const triggerFrom = ref<DialogTriggerFrom>(undefined)
const dialogInterceptContext: DialogInterceptContext = { triggerFrom }

const beforeClosePending = ref(false)
const bypassBeforeClose = ref(false)

function emitOpenChange(details: OpenChangeDetails) {
  emits('openChange', { ...details, from: triggerFrom.value })
  emits('update:open', details.open)
  forwarded.value.onOpenChange?.({
    ...details,
    from: triggerFrom.value,
  } as OpenChangeDetails)
}

const dialog = useDialog(
  computed(() => ({
    ...forwarded.value,
    onOpenChange: (details: OpenChangeDetails) => {
      if (!details.open && beforeClose && !bypassBeforeClose.value) {
        if (beforeClosePending.value) {
          dialog.value.setOpen(true)
          return
        }
        beforeClosePending.value = true
        dialog.value.setOpen(true)
        beforeClose({
          from: triggerFrom.value,
          resume: resumeBeforeClose,
          done: (autoClose = true) => {
            if (!beforeClosePending.value)
              return
            if (!autoClose) {
              resumeBeforeClose()
              return
            }
            beforeClosePending.value = false
            bypassBeforeClose.value = true
            dialog.value.setOpen(false)
            nextTick(() => {
              bypassBeforeClose.value = false
            })
          },
        })
        return
      }
      !beforeClosePending.value && emitOpenChange(details)
    },
    onEscapeKeyDown: (event: KeyboardEvent) => {
      triggerFrom.value = TriggerFrom.ESCAPE
      emits('escapeKeyDown', event)
      forwarded.value.onEscapeKeyDown?.(event)
    },
    onFocusOutside: (event: FocusOutsideEvent) => {
      emits('focusOutside', event)
      forwarded.value.onFocusOutside?.(event)
    },
    onInteractOutside: (event: InteractOutsideEvent) => {
      triggerFrom.value = TriggerFrom.OUTSIDE
      emits('interactOutside', event)
      forwarded.value.onInteractOutside?.(event)
    },
    onPointerDownOutside: (event: PointerDownOutsideEvent) => {
      emits('pointerDownOutside', event)
      forwarded.value.onPointerDownOutside?.(event)
    },
    onRequestDismiss: (event: RequestDismissEvent) => {
      emits('requestDismiss', event)
      forwarded.value.onRequestDismiss?.(event)
    },
  })),
)

function resumeBeforeClose() {
  if (!beforeClosePending.value)
    return
  beforeClosePending.value = false
  bypassBeforeClose.value = false
  dialog.value.setOpen(true)
}

// theme
const theme = useTheme(
  () => propsTheme,
  () => dialogConfig.value?.theme,
)
const themed = useThemeCraft(theme, 'tvDialog', () => craft)
useProvideComponentTheme(themed, () => propsTheme)

// expose
const dialogApi = computed(() => ({
  ...dialog.value,
  resumeBeforeClose,
}))
defineExpose({ $api: dialogApi as UseDialogReturn })
useForwardExpose()
</script>

<template>
  <Dialog.RootProvider
    :value="dialog"
    :lazy-mount="dialogConfig?.lazyMount ?? lazyMount"
    :unmount-on-exit="dialogConfig?.unmountOnExit ?? unmountOnExit"
    @exit-complete="
      () => {
        forwarded.onExitComplete?.()
        emits('exitComplete')
      }
    "
  >
    <DialogInterceptProvider :value="dialogInterceptContext">
      <slot />
    </DialogInterceptProvider>
  </Dialog.RootProvider>
</template>
