// packages/react/core/src/components/dialog/DialogBody.tsx
import type { DialogBodyProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { useStableId } from '@raxium/react/hooks/useStableId'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const DialogBody = forwardRef<HTMLDivElement, DialogBodyProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const id = useStableId('dialog-body')
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvDialog')

    return (
      <ark.div
        ref={ref}
        id={id}
        className={crafts.body(cxc(className))}
        data-scope="dialog"
        data-part="body"
        {...props}
      >
        {children}
      </ark.div>
    )
  },
)

DialogBody.displayName = 'Dialog.Body'

// packages/vue/core/src/components/dialog/DialogBody.vue
<script setup lang="ts">
import type { DialogBodyProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { ark } from '@ark-ui/vue/factory'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { useId } from 'vue'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<DialogBodyProps>()
const forwarded = useForwardProps(props)

const id = useId()
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvDialog')
</script>

<template>
  <ark.div
    v-bind="forwarded"
    :id="`dialog:${id}:body`"
    :class="crafts.body(cxc(propsClass))"
    data-scope="dialog"
    data-part="body"
  >
    <slot />
  </ark.div>
</template>
