// packages/react/core/src/components/dialog/DialogContent.tsx
import type { CSSProperties } from 'react'
import type { DialogContentProps } from './props'
import { Dialog as ArkDialog, useDialogContext } from '@ark-ui/react/dialog'
import { ark } from '@ark-ui/react/factory'
import { DepthOwnerProvider, useDepthOwner } from '@raxium/react/hooks/useDepth'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useThemeAttrs } from '@raxium/react/hooks/useThemeAttrs'
import { cn, cxc } from '@raxium/themes/utils'
import { X } from 'lucide-react'
import { forwardRef } from 'react'
import { createPortal } from 'react-dom'
import { DialogBackdrop } from './DialogBackdrop'
import { DialogCloseTrigger } from './DialogCloseTrigger'
import { hasDialogHeader } from './has-dialog-header'

export const DialogContent = forwardRef<HTMLDivElement, DialogContentProps>(
  ({ className, theme: propsTheme, ui, showClose = true, close, children, ...props }, ref) => {
    const dialog = useDialogContext()
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvDialog')
    const themeAttrs = useThemeAttrs(theme)
    const depthOwner = useDepthOwner('dialog', { active: dialog.open })
    const showContentClose = showClose && !hasDialogHeader(children)
    const defaultClose = (
      <DialogCloseTrigger asChild>
        <ark.button
          className={cn(['absolute', 'top-0', 'right-0'], crafts.close(cxc(ui?.close)))}
          data-variant="content-close"
        >
          <X />
          <span className="sr-only">Close</span>
        </ark.button>
      </DialogCloseTrigger>
    )

    if (typeof document === 'undefined')
      return null

    return createPortal(
      <ProvideStructuralComponentTheme theme={theme}>
        <DepthOwnerProvider owner={depthOwner}>
          <DialogBackdrop
            {...themeAttrs}
            className={crafts.backdrop(cxc(ui?.backdrop))}
            theme={theme}
            style={{ '--rui-z-index': depthOwner.backdropZIndex } as CSSProperties}
          />
          <ArkDialog.Positioner
            {...themeAttrs}
            className={crafts.positioner(cxc(ui?.positioner))}
            style={{ '--rui-z-index': depthOwner.contentZIndex } as CSSProperties}
          >
            <ArkDialog.Content
              ref={ref}
              {...themeAttrs}
              className={crafts.content(cxc(ui?.content, className))}
              {...props}
            >
              {children}
              {close ?? (showContentClose ? defaultClose : null)}
            </ArkDialog.Content>
          </ArkDialog.Positioner>
        </DepthOwnerProvider>
      </ProvideStructuralComponentTheme>,
      document.body,
    )
  },
)

DialogContent.displayName = 'Dialog.Content'

// packages/vue/core/src/components/dialog/DialogContent.vue
<script setup lang="ts">
import type { DialogContentProps } from '.'
import { Dialog, useDialogContext } from '@ark-ui/vue/dialog'
import { ark } from '@ark-ui/vue/factory'
import { X } from '@lucide/vue'
import { cn, cxc } from '@raxium/themes/utils'
import { provideDepthOwner, useCraft, useDepthOwner } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { useProvideStructuralComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { useThemeAttrs } from '@raxium/vue/composables/useThemeAttrs'
import { hasChildVNodeByName } from '@raxium/vue/utils/vnode'
import { computed, useAttrs, useSlots } from 'vue'
import { DialogBackdrop, DialogCloseTrigger } from '.'

defineOptions({
  inheritAttrs: false,
})

const {
  class: propsClass,
  theme: propsTheme,
  ui,
  showClose = true,
} = defineProps<DialogContentProps>()

const slots = useSlots()
const defaultSlots = computed(() => slots.default?.())
const hasDialogHeader = computed(() => hasChildVNodeByName(defaultSlots.value, 'DialogHeader'))
const showContentClose = computed(() => showClose && !hasDialogHeader.value)
const dialog = useDialogContext()
const open = computed(() => dialog.value.open)

// theme
const attrs = useAttrs()
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvDialog')
const themeAttrs = useThemeAttrs(theme)
useProvideStructuralComponentTheme(theme, () => propsTheme)

// depth
const depthOwner = useDepthOwner('dialog', { active: open })
provideDepthOwner(depthOwner)
// Single source of truth: expose z-index only as a CSS custom property.
// The dialog theme (`tvDialog`) references `var(--rui-z-index)` to set the actual
// `z-index`, so we cannot end up with an inline `z-index` that disagrees with
// the custom property.
const backdropStyle = computed(() => ({
  '--rui-z-index': depthOwner.backdropZIndex.value,
}))
const positionerStyle = computed(() => ({
  '--rui-z-index': depthOwner.contentZIndex.value,
}))
</script>

<template>
  <Teleport to="body">
    <DialogBackdrop
      v-bind="themeAttrs"
      :class="crafts.backdrop(cxc(ui?.backdrop))"
      :theme="theme"
      :style="backdropStyle"
    />
    <Dialog.Positioner
      v-bind="themeAttrs"
      :class="crafts.positioner(cxc(ui?.positioner))"
      :style="positionerStyle"
    >
      <Dialog.Content
        v-bind="{ ...attrs, ...themeAttrs }"
        :class="crafts.content(cxc(ui?.content, propsClass))"
      >
        <slot />
        <slot name="close">
          <DialogCloseTrigger
            v-if="showContentClose"
            as-child
          >
            <ark.button
              :class="cn(['absolute', 'top-0', 'right-0'], crafts.close(cxc(ui?.close)))"
              data-variant="content-close"
            >
              <X />
              <span class="sr-only">Close</span>
            </ark.button>
          </DialogCloseTrigger>
        </slot>
      </Dialog.Content>
    </Dialog.Positioner>
  </Teleport>
</template>
