// packages/react/core/src/components/tooltip/examples/disabled.tsx
import { Button } from '../../button'
import { Tooltip } from '../index'

export function TooltipDisabledExample() {
  return (
    <div className="w-full flex flex-wrap items-center gap-4">
      <Tooltip disabled>
        <Tooltip.Trigger asChild>
          <Button variant="outlined">Disabled tooltip</Button>
        </Tooltip.Trigger>
        <Tooltip.Content>
          <Tooltip.Arrow />
          This text should not be shown.
        </Tooltip.Content>
      </Tooltip>

      <Tooltip positioning={{ placement: 'top' }}>
        <Tooltip.Trigger asChild>
          <Button>Enabled tooltip</Button>
        </Tooltip.Trigger>
        <Tooltip.Content>
          <Tooltip.Arrow />
          Tooltip works normally.
        </Tooltip.Content>
      </Tooltip>
    </div>
  )
}

// packages/vue/core/src/components/tooltip/examples/disabled.vue
<script setup lang="ts">
import { Button } from '../../button'
import { Tooltip, TooltipArrow, TooltipContent, TooltipTrigger } from '../index'
</script>

<template>
  <div class="w-full flex flex-wrap items-center gap-4">
    <Tooltip :disabled="true">
      <TooltipTrigger as-child>
        <Button variant="outlined">
          Disabled tooltip
        </Button>
      </TooltipTrigger>
      <TooltipContent>
        <TooltipArrow />
        This text should not be shown.
      </TooltipContent>
    </Tooltip>

    <Tooltip :positioning="{ placement: 'top' }">
      <TooltipTrigger as-child>
        <Button>
          Enabled tooltip
        </Button>
      </TooltipTrigger>
      <TooltipContent>
        <TooltipArrow />
        Tooltip works normally.
      </TooltipContent>
    </Tooltip>
  </div>
</template>
