// packages/vue/core/src/providers/theme/ThemeProvider.vue
<script setup lang="ts" generic="T = ThemeProps">
import type { ThemeProps } from '.'
import { computed } from 'vue'
import { provideScopeTheme } from './theme-props'

const props = defineProps<{ value?: T }>()

// User-facing ThemeProvider: always provides Scope Theme so all descendant
// components receive the user's explicit intent (highest-priority scope).
provideScopeTheme(computed(() => props.value ?? {}))
</script>

<template>
  <slot />
</template>

// packages/react/core/src/providers/theme/ThemeProvider.tsx
import type { ReactNode } from 'react'
import type { ThemeProps } from './theme-props'
import { ScopeThemeContext } from './theme-props'

export interface ThemeProviderProps {
  value?: ThemeProps
  children?: ReactNode
}

/** User-facing ThemeProvider: always provides Scope Theme for descendants. */
export function ThemeProvider({ value, children }: ThemeProviderProps) {
  return (
    <ScopeThemeContext.Provider value={value ?? {}}>
      {children}
    </ScopeThemeContext.Provider>
  )
}
