// packages/vue/core/src/components/arrow/createArrow.tsx
import type { ThemeNoCrafts, ThemeProps } from '@raxium/vue/providers/theme'
import type { DefineComponent, HTMLAttributes, PropType } from 'vue'
import { cn } from '@raxium/themes/utils'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { useThemeAttrs } from '@raxium/vue/composables/useThemeAttrs'
import { computed, defineComponent } from 'vue'

export interface ArrowProps extends ThemeNoCrafts {
  class?: HTMLAttributes['class']
  ui?: {
    arrow?: HTMLAttributes['class']
    arrowTip?: HTMLAttributes['class']
  }
}

export function createArrow(
  ArrowNode: DefineComponent<any, any, any>,
  ArrowTipNode: DefineComponent<any, any, any>,
) {
  return defineComponent<ArrowProps>({
    name: ArrowNode.__name ?? 'Arrow',
    props: {
      class: {
        type: [String, Array, Object] as PropType<HTMLAttributes['class']>,
      },
      ui: {
        type: Object as PropType<{
          arrow?: HTMLAttributes['class']
          arrowTip?: HTMLAttributes['class']
        }>,
      },
      theme: {
        type: Object as PropType<ThemeProps>,
      },
    },
    setup(props: ArrowProps) {
      const theme = useInheritedTheme(() => props.theme)
      const themeAttrs = useThemeAttrs(theme)
      const arrowSize = computed(() => {
        switch (theme.value.size) {
          case 'xs':
            return '0.25rem'
          case 'sm':
            return '0.375rem'
          case 'base':
            return '0.5rem'
          case 'lg':
            return '0.625rem'
          default:
            return '0.5rem'
        }
      })
      return () => {
        return (
          <ArrowNode
            class={cn(props.ui?.arrow, props.class)}
            {...themeAttrs.value}
            style={{
              'overflow': 'visible',
              'zIndex': 0,
              '--arrow-size': arrowSize.value,
            }}
          >
            <ArrowTipNode
              class={cn(theme.value.bordered && 'border', props.ui?.arrowTip)}
              {...themeAttrs.value}
            />
          </ArrowNode>
        )
      }
    },
  })
}

// packages/react/core/src/components/arrow/createArrow.tsx
import type { ThemeNoCrafts, ThemeProps } from '@raxium/react/providers/theme'
import type { ComponentType, CSSProperties, HTMLAttributes } from 'react'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useThemeAttrs } from '@raxium/react/hooks/useThemeAttrs'
import { cn } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export interface ArrowProps extends ThemeNoCrafts {
  className?: HTMLAttributes<HTMLElement>['className']
  ui?: {
    arrow?: HTMLAttributes<HTMLElement>['className']
    arrowTip?: HTMLAttributes<HTMLElement>['className']
  }
}

function arrowSizeCss(size: ThemeProps['size']): string {
  switch (size) {
    case 'xs':
      return '0.25rem'
    case 'sm':
      return '0.375rem'
    case 'base':
      return '0.5rem'
    case 'lg':
      return '0.625rem'
    case undefined:
      return '0.5rem'
    default: {
      const _exhaustive: never = size
      return _exhaustive
    }
  }
}

export function createArrow(
  ArrowNode: ComponentType<any>,
  ArrowTipNode: ComponentType<any>,
) {
  const Arrow = forwardRef<HTMLDivElement, ArrowProps>(
    ({ className, ui, theme: propsTheme, ...props }, ref) => {
      const theme = useInheritedTheme(propsTheme)
      const themeAttrs = useThemeAttrs(theme)

      return (
        <ProvideStructuralComponentTheme theme={theme}>
          <ArrowNode
            ref={ref}
            className={cn(ui?.arrow, className)}
            {...themeAttrs}
            style={{
              overflow: 'visible',
              zIndex: 0,
              '--arrow-size': arrowSizeCss(theme.size),
            } as CSSProperties}
            {...props}
          >
            <ArrowTipNode
              className={cn(theme.bordered && 'border', ui?.arrowTip)}
              {...themeAttrs}
            />
          </ArrowNode>
        </ProvideStructuralComponentTheme>
      )
    },
  )

  Arrow.displayName = ArrowNode.displayName ?? 'Arrow'
  return Arrow
}
