// packages/vue/core/src/components/toggle/examples/controlled.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import { Toggle } from '../index'

const pressed = ref(false)
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="flex items-center gap-2">
      <Button variant="outlined" @click="pressed = false">
        Set off
      </Button>
      <Button variant="outlined" @click="pressed = true">
        Set on
      </Button>
      <span class="text-sm text-gray-ff">pressed: {{ pressed }}</span>
    </div>

    <Toggle v-model:pressed="pressed">
      Controlled toggle
    </Toggle>
  </div>
</template>

// packages/react/core/src/components/switch/examples/controlled.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Switch } from '../index'

export function SwitchControlledExample() {
  const [checked, setChecked] = useState(false)

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <Button variant="outlined" onClick={() => setChecked(false)}>Set false</Button>
        <Button variant="outlined" onClick={() => setChecked(true)}>Set true</Button>
        <span className="text-sm text-gray-ff">
          checked:
          {' '}
          {String(checked)}
        </span>
      </div>
      <Switch checked={checked} onCheckedChange={details => setChecked(details.checked)}>
        <Switch.Label>Controlled</Switch.Label>
      </Switch>
    </div>
  )
}
