// packages/vue/core/src/composables/useRipple.tsx
import type { ComputedRef, MaybeRef, Ref } from 'vue'
import { computed, ref, unref, watchEffect } from 'vue'

type MaybeRefOrComputedRef<T> = MaybeRef<T> | ComputedRef<T>
interface Options {
  enabled?: MaybeRefOrComputedRef<boolean | undefined>
  duration?: MaybeRefOrComputedRef<number | undefined>
  color?: MaybeRefOrComputedRef<string | undefined>
}

export function useRipple(
  referenceRef: Ref<Element | null> | ComputedRef<Element | null>,
  {
    duration = 600,
    color = '#44D62C',
    enabled = true,
  }: Options = {},
) {
  const ripples = ref<Array<{ x: number, y: number, size: number, key: number }>>([])
  const isRelativedReference = computed(() => {
    if (!referenceRef.value)
      return false
    return getComputedStyle(referenceRef.value).position !== 'static'
  })
  const onRipple = (event: MouseEvent) => {
    if (!referenceRef.value || !unref(enabled))
      return
    const reference = referenceRef.value!
    if (!isRelativedReference.value)
      reference.classList.add('relative')
    const rect = reference.getBoundingClientRect()
    const size = Math.max(rect.width, rect.height)
    const x = event.clientX - rect.left - size / 2
    const y = event.clientY - rect.top - size / 2

    const newRipple = { x, y, size, key: Date.now() }
    ripples.value.push(newRipple)
  }

  watchEffect((onCleanup) => {
    if (ripples.value.length > 0) {
      const lastRipple = ripples.value[ripples.value.length - 1]
      const timer = setTimeout(() => {
        ripples.value = ripples.value.filter(
          ripple => ripple.key !== lastRipple.key,
        )
      }, unref(duration))
      onCleanup(() => clearTimeout(timer))
    }
    else {
      if (!referenceRef.value)
        return
      const reference = referenceRef.value!
      if (!isRelativedReference.value)
        reference.classList.remove('relative')
    }
  })

  const Ripple = computed(() => {
    return (
      <span
        class="pointer-events-none absolute inset-0 overflow-hidden"
      >
        {ripples.value.map(ripple => (
          <span
            key={ripple.key}
            class="absolute rounded-full bg-transparent opacity-30 animate-rippling"
            style={{
              width: `${ripple.size}px`,
              height: `${ripple.size}px`,
              top: `${ripple.y}px`,
              left: `${ripple.x}px`,
              backgroundColor: unref(color),
              transform: 'scale(0)',
              animationDuration: `${unref(duration)}ms`,
            }}
          />
        ))}
      </span>
    )
  })

  return { Ripple, onRipple }
}

// packages/react/core/src/hooks/useRipple.tsx
import type { CSSProperties, RefObject } from 'react'
import { useCallback, useEffect, useRef, useState } from 'react'

interface RippleItem {
  x: number
  y: number
  size: number
  key: number
}

export interface UseRippleOptions {
  enabled?: boolean
  duration?: number
  color?: string | (() => string | undefined)
}

function resolveColor(color: UseRippleOptions['color'], fallback: string) {
  if (typeof color === 'function')
    return color() ?? fallback
  return color ?? fallback
}

export function useRipple(
  referenceRef: RefObject<Element | null>,
  {
    duration = 600,
    color = '#44D62C',
    enabled = true,
  }: UseRippleOptions = {},
) {
  const [ripples, setRipples] = useState<RippleItem[]>([])
  const addedRelativeRef = useRef(false)

  const onRipple = useCallback((event: Pick<MouseEvent, 'clientX' | 'clientY'>) => {
    const reference = referenceRef.current
    if (!reference || !enabled)
      return

    const position = getComputedStyle(reference).position
    if (position === 'static') {
      reference.classList.add('relative')
      addedRelativeRef.current = true
    }

    const rect = reference.getBoundingClientRect()
    const size = Math.max(rect.width, rect.height)
    const item: RippleItem = {
      x: event.clientX - rect.left - size / 2,
      y: event.clientY - rect.top - size / 2,
      size,
      key: Date.now(),
    }
    setRipples(prev => [...prev, item])
  }, [enabled, referenceRef])

  useEffect(() => {
    if (ripples.length === 0) {
      const reference = referenceRef.current
      if (reference && addedRelativeRef.current) {
        reference.classList.remove('relative')
        addedRelativeRef.current = false
      }
      return
    }

    const lastRipple = ripples[ripples.length - 1]
    const timer = window.setTimeout(() => {
      setRipples(prev => prev.filter(ripple => ripple.key !== lastRipple.key))
    }, duration)

    return () => window.clearTimeout(timer)
  }, [duration, referenceRef, ripples])

  const Ripple = useCallback(() => {
    const backgroundColor = resolveColor(color, '#44D62C')
    return (
      <span className="pointer-events-none absolute inset-0 overflow-hidden">
        {ripples.map(ripple => (
          <span
            key={ripple.key}
            className="absolute rounded-full bg-transparent opacity-30 animate-rippling"
            style={{
              width: `${ripple.size}px`,
              height: `${ripple.size}px`,
              top: `${ripple.y}px`,
              left: `${ripple.x}px`,
              backgroundColor,
              transform: 'scale(0)',
              animationDuration: `${duration}ms`,
            } as CSSProperties}
          />
        ))}
      </span>
    )
  }, [color, duration, ripples])

  return { Ripple, onRipple }
}
