// packages/react/core/src/components/pagination/examples/dynamic-end.tsx
import { useState } from 'react'
import { Pagination } from '../index'

export function PaginationDynamicEndExample() {
  const [page, setPage] = useState(1)

  return (
    <div className="w-full flex flex-col gap-2">
      <div className="text-sm text-gray-cc">
        page:
        {' '}
        <span className="text-gray-ff">{page}</span>
      </div>

      <div className="w-full max-w-[720px] rounded-md border border-gray-33 p-3">
        <Pagination
          page={page}
          count={10000}
          defaultPageSize={10}
          siblingCount={1}
          dynamicPageEnd={20}
          onPageChange={details => setPage(details.page)}
        >
          <Pagination.GoTo
            suffix={(
              <Pagination.GoToTrigger>
                <span className="text-sm text-rz-green hover:text-rz-green-light hover:underline">
                  GO
                </span>
              </Pagination.GoToTrigger>
            )}
          />
          <Pagination.PageSize
            prefix={<span className="text-sm text-gray-cc">每页</span>}
            suffix={<span className="text-sm text-gray-cc">条</span>}
          />
        </Pagination>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/pagination/examples/dynamic-end.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Pagination, PaginationGoTo, PaginationGoToTrigger, PaginationPageSize } from '../index'

const page = ref(1)
</script>

<template>
  <div class="w-full flex flex-col gap-2">
    <div class="text-sm text-gray-cc">
      page: <span class="text-gray-ff">{{ page }}</span>
    </div>

    <div class="w-full max-w-[720px] rounded-md border border-gray-33 p-3">
      <Pagination
        v-model:page="page"
        :count="10000"
        :default-page-size="10"
        :sibling-count="1"
        :dynamic-page-end="20"
      >
        <PaginationGoTo>
          <template #suffix>
            <PaginationGoToTrigger>
              <span class="text-sm text-rz-green hover:text-rz-green-light hover:underline">
                GO
              </span>
            </PaginationGoToTrigger>
          </template>
        </PaginationGoTo>
        <PaginationPageSize>
          <template #prefix>
            <span class="text-sm text-gray-cc">每页</span>
          </template>
          <template #suffix>
            <span class="text-sm text-gray-cc">条</span>
          </template>
        </PaginationPageSize>
      </Pagination>
    </div>
  </div>
</template>
