// packages/react/core/src/components/pagination/examples/link-type.tsx
import { useState } from 'react'
import { Pagination } from '../index'

export function PaginationLinkTypeExample() {
  const [page, setPage] = useState(3)

  return (
    <div className="w-full flex flex-col gap-2">
      <div className="text-sm text-gray-cc">
        type=link（仅演示 href 生成）
      </div>

      <div className="w-full max-w-[720px] rounded-md border border-gray-33 p-3">
        <Pagination
          page={page}
          type="link"
          count={120}
          defaultPageSize={10}
          getPageUrl={({ page: nextPage }) => `#page=${nextPage}`}
          onPageChange={details => setPage(details.page)}
        />
      </div>
    </div>
  )
}

// packages/vue/core/src/components/pagination/examples/link-type.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Pagination } from '../index'

const page = ref(3)
</script>

<template>
  <div class="w-full flex flex-col gap-2">
    <div class="text-sm text-gray-cc">
      type=link（仅演示 href 生成）
    </div>

    <div class="w-full max-w-[720px] rounded-md border border-gray-33 p-3">
      <Pagination
        v-model:page="page"
        type="link"
        :count="120"
        :default-page-size="10"
        :get-page-url="({ page }) => `#page=${page}`"
      />
    </div>
  </div>
</template>
