// packages/react/core/src/components/pagination/examples/minimal.tsx
import { useState } from 'react'
import { Pagination } from '../index'

export function PaginationMinimalExample() {
  const [page, setPage] = useState(1)

  return (
    <div className="w-full flex flex-col gap-2">
      <div className="text-sm text-gray-cc">
        page:
        {' '}
        <span className="text-gray-ff">{page}</span>
      </div>

      <div className="w-full max-w-[720px] rounded-md border border-gray-33 p-3">
        <Pagination
          page={page}
          count={80}
          defaultPageSize={10}
          siblingCount={1}
          onPageChange={details => setPage(details.page)}
        />
      </div>
    </div>
  )
}

// packages/vue/core/src/components/pagination/examples/minimal.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Pagination } from '../index'

const page = ref(1)
</script>

<template>
  <div class="w-full flex flex-col gap-2">
    <div class="text-sm text-gray-cc">
      page: <span class="text-gray-ff">{{ page }}</span>
    </div>

    <div class="w-full max-w-[720px] rounded-md border border-gray-33 p-3">
      <Pagination v-model:page="page" :count="80" :default-page-size="10" :sibling-count="1" />
    </div>
  </div>
</template>
