// packages/vue/core/src/components/progress/examples/custom-ui.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Progress, ProgressLinear } from '../index'

const value = ref(35)
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <Progress
      class="w-80"
      :model-value="value"
    >
      <ProgressLinear
        :ui="{
          track: 'bg-gray-22 border border-gray-55',
          range: 'bg-rz-green',
        }"
      />
    </Progress>

    <Progress
      class="w-80"
      :model-value="value"
    >
      <ProgressLinear
        variant="transfer"
        :ui="{
          track: 'bg-gray-22 border border-gray-55',
          range: 'bg-rz-green',
        }"
      />
    </Progress>
  </div>
</template>

// packages/react/core/src/components/progress/examples/custom-ui.tsx
import { useState } from 'react'
import { Progress } from '../index'

export function ProgressCustomUiExample() {
  const [value] = useState(35)

  return (
    <div className="w-full flex flex-col gap-4">
      <Progress className="w-80" value={value}>
        <Progress.Linear
          ui={{
            track: 'bg-gray-22 border border-gray-55',
            range: 'bg-rz-green',
          }}
        />
      </Progress>

      <Progress className="w-80" value={value}>
        <Progress.Linear
          variant="transfer"
          ui={{
            track: 'bg-gray-22 border border-gray-55',
            range: 'bg-rz-green',
          }}
        />
      </Progress>
    </div>
  )
}
