// packages/vue/core/src/components/floating-panel/examples/minimal.vue
<script setup lang="ts">
import { Button } from '../../button'
import {
  FloatingPanel,
  FloatingPanelCloseTrigger,
  FloatingPanelContent,
  FloatingPanelHeader,
  FloatingPanelTrigger,
} from '../index'
</script>

<template>
  <FloatingPanel :min-size="{ width: 360, height: 240 }">
    <FloatingPanelTrigger as-child>
      <Button class="w-fit">
        Open FloatingPanel
      </Button>
    </FloatingPanelTrigger>

    <FloatingPanelContent>
      <FloatingPanelHeader>
        FloatingPanel
        <template #control>
          <FloatingPanelCloseTrigger />
        </template>
      </FloatingPanelHeader>

      <div class="p-3">
        Minimal content.
      </div>
    </FloatingPanelContent>
  </FloatingPanel>
</template>

// packages/react/core/src/components/floating-panel/examples/minimal.tsx
import { Button } from '../../button'
import { FloatingPanel } from '../index'

export function FloatingPanelMinimalExample() {
  return (
    <FloatingPanel minSize={{ width: 360, height: 240 }}>
      <FloatingPanel.Trigger asChild>
        <Button className="w-fit">Open FloatingPanel</Button>
      </FloatingPanel.Trigger>
      <FloatingPanel.Content>
        <FloatingPanel.Header control={<FloatingPanel.CloseTrigger />}>
          FloatingPanel
        </FloatingPanel.Header>
        <div className="p-3">Minimal content.</div>
      </FloatingPanel.Content>
    </FloatingPanel>
  )
}
