// packages/vue/core/src/components/floating-panel/examples/multiple.vue
<script setup lang="ts">
import { Button } from '../../button'
import {
  FloatingPanel,
  FloatingPanelCloseTrigger,
  FloatingPanelContent,
  FloatingPanelHeader,
  FloatingPanelTrigger,
} from '../index'
</script>

<template>
  <div class="flex flex-wrap gap-3">
    <FloatingPanel :min-size="{ width: 320, height: 220 }">
      <FloatingPanelTrigger as-child>
        <Button class="w-fit">
          Open Panel A
        </Button>
      </FloatingPanelTrigger>
      <FloatingPanelContent>
        <FloatingPanelHeader>
          Panel A
          <template #control>
            <FloatingPanelCloseTrigger />
          </template>
        </FloatingPanelHeader>
        <div class="p-3">
          Click any panel to bring it to the front.
        </div>
      </FloatingPanelContent>
    </FloatingPanel>

    <FloatingPanel :min-size="{ width: 320, height: 220 }">
      <FloatingPanelTrigger as-child>
        <Button class="w-fit">
          Open Panel B
        </Button>
      </FloatingPanelTrigger>
      <FloatingPanelContent>
        <FloatingPanelHeader>
          Panel B
          <template #control>
            <FloatingPanelCloseTrigger />
          </template>
        </FloatingPanelHeader>
        <div class="p-3">
          Focus this panel to promote its z-index.
        </div>
      </FloatingPanelContent>
    </FloatingPanel>

    <FloatingPanel :min-size="{ width: 320, height: 220 }">
      <FloatingPanelTrigger as-child>
        <Button class="w-fit">
          Open Panel C
        </Button>
      </FloatingPanelTrigger>
      <FloatingPanelContent>
        <FloatingPanelHeader>
          Panel C
          <template #control>
            <FloatingPanelCloseTrigger />
          </template>
        </FloatingPanelHeader>
        <div class="p-3">
          Last focused panel wins.
        </div>
      </FloatingPanelContent>
    </FloatingPanel>
  </div>
</template>

// packages/react/core/src/components/floating-panel/examples/multiple.tsx
import { Button } from '../../button'
import { FloatingPanel } from '../index'

const panels = [
  { id: 'a', title: 'Panel A', body: 'Click any panel to bring it to the front.' },
  { id: 'b', title: 'Panel B', body: 'Focus this panel to promote its z-index.' },
  { id: 'c', title: 'Panel C', body: 'Last focused panel wins.' },
] as const

export function FloatingPanelMultipleExample() {
  return (
    <div className="flex flex-wrap gap-3">
      {panels.map(panel => (
        <FloatingPanel key={panel.id} minSize={{ width: 320, height: 220 }}>
          <FloatingPanel.Trigger asChild>
            <Button className="w-fit">
              Open
              {' '}
              {panel.title}
            </Button>
          </FloatingPanel.Trigger>
          <FloatingPanel.Content>
            <FloatingPanel.Header control={<FloatingPanel.CloseTrigger />}>
              {panel.title}
            </FloatingPanel.Header>
            <div className="p-3">{panel.body}</div>
          </FloatingPanel.Content>
        </FloatingPanel>
      ))}
    </div>
  )
}
