// packages/react/core/src/components/select/examples/multiple-and-clearable.tsx
import { useState } from 'react'
import { createListCollection, Select } from '../index'

const items = [
  { label: 'Apple', value: 'fruit-0' },
  { label: 'Banana', value: 'fruit-1' },
  { label: 'Cherry', value: 'fruit-2' },
  { label: 'Mango', value: 'fruit-3' },
  { label: 'Orange', value: 'fruit-4' },
  { label: 'Peach', value: 'fruit-5' },
  { label: 'Pear', value: 'fruit-6' },
  { label: 'Plum', value: 'fruit-7' },
]

const collection = createListCollection({ items })

export function SelectMultipleAndClearableExample() {
  const [value, setValue] = useState<string[]>([])

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="text-sm text-gray-ff">
        value:
        {' '}
        {JSON.stringify(value)}
      </div>

      <Select
        collection={collection}
        multiple
        value={value}
        onValueChange={details => setValue(details.value)}
      >
        <Select.Trigger className="w-80" clearable>
          <Select.Value placeholder="Select fruits (multiple)" />
        </Select.Trigger>
        <Select.Content>
          {items.map(item => (
            <Select.Item key={item.value} item={item}>
              {item.label}
            </Select.Item>
          ))}
        </Select.Content>
      </Select>
    </div>
  )
}

// packages/vue/core/src/components/select/examples/multiple-and-clearable.vue
<script setup lang="ts">
import { createListCollection } from '@ark-ui/vue/select'
import { fakerEN } from '@faker-js/faker'
import { ref } from 'vue'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../index'

const collection = createListCollection({
  items: Array.from({ length: 8 }, (_, index) => ({
    label: fakerEN.food.fruit(),
    value: `fruit-${index}`,
  })),
})
const modelValue = ref<string[]>([])
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="text-sm text-gray-ff">
      modelValue: {{ modelValue }}
    </div>

    <Select v-model="modelValue" :collection="collection" multiple>
      <SelectTrigger class="w-80" clearable>
        <SelectValue placeholder="Select fruits (multiple)" />
      </SelectTrigger>
      <SelectContent>
        <SelectItem
          v-for="item in collection.items"
          :key="item.value"
          :item="item"
        >
          {{ item.label }}
        </SelectItem>
      </SelectContent>
    </Select>
  </div>
</template>
