// packages/vue/core/src/components/scroll-area/ScrollAreaCorner.vue
<script setup lang="ts">
import type { ScrollAreaCornerProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { ScrollArea } from '@ark-ui/vue/scroll-area'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  ...props
} = defineProps<ScrollAreaCornerProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvScrollArea', undefined, () => propsTheme?.craft)
</script>

<template>
  <ScrollArea.Corner v-bind="forwarded" :class="crafts.corner(cxc(propsClass))" />
</template>

// packages/react/core/src/components/scroll-area/ScrollAreaCorner.tsx
import type { ScrollAreaCornerProps } from './props'
import { ScrollArea as ArkScrollArea } from '@ark-ui/react/scroll-area'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const ScrollAreaCorner = forwardRef<HTMLDivElement, ScrollAreaCornerProps>(
  ({ className, theme: propsTheme, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvScrollArea')

    return (
      <ArkScrollArea.Corner
        ref={ref}
        className={crafts.corner(cxc(className))}
        {...props}
      />
    )
  },
)

ScrollAreaCorner.displayName = 'ScrollArea.Corner'
