// packages/react/core/src/components/scroll-area/ScrollAreaScrollbar.tsx
import type { ScrollAreaScrollbarProps } from './props'
import { ScrollArea as ArkScrollArea } from '@ark-ui/react/scroll-area'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useMemo } from 'react'
import { useScrollAreaOverflow } from './overflow-context'

export const ScrollAreaScrollbar = forwardRef<HTMLDivElement, ScrollAreaScrollbarProps>(
  ({ className, theme: propsTheme, ui, orientation = 'vertical', ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const variants = useMemo(() => ({ orientation }), [orientation])
    const crafts = useCraft(theme, 'tvScrollArea', variants)
    const overflow = useScrollAreaOverflow()

    let visible: boolean
    switch (orientation) {
      case 'horizontal':
        visible = overflow.horizontal
        break
      case 'vertical':
        visible = overflow.vertical
        break
      default: {
        const _exhaustive: never = orientation
        return _exhaustive
      }
    }

    if (!visible)
      return null

    return (
      <ArkScrollArea.Scrollbar
        ref={ref}
        orientation={orientation}
        className={crafts.scrollbar(cxc(ui?.root, className))}
        {...props}
      >
        <ArkScrollArea.Thumb className={crafts.thumb(cxc(ui?.thumb))} />
      </ArkScrollArea.Scrollbar>
    )
  },
)

ScrollAreaScrollbar.displayName = 'ScrollArea.Scrollbar'

// packages/vue/core/src/components/scroll-area/ScrollAreaScrollbar.vue
<script setup lang="ts">
import type { ScrollAreaScrollbarProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { ScrollArea } from '@ark-ui/vue/scroll-area'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  ui,
  ...props
} = defineProps<ScrollAreaScrollbarProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvScrollArea', () => ({
  orientation: forwarded.value.orientation ?? 'vertical',
}), () => propsTheme?.craft)
</script>

<template>
  <ScrollArea.Scrollbar
    v-bind="forwarded"
    :class="
      crafts.scrollbar(cxc(ui?.root, propsClass))
    "
  >
    <ScrollArea.Thumb
      :class="
        crafts.thumb(cxc(ui?.thumb))
      "
    />
  </ScrollArea.Scrollbar>
</template>
