// packages/react/core/src/components/scroll-area/ScrollArea.tsx
import type { ScrollAreaOverflow } from './overflow-context'
import type { ScrollAreaProps } from './props'
import { ScrollArea as ArkScrollArea } from '@ark-ui/react/scroll-area'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useMemo, useState } from 'react'
import { ScrollAreaOverflowContext } from './overflow-context'

export const ScrollAreaRoot = forwardRef<HTMLDivElement, ScrollAreaProps>(
  ({ className, theme: propsTheme, craft, ui, children, ...props }, ref) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvScrollArea', craft)
    const crafts = useCraft(themed, 'tvScrollArea')
    const [overflow, setOverflow] = useState<ScrollAreaOverflow>({
      vertical: false,
      horizontal: false,
    })
    const overflowValue = useMemo(() => ({ overflow, setOverflow }), [overflow])

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ScrollAreaOverflowContext.Provider value={overflowValue}>
          <ArkScrollArea.Root
            ref={ref}
            className={crafts.root(cxc(ui?.root, className))}
            {...props}
          >
            {children}
          </ArkScrollArea.Root>
        </ScrollAreaOverflowContext.Provider>
      </ProvideComponentTheme>
    )
  },
)

ScrollAreaRoot.displayName = 'ScrollArea'

// packages/vue/core/src/components/scroll-area/ScrollArea.vue
<script setup lang="ts">
import type { ScrollAreaEmits, ScrollAreaProps, ScrollAreaTheme } from '.'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { ScrollArea, useScrollArea } from '@ark-ui/vue/scroll-area'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { excludeVNodesByNames, findVNodesByName } from '@raxium/vue/utils/vnode'
import { useElementSize } from '@vueuse/core'
import { computed, useSlots, useTemplateRef } from 'vue'

const { class: propsClass, theme: propsTheme, ui, ...props } = defineProps<ScrollAreaProps>()
const emits = defineEmits<ScrollAreaEmits>()
const scrollArea = useScrollArea(useForwardProps(props))

const slots = useSlots()
const defaultSlots = computed(() => slots.default?.())
const scrollbarNodes = computed(() => findVNodesByName(defaultSlots.value, 'ScrollAreaScrollbar'))
const cornerNodes = computed(() => findVNodesByName(defaultSlots.value, 'ScrollAreaCorner'))
const otherNodes = computed(() =>
  excludeVNodesByNames(defaultSlots.value, ['ScrollAreaScrollbar', 'ScrollAreaCorner']),
)

const viewportRef = useTemplateRef('viewport')
const contentRef = useTemplateRef('content')

const { width: viewportWidth, height: viewportHeight } = useElementSize(
  () => viewportRef.value?.$el,
)
const { width: contentWidth, height: contentHeight } = useElementSize(() => contentRef.value?.$el)
const isShowScrollbars = computed(() => ({
  vertical: viewportHeight.value < contentHeight.value,
  horizontal: viewportWidth.value < contentWidth.value,
}))

// theme
const theme = useTheme<ScrollAreaTheme>(() => propsTheme)
const themed = useThemeCraft(theme, 'tvScrollArea', () => propsTheme?.craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvScrollArea')

// expose
defineExpose({ $api: scrollArea })
useForwardExpose()
</script>

<template>
  <ScrollArea.RootProvider
    :value="scrollArea"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <ScrollArea.Viewport
      ref="viewport"
      :class="crafts.viewport(cxc(ui?.viewport))"
      @scrollstart="emits('scrollstart', $event)"
      @scrollend="emits('scrollend', $event)"
      @scroll="emits('scroll', $event)"
    >
      <ScrollArea.Content
        ref="content"
        :class="crafts.content(cxc(ui?.content))"
      >
        <component
          :is="node"
          v-for="node in otherNodes"
          :key="node.key"
        />
      </ScrollArea.Content>
    </ScrollArea.Viewport>
    <template
      v-for="(node, index) in scrollbarNodes"
      :key="node.key ?? index"
    >
      <component
        :is="node"
        v-if="
          isShowScrollbars.vertical
            && (node.props?.orientation === 'vertical' || !node.props?.orientation)
        "
      />
      <component
        :is="node"
        v-if="isShowScrollbars.horizontal && node.props?.orientation === 'horizontal'"
        :data-test="node.props?.orientation"
      />
    </template>
    <component
      :is="node"
      v-for="node in cornerNodes"
      :key="node.key"
    />
  </ScrollArea.RootProvider>
</template>
