// packages/vue/core/src/components/hover-card/examples/controlled-and-context.vue
<script setup lang="ts">
import { HoverCardContext } from '@ark-ui/vue/hover-card'
import { ref } from 'vue'
import { Button } from '../../button'
import {
  HoverCard,
  HoverCardArrow,
  HoverCardContent,
  HoverCardTrigger,
} from '../index'

const open = ref(false)
</script>

<template>
  <div class="w-full flex items-center gap-6">
    <Button @click="open = !open">
      Toggle open: {{ open }}
    </Button>

    <HoverCard
      v-model:open="open"
      :positioning="{ placement: 'top' }"
    >
      <HoverCardTrigger as-child>
        <Button variant="outlined">
          Controlled hover-card
        </Button>
      </HoverCardTrigger>

      <HoverCardContent>
        <HoverCardArrow />
        <HoverCardContext v-slot="ctx">
          <div class="flex flex-col gap-1">
            <div class="text-sm">
              open: {{ ctx.open }}
            </div>
            <div class="text-xs opacity-75">
              Use HoverCardContext to access the API.
            </div>
          </div>
        </HoverCardContext>
      </HoverCardContent>
    </HoverCard>
  </div>
</template>

// packages/react/core/src/components/hover-card/examples/controlled-and-context.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { HoverCard, useHoverCardContext } from '../index'

function HoverCardStatus() {
  const { open } = useHoverCardContext()
  return (
    <div className="flex flex-col gap-1">
      <div className="text-sm">
        open:
        {' '}
        {String(open)}
      </div>
      <div className="text-xs opacity-75">Use useHoverCardContext to access the API.</div>
    </div>
  )
}

export function HoverCardControlledAndContextExample() {
  const [open, setOpen] = useState(false)

  return (
    <div className="w-full flex items-center gap-6">
      <Button onClick={() => setOpen(current => !current)}>
        Toggle open:
        {' '}
        {String(open)}
      </Button>
      <HoverCard
        open={open}
        positioning={{ placement: 'top' }}
        onOpenChange={details => setOpen(details.open)}
      >
        <HoverCard.Trigger asChild>
          <Button variant="outlined">Controlled hover-card</Button>
        </HoverCard.Trigger>
        <HoverCard.Content>
          <HoverCard.Arrow />
          <HoverCardStatus />
        </HoverCard.Content>
      </HoverCard>
    </div>
  )
}
