// packages/vue/core/src/components/hover-card/examples/delays-and-positioning.vue
<script setup lang="ts">
import { Button } from '../../button'
import { HoverCard, HoverCardArrow, HoverCardContent, HoverCardTrigger } from '../index'
</script>

<template>
  <div class="w-full flex flex-wrap items-center gap-6">
    <HoverCard :open-delay="0" :close-delay="0" :positioning="{ placement: 'top' }">
      <HoverCardTrigger as-child>
        <Button variant="outlined">
          No delay (top)
        </Button>
      </HoverCardTrigger>
      <HoverCardContent>
        <HoverCardArrow />
        openDelay=0 closeDelay=0
      </HoverCardContent>
    </HoverCard>

    <HoverCard :open-delay="800" :close-delay="300" :positioning="{ placement: 'bottom-start' }">
      <HoverCardTrigger as-child>
        <Button variant="outlined">
          Delayed (bottom-start)
        </Button>
      </HoverCardTrigger>
      <HoverCardContent>
        <HoverCardArrow />
        openDelay=800 closeDelay=300
      </HoverCardContent>
    </HoverCard>

    <HoverCard :positioning="{ placement: 'right' }" unmount-on-exit lazy-mount>
      <HoverCardTrigger as-child>
        <Button variant="outlined">
          Lazy mount + unmount
        </Button>
      </HoverCardTrigger>
      <HoverCardContent>
        <HoverCardArrow />
        mounted only when opened
      </HoverCardContent>
    </HoverCard>
  </div>
</template>

// packages/react/core/src/components/hover-card/examples/delays-and-positioning.tsx
import { Button } from '../../button'
import { HoverCard } from '../index'

export function HoverCardDelaysAndPositioningExample() {
  return (
    <div className="w-full flex flex-wrap items-center gap-6">
      <HoverCard openDelay={0} closeDelay={0} positioning={{ placement: 'top' }}>
        <HoverCard.Trigger asChild>
          <Button variant="outlined">No delay (top)</Button>
        </HoverCard.Trigger>
        <HoverCard.Content>
          <HoverCard.Arrow />
          openDelay=0 closeDelay=0
        </HoverCard.Content>
      </HoverCard>

      <HoverCard openDelay={800} closeDelay={300} positioning={{ placement: 'bottom-start' }}>
        <HoverCard.Trigger asChild>
          <Button variant="outlined">Delayed (bottom-start)</Button>
        </HoverCard.Trigger>
        <HoverCard.Content>
          <HoverCard.Arrow />
          openDelay=800 closeDelay=300
        </HoverCard.Content>
      </HoverCard>

      <HoverCard positioning={{ placement: 'right' }} unmountOnExit lazyMount>
        <HoverCard.Trigger asChild>
          <Button variant="outlined">Lazy mount + unmount</Button>
        </HoverCard.Trigger>
        <HoverCard.Content>
          <HoverCard.Arrow />
          mounted only when opened
        </HoverCard.Content>
      </HoverCard>
    </div>
  )
}
