// packages/react/core/src/components/progress/Progress.tsx
import type { ProgressProps } from './props'
import { Progress as ArkProgress } from '@ark-ui/react/progress'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const ProgressRoot = forwardRef<HTMLDivElement, ProgressProps>(
  ({ className, theme: propsTheme, craft, orientation = 'horizontal', children, ...props }, ref) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvProgress', craft)
    const crafts = useCraft(themed, 'tvProgress', { orientation })

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkProgress.Root
          ref={ref}
          className={crafts.root(cxc(className))}
          orientation={orientation}
          {...props}
        >
          {children}
        </ArkProgress.Root>
      </ProvideComponentTheme>
    )
  },
)

ProgressRoot.displayName = 'Progress'

// packages/vue/core/src/components/progress/Progress.vue
<script setup lang="ts">
import type { ProgressRootEmits } from '@ark-ui/vue/progress'
import type { ProgressProps } from '.'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { Progress, useProgress } from '@ark-ui/vue/progress'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'

const { class: propsClass, theme: propsTheme, craft, ...props } = defineProps<ProgressProps>()
const emit = defineEmits<ProgressRootEmits>()
const forwarded = useForwardProps(props)
const progress = useProgress(forwarded, emit)

// theme
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvProgress', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvProgress', () => ({
  orientation: forwarded.value.orientation ?? 'horizontal',
}))

// expose
defineExpose({ $api: progress })
useForwardExpose()
</script>

<template>
  <Progress.RootProvider
    :value="progress"
    :class="crafts.root(cxc(propsClass))"
  >
    <slot />
  </Progress.RootProvider>
</template>
