// packages/react/core/src/components/progress/ProgressCircle.tsx
import type { CSSProperties } from 'react'
import type { ProgressCircleProps } from './props'
import { Progress as ArkProgress } from '@ark-ui/react/progress'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useRef } from 'react'
import { useRangeTransfer } from './useRangeTransfer'

export const ProgressCircle = forwardRef<SVGSVGElement, ProgressCircleProps>(
  ({ className, theme: propsTheme, variant = 'default', ui, ...props }, ref) => {
    const rangeRef = useRef<SVGCircleElement>(null)
    const transferStyles = useRangeTransfer(rangeRef, variant, 'stroke')
    const theme = useInheritedTheme(
      propsTheme
        ? { ...propsTheme, size: typeof propsTheme.size === 'number' ? undefined : propsTheme.size }
        : undefined,
    )
    const size = propsTheme?.size ?? theme.size
    const crafts = useCraft(theme, 'tvProgress', {
      size: typeof size === 'string' ? size : 'base',
    })

    return (
      <ArkProgress.Circle
        ref={ref}
        className={crafts.circle(cxc(ui?.circle, className))}
        data-variant={variant}
        style={typeof size === 'number' ? { '--size': `${size}px` } as CSSProperties : undefined}
        {...props}
      >
        <ArkProgress.CircleTrack
          className={crafts.circleTrack(cxc(ui?.circleTrack))}
          data-variant={variant}
        />
        <ArkProgress.CircleRange
          ref={rangeRef}
          className={crafts.circleRange(cxc(ui?.circleRange))}
          data-variant={variant}
          style={transferStyles}
        />
      </ArkProgress.Circle>
    )
  },
)

ProgressCircle.displayName = 'Progress.Circle'

// packages/vue/core/src/components/progress/ProgressCircle.vue
<script setup lang="ts">
import type { ProgressCircleProps } from '.'
import type { ThemeProps } from '@raxium/vue/providers/theme'
import { useForwardProps } from '@ark-ui/vue'
import { Progress } from '@ark-ui/vue/progress'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { computed, useTemplateRef } from 'vue'
import { useRangeTransfer } from './useRangeTransfer'

const {
  class: propsClass,
  theme: propsTheme,
  variant = 'default',
  ui,
  ...props
} = defineProps<ProgressCircleProps>()
const forwarded = useForwardProps(props)

const rangeRef = useTemplateRef<{ $el: HTMLDivElement }>('range')
const { styles: transferStyles } = useRangeTransfer(
  rangeRef,
  computed(() => variant),
  'stroke',
)

// theme
const theme = useInheritedTheme(() => propsTheme as Partial<ThemeProps> | undefined)
const crafts = useCraft(theme, 'tvProgress', () => ({
  size: typeof theme.value.size === 'string' ? theme.value.size : 'base',
}))
</script>

<template>
  <Progress.Circle
    v-bind="forwarded"
    :class="crafts.circle(cxc(ui?.circle, propsClass))"
    :data-variant="variant"
    :style="typeof theme.size === 'number' && { '--size': `${theme.size}px` }"
  >
    <Progress.CircleTrack
      :class="crafts.circleTrack(cxc(ui?.circleTrack))"
      :data-variant="variant"
    />
    <Progress.CircleRange
      ref="range"
      :class="crafts.circleRange(cxc(ui?.circleRange))"
      :data-variant="variant"
      :style="transferStyles"
    />
  </Progress.Circle>
</template>
