// packages/react/core/src/components/progress/ProgressLinear.tsx
import type { ProgressLinearProps } from './props'
import { Progress as ArkProgress, useProgressContext } from '@ark-ui/react/progress'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useRef } from 'react'
import { useRangeTransfer } from './useRangeTransfer'

export const ProgressLinear = forwardRef<HTMLDivElement, ProgressLinearProps>(
  ({ className, theme: propsTheme, variant = 'default', ui, ...props }, ref) => {
    const context = useProgressContext()
    const rangeRef = useRef<HTMLDivElement>(null)
    const transferStyles = useRangeTransfer(rangeRef, variant, 'background')
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvProgress', {
      orientation: (context.getTrackProps() as { 'data-orientation'?: string })['data-orientation'] ?? 'horizontal',
      variant,
    })

    return (
      <ArkProgress.Track
        ref={ref}
        className={crafts.track(cxc(ui?.track, className))}
        data-variant={variant}
        {...props}
      >
        <ArkProgress.Range
          ref={rangeRef}
          className={crafts.range(cxc(ui?.range))}
          data-variant={variant}
          style={transferStyles}
        />
      </ArkProgress.Track>
    )
  },
)

ProgressLinear.displayName = 'Progress.Linear'

// packages/vue/core/src/components/progress/ProgressLinear.vue
<script setup lang="ts">
import type { ProgressLinearProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Progress, useProgressContext } from '@ark-ui/vue/progress'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'
import { computed, useTemplateRef } from 'vue'
import { useRangeTransfer } from './useRangeTransfer'

const {
  class: propsClass,
  theme: propsTheme,
  variant = 'default',
  ui,
  ...props
} = defineProps<ProgressLinearProps>()
const forwarded = useForwardProps(props)
const context = useProgressContext()
const itemProps = computed<any>(() => context.value.getTrackProps())

const rangeRef = useTemplateRef<{ $el: HTMLDivElement }>('range')
const { styles: transferStyles } = useRangeTransfer(
  rangeRef,
  computed(() => variant),
  'background',
)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvProgress', () => ({
  orientation: itemProps.value['data-orientation'] ?? 'horizontal',
  variant,
}))
</script>

<template>
  <Progress.Track
    v-bind="forwarded"
    :class="
      crafts.track(cxc(ui?.track, propsClass))
    "
    :data-variant="variant"
  >
    <Progress.Range
      ref="range"
      :class="
        crafts.range(cxc(ui?.range))
      "
      :data-variant="variant"
      :style="transferStyles"
    />
  </Progress.Track>
</template>
