// packages/vue/core/src/components/select/examples/groups-and-disabled.vue
<script setup lang="ts">
import { createListCollection } from '@ark-ui/vue/select'
import { fakerEN } from '@faker-js/faker'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectItemGroup,
  SelectTrigger,
  SelectValue,
} from '../index'

const groupCollection = createListCollection({
  items: Array.from({ length: 5 }, (_, index) => ({
    label: fakerEN.animal.cat(),
    value: `cat-${index}`,
    type: 'cat',
    disabled: index === 0,
  })).concat(
    Array.from({ length: 5 }, (_, index) => ({
      label: fakerEN.animal.bird(),
      value: `bird-${index}`,
      type: 'bird',
      disabled: index === 0,
    })),
  ),
  groupBy: item => item.type,
})
</script>

<template>
  <Select :collection="groupCollection">
    <SelectTrigger class="w-70">
      <SelectValue placeholder="Select an animal" />
    </SelectTrigger>
    <SelectContent>
      <SelectItemGroup
        v-for="[type, group] in groupCollection.group()"
        :key="type"
        :label="type === 'cat' ? 'Cats' : 'Birds'"
      >
        <SelectItem v-for="(item, index) in group" :key="item.value" :item="item">
          {{ item.label }} <span v-if="index === 0" class="opacity-60">(disabled)</span>
        </SelectItem>
      </SelectItemGroup>
    </SelectContent>
  </Select>
</template>

// packages/react/core/src/components/select/examples/groups-and-disabled.tsx
import { createListCollection, Select } from '../index'

const groups = [
  {
    type: 'cat',
    label: 'Cats',
    items: [
      { label: 'Bengal', value: 'cat-0', type: 'cat', disabled: true },
      { label: 'Calico', value: 'cat-1', type: 'cat', disabled: false },
      { label: 'Maine Coon', value: 'cat-2', type: 'cat', disabled: false },
      { label: 'Siamese', value: 'cat-3', type: 'cat', disabled: false },
      { label: 'Tabby', value: 'cat-4', type: 'cat', disabled: false },
    ],
  },
  {
    type: 'bird',
    label: 'Birds',
    items: [
      { label: 'Canary', value: 'bird-0', type: 'bird', disabled: true },
      { label: 'Finch', value: 'bird-1', type: 'bird', disabled: false },
      { label: 'Parrot', value: 'bird-2', type: 'bird', disabled: false },
      { label: 'Sparrow', value: 'bird-3', type: 'bird', disabled: false },
      { label: 'Wren', value: 'bird-4', type: 'bird', disabled: false },
    ],
  },
] as const

const collection = createListCollection({
  items: groups.flatMap(group => [...group.items]),
  groupBy: item => item.type,
})

export function SelectGroupsAndDisabledExample() {
  return (
    <Select collection={collection}>
      <Select.Trigger className="w-70">
        <Select.Value placeholder="Select an animal" />
      </Select.Trigger>
      <Select.Content>
        {groups.map(group => (
          <Select.ItemGroup key={group.type} label={group.label}>
            {group.items.map((item, index) => (
              <Select.Item key={item.value} item={item}>
                {item.label}
                {index === 0 ? <span className="opacity-60"> (disabled)</span> : null}
              </Select.Item>
            ))}
          </Select.ItemGroup>
        ))}
      </Select.Content>
    </Select>
  )
}
