// packages/vue/core/src/components/editable/Editable.vue
<script setup lang="ts">
import type { EditableRootEmits, UseEditableProps } from '@ark-ui/vue/editable'
import type { EditableProps } from '.'
import { EditableArea, EditableRootProvider, useEditable } from '@ark-ui/vue/editable'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue/utils'
import { findUp } from '@raxium/shared/dom'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { useTheme } from '@raxium/vue/composables/useTheme'
import { computed } from 'vue'

type SlotProps = {
  editing: boolean
  empty: boolean
  value: string
}

const {
  class: propsClass,
  theme: propsTheme,
  clearable,
  ui,
  craft,
  ...props
} = defineProps<EditableProps>()
const emits = defineEmits<Omit<EditableRootEmits, 'onInteractOutside'>>()
defineSlots<{
  prefix: (props: SlotProps) => any
  suffix: (props: SlotProps) => any
  default: (props: SlotProps) => any
}>()

// useForwardProps 收窄传递的props
const forwarded = useForwardProps<EditableProps, UseEditableProps>(props)
const editable = useEditable(
  computed(() => {
    return {
      ...forwarded.value,
      onInteractOutside: (event) => {
        // event.detail.target could be element triggered the event
        const target = event.detail.target as HTMLElement
        const exceptParts = ['input-area', 'clear-button']
        if (
          findUp(target, (node) => {
            return (
              node.dataset.scope === 'editable' && exceptParts.includes(node.dataset.part ?? '')
            )
          })
        ) {
          event.preventDefault()
          forwarded.value.onInteractOutside?.(event)
        }
      },
    }
  }),
  emits,
)
const slotProps = computed<SlotProps>(() => {
  return {
    editing: editable.value.editing,
    empty: editable.value.empty,
    value: editable.value.value,
  }
})

// theme
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvEditable', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvEditable')

// expose
defineExpose({ $api: editable })
useForwardExpose()
</script>

<template>
  <EditableRootProvider
    :value="editable"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <slot
      name="prefix"
      v-bind="slotProps"
    />
    <EditableArea :class="crafts.area(cxc(ui?.area, propsClass))">
      <slot v-bind="slotProps" />
    </EditableArea>
    <slot
      name="suffix"
      v-bind="slotProps"
    />
  </EditableRootProvider>
</template>

// packages/react/core/src/components/editable/Editable.tsx
import type { EditableInteractOutsideEvent } from '@ark-ui/react/editable'
import type { EditableProps } from './props'
import { Editable as ArkEditable } from '@ark-ui/react/editable'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { findUp } from '@raxium/shared/dom'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

const exceptParts = ['input-area', 'clear-button']

function interactTarget(event: EditableInteractOutsideEvent): HTMLElement | undefined {
  const detail = event.detail as { originalEvent?: Event, target?: EventTarget }
  const raw = detail?.originalEvent?.target ?? detail?.target
  return raw instanceof HTMLElement ? raw : undefined
}

export const EditableRoot = forwardRef<HTMLDivElement, EditableProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      prefix,
      suffix,
      ui,
      children,
      onInteractOutside,
      ...props
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvEditable', craft)
    const crafts = useCraft(themed, 'tvEditable')

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkEditable.Root
          ref={ref}
          className={crafts.root(cxc(ui?.root, className))}
          onInteractOutside={(event) => {
            const target = interactTarget(event)
            if (
              findUp(target, node =>
                node.dataset.scope === 'editable' && exceptParts.includes(node.dataset.part ?? ''))
            ) {
              event.preventDefault()
              onInteractOutside?.(event)
            }
          }}
          {...props}
        >
          {prefix}
          <ArkEditable.Area className={crafts.area(cxc(ui?.area))}>
            {children}
          </ArkEditable.Area>
          {suffix}
        </ArkEditable.Root>
      </ProvideComponentTheme>
    )
  },
)

EditableRoot.displayName = 'Editable'
