// packages/react/core/src/components/tooltip/Tooltip.tsx
import type { TooltipProps } from './props'
import { Tooltip as ArkTooltip } from '@ark-ui/react/tooltip'
import { useConfig } from '@raxium/react/hooks/useConfig'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { defaults } from 'es-toolkit/compat'
import { useMemo } from 'react'

export function TooltipRoot({
  theme: propsTheme,
  craft,
  lazyMount,
  unmountOnExit,
  openDelay,
  closeDelay,
  positioning,
  children,
  ...props
}: TooltipProps) {
  const tooltipConfig = useConfig('tooltip', { lazyMount, unmountOnExit, openDelay, closeDelay })
  const mergedPositioning = useMemo(
    () => defaults({ ...(positioning ?? {}) }, { placement: tooltipConfig?.placement }),
    [tooltipConfig?.placement, positioning],
  )
  const theme = useTheme(propsTheme, tooltipConfig?.theme)
  const themed = useThemeCraft(theme, 'tvTooltip', craft)

  return (
    <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
      <ArkTooltip.Root
        lazyMount={tooltipConfig?.lazyMount}
        unmountOnExit={tooltipConfig?.unmountOnExit}
        openDelay={tooltipConfig?.openDelay}
        closeDelay={tooltipConfig?.closeDelay}
        positioning={mergedPositioning}
        {...props}
      >
        {children}
      </ArkTooltip.Root>
    </ProvideComponentTheme>
  )
}

TooltipRoot.displayName = 'Tooltip'

// packages/vue/core/src/components/tooltip/Tooltip.vue
<script setup lang="ts">
import type { TooltipRootEmits } from '@ark-ui/vue/tooltip'
import type { TooltipProps } from '.'
import { Tooltip, useTooltip } from '@ark-ui/vue/tooltip'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue/utils'
import { useConfig } from '@raxium/vue/composables/useConfig'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { useTheme } from '@raxium/vue/composables/useTheme'
import { useThemeCraft } from '@raxium/vue/composables/useThemeCraft'
import { defaults } from 'es-toolkit/compat'
import { computed, mergeProps } from 'vue'

const {
  theme: propsTheme,
  craft,
  lazyMount = undefined,
  unmountOnExit = undefined,
  ...props
} = defineProps<TooltipProps>()
const emit = defineEmits<TooltipRootEmits>()
const tooltipConfig = useConfig('tooltip', () => ({ lazyMount, unmountOnExit }))
const forwarded = useForwardProps(props)
const tooltip = useTooltip(
  computed(() =>
    mergeProps(
      {
        openDelay: tooltipConfig.value?.openDelay,
        closeDelay: tooltipConfig.value?.closeDelay,
      },
      forwarded.value,
      {
        positioning: defaults(
          { ...(forwarded.value.positioning ?? {}) },
          { placement: tooltipConfig.value?.placement },
        ),
      },
    ),
  ),
  emit,
)

// theme
const theme = useTheme(() => propsTheme, () => tooltipConfig.value?.theme)
const themed = useThemeCraft(theme, 'tvTooltip', () => craft)
useProvideComponentTheme(themed, () => propsTheme)

// expose
defineExpose({ $api: tooltip })
useForwardExpose()
</script>

<template>
  <Tooltip.RootProvider
    :value="tooltip"
    :lazy-mount="tooltipConfig?.lazyMount"
    :unmount-on-exit="tooltipConfig?.unmountOnExit"
  >
    <slot />
  </Tooltip.RootProvider>
</template>
