// packages/react/core/src/components/tooltip/TooltipContent.tsx
import type { CSSProperties } from 'react'
import type { TooltipContentProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { Tooltip as ArkTooltip } from '@ark-ui/react/tooltip'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useTeleportedDepth } from '@raxium/react/hooks/useDepth'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTeleportDetection } from '@raxium/react/hooks/useTeleportDetection'
import { useThemeAttrs } from '@raxium/react/hooks/useThemeAttrs'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useMemo } from 'react'
import { splitTooltipArrow } from './split-tooltip-arrow'

export const TooltipContent = forwardRef<HTMLDivElement, TooltipContentProps>(
  ({ className, theme: propsTheme, ui, children, ...props }, ref) => {
    const { isTeleported, setElementRef } = useTeleportDetection()
    const depth = useTeleportedDepth({
      type: 'tooltip',
      active: isTeleported,
      fallbackZIndex: 'var(--z-tooltip, var(--z-index))',
    })
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvTooltip')
    const themeAttrs = useThemeAttrs(theme)
    const { arrows, rest } = useMemo(() => splitTooltipArrow(children), [children])

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <ArkTooltip.Positioner
          ref={setElementRef}
          className={crafts.positioner(cxc(ui?.positioner))}
        >
          <ArkTooltip.Content
            ref={ref}
            className={crafts.content(cxc(ui?.content, className))}
            style={{ '--rui-z-index': isTeleported ? depth.zIndex : 'auto' } as CSSProperties}
            {...props}
            {...themeAttrs}
          >
            {arrows}
            <ark.div
              className={crafts.contentInner(cxc(ui?.inner))}
              {...themeAttrs}
            >
              {rest}
            </ark.div>
          </ArkTooltip.Content>
        </ArkTooltip.Positioner>
      </ProvideStructuralComponentTheme>
    )
  },
)

TooltipContent.displayName = 'Tooltip.Content'

// packages/vue/core/src/components/tooltip/TooltipContent.vue
<script setup lang="ts">
import type { TooltipContentProps } from '.'
import { useForwardExpose } from '@ark-ui/vue'
import { Tooltip } from '@ark-ui/vue/tooltip'
import { useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import {
  useCraft,
  useInheritedTheme,
  useProvideStructuralComponentTheme,
  useTeleportDetection,
  useTeleportedDepth,
  useThemeAttrs,
} from '@raxium/vue/composables'
import {
  checkContextVNodePosition,
  excludeVNodesByName,
  findVNodeByName,
} from '@raxium/vue/utils/vnode'
import { computed, useSlots } from 'vue'

const { class: propsClass, theme: propsTheme, ui, ...props } = defineProps<TooltipContentProps>()
const forwarded = useForwardProps<TooltipContentProps, { asChild?: boolean }>(props)

const slots = useSlots()
const defaultSlots = computed(() => slots.default?.())
checkContextVNodePosition(defaultSlots.value, 'TooltipContext', 'TooltipContent')
const arrowNode = computed(() => findVNodeByName(defaultSlots.value, 'TooltipArrow'))
const otherNodes = computed(() => excludeVNodesByName(defaultSlots.value, 'TooltipArrow'))

// teleport detection
const { isTeleported, setElementRef: setPositionerRef } = useTeleportDetection()
const depth = useTeleportedDepth({
  type: 'tooltip',
  active: isTeleported,
  fallbackZIndex: 'var(--z-tooltip, var(--z-index))',
})

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvTooltip')
const themeAttrs = useThemeAttrs(theme)
useProvideStructuralComponentTheme(theme, () => propsTheme)
const positionerStyle = computed(() => ({
  zIndex: isTeleported.value ? depth.zIndex.value : 'auto',
}))

// forward expose
const { forwardRef } = useForwardExpose()
</script>

<template>
  <Tooltip.Positioner
    :ref="setPositionerRef"
    :class="crafts.positioner(cxc(ui?.positioner))"
    :style="positionerStyle"
  >
    <Tooltip.Content
      v-bind="{ ...forwarded, ...themeAttrs }"
      :ref="forwardRef"
      :class="crafts.content(cxc(ui?.content, propsClass))"
    >
      <template v-if="arrowNode">
        <component :is="arrowNode" />
      </template>
      <div
        :class="crafts.contentInner(cxc(ui?.inner))"
        v-bind="themeAttrs"
      >
        <template
          v-for="node in otherNodes"
          :key="node.key"
        >
          <component :is="node" />
        </template>
      </div>
    </Tooltip.Content>
  </Tooltip.Positioner>
</template>
