// packages/vue/core/src/components/dialog/examples/controlled-and-events.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import {
  Dialog,
  DialogBody,
  DialogCloseTrigger,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTrigger,
  TriggerFrom,
} from '../index'

const open = ref(false)
const lastFrom = ref<string | null | undefined>(undefined)
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="flex items-center gap-3">
      <Button @click="open = true">
        Open (v-model)
      </Button>
      <span class="text-sm text-gray-ff">open: {{ open }}</span>
      <span class="text-xs opacity-75">lastFrom: {{ lastFrom }}</span>
    </div>

    <Dialog
      v-model:open="open"
      lazy-mount
      unmount-on-exit
      @open-change="(d) => { lastFrom = d.from }"
      @escape-key-down="() => { lastFrom = TriggerFrom.ESCAPE }"
      @interact-outside="() => { lastFrom = TriggerFrom.OUTSIDE }"
      @exit-complete="() => { /* just to show event exists */ }"
    >
      <DialogTrigger as-child>
        <Button variant="outlined">
          Open via Trigger
        </Button>
      </DialogTrigger>

      <DialogContent class="w-120">
        <DialogHeader>
          Controlled Dialog
        </DialogHeader>
        <DialogBody>
          <div class="flex flex-col gap-2">
            <div class="text-sm text-gray-cc">
              This example tracks the trigger source via <code class="text-gray-ff">openChange.details.from</code>.
            </div>
            <div class="flex items-center gap-3">
              <DialogCloseTrigger as-child :from="TriggerFrom.CLOSE_TRIGGER">
                <Button variant="text">
                  Close (close trigger)
                </Button>
              </DialogCloseTrigger>
              <DialogCloseTrigger as-child from="custom_from">
                <Button variant="text">
                  Close (custom from)
                </Button>
              </DialogCloseTrigger>
            </div>
          </div>
        </DialogBody>
        <DialogFooter
          @ok="() => { lastFrom = TriggerFrom.OK_BUTTON }"
          @cancel="() => { lastFrom = TriggerFrom.CANCEL_BUTTON }"
        />
      </DialogContent>
    </Dialog>
  </div>
</template>

// packages/react/core/src/components/dialog/examples/controlled-and-events.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Dialog, TriggerFrom } from '../index'

export function DialogControlledAndEventsExample() {
  const [open, setOpen] = useState(false)
  const [lastFrom, setLastFrom] = useState<string | null | undefined>()

  return (
    <div className="w-full flex flex-col gap-4">
      <div className="flex items-center gap-3">
        <Button onClick={() => setOpen(true)}>Open (controlled)</Button>
        <span className="text-sm text-gray-ff">
          open:
          {String(open)}
        </span>
        <span className="text-xs opacity-75">
          lastFrom:
          {lastFrom}
        </span>
      </div>

      <Dialog
        open={open}
        lazyMount
        unmountOnExit
        onOpenChange={(details) => {
          setOpen(details.open)
          setLastFrom(details.from)
        }}
        onEscapeKeyDown={() => setLastFrom(TriggerFrom.ESCAPE)}
        onInteractOutside={() => setLastFrom(TriggerFrom.OUTSIDE)}
      >
        <Dialog.Trigger asChild>
          <Button variant="outlined">Open via Trigger</Button>
        </Dialog.Trigger>
        <Dialog.Content className="w-120">
          <Dialog.Header>Controlled Dialog</Dialog.Header>
          <Dialog.Body>
            <div className="flex flex-col gap-2">
              <div className="text-sm text-gray-cc">
                通过
                {' '}
                <code className="text-gray-ff">onOpenChange.details.from</code>
                {' '}
                追踪关闭来源。
              </div>
              <div className="flex items-center gap-3">
                <Dialog.CloseTrigger asChild from={TriggerFrom.CLOSE_TRIGGER}>
                  <Button variant="text">Close (close trigger)</Button>
                </Dialog.CloseTrigger>
                <Dialog.CloseTrigger asChild from="custom_from">
                  <Button variant="text">Close (custom from)</Button>
                </Dialog.CloseTrigger>
              </div>
            </div>
          </Dialog.Body>
          <Dialog.Footer
            onOk={() => setLastFrom(TriggerFrom.OK_BUTTON)}
            onCancel={() => setLastFrom(TriggerFrom.CANCEL_BUTTON)}
          />
        </Dialog.Content>
      </Dialog>
    </div>
  )
}
