// packages/vue/core/src/components/dialog/examples/scrollable.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { Button } from '../../button'
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTrigger,
} from '../index'

const content = fakerEN.lorem.paragraphs(8)
</script>

<template>
  <Dialog>
    <DialogTrigger as-child>
      <Button class="w-fit" variant="outlined">
        Scrollable body
      </Button>
    </DialogTrigger>
    <DialogContent class="w-140">
      <DialogHeader> Scrollable Dialog </DialogHeader>
      <DialogBody class="h-50">
        <p class="whitespace-pre-wrap text-sm text-gray-cc">
          {{ content }}
        </p>
      </DialogBody>
      <DialogFooter />
    </DialogContent>
  </Dialog>
</template>

// packages/react/core/src/components/dialog/examples/scrollable.tsx
import { Button } from '../../button'
import { Dialog } from '../index'

const content = Array.from({ length: 8 }, (_, i) => `Paragraph ${i + 1}. Long body text for scrollable dialog content.`).join('\n\n')

export function DialogScrollableExample() {
  return (
    <Dialog>
      <Dialog.Trigger asChild>
        <Button className="w-fit" variant="outlined">Scrollable body</Button>
      </Dialog.Trigger>
      <Dialog.Content className="w-140">
        <Dialog.Header>Scrollable Dialog</Dialog.Header>
        <Dialog.Body className="h-50">
          <p className="whitespace-pre-wrap text-sm text-gray-cc">{content}</p>
        </Dialog.Body>
        <Dialog.Footer />
      </Dialog.Content>
    </Dialog>
  )
}
