// packages/react/core/src/components/popover/PopoverIndicator.tsx
import type { PopoverIndicatorProps } from './props'
import { PopoverIndicator as ArkPopoverIndicator } from '@ark-ui/react/popover'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { ChevronDown } from 'lucide-react'

export function PopoverIndicator({
  className,
  theme: propsTheme,
  asChild = true,
  children,
}: PopoverIndicatorProps) {
  const theme = useInheritedTheme(propsTheme)
  const crafts = useCraft(theme, 'tvPopover')

  return (
    <ArkPopoverIndicator asChild={asChild} className={crafts.indicator(cxc(className))}>
      {children ?? <ChevronDown />}
    </ArkPopoverIndicator>
  )
}

PopoverIndicator.displayName = 'Popover.Indicator'

// packages/vue/core/src/components/popover/PopoverIndicator.vue
<script setup lang="ts">
import type { PopoverIndicatorProps } from '.'
import { PopoverIndicator } from '@ark-ui/vue'
import { ChevronDown } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  asChild = true,
} = defineProps<PopoverIndicatorProps>()
const theme = useInheritedTheme(() => propsTheme)

const crafts = useCraft(theme, 'tvPopover')
</script>

<template>
  <PopoverIndicator
    :as-child="asChild"
    :class="crafts.indicator(cxc(propsClass))"
  >
    <slot>
      <ChevronDown />
    </slot>
  </PopoverIndicator>
</template>
