// packages/vue/core/src/components/pagination/examples/events.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Pagination, PaginationPageSize } from '../index'

const page = ref(1)
const pageSize = ref(10)
const lines = ref<string[]>([])

function push(line: string) {
  lines.value = [line, ...lines.value].slice(0, 8)
}

const joined = computed(() => (lines.value.length ? lines.value.join('\n') : '（暂无事件）'))
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="text-sm text-gray-cc">
      监听：page-change / page-size-change / update:page / update:pageSize
    </div>

    <div class="w-full max-w-[720px] rounded-md border border-gray-33 p-3">
      <Pagination
        v-model:page="page"
        v-model:page-size="pageSize"
        :count="123"
        :sibling-count="1"
        @page-change="(d) => push(`page-change: page=${d.page} pageSize=${d.pageSize}`)"
        @page-size-change="(d) => push(`page-size-change: pageSize=${d.pageSize}`)"
        @update:page="(p) => push(`update:page: ${p}`)"
        @update:page-size="(ps) => push(`update:pageSize: ${ps}`)"
      >
        <PaginationPageSize />
      </Pagination>
    </div>

    <pre class="w-full max-w-[720px] whitespace-pre-wrap rounded-md bg-gray-0c p-3 text-xs text-gray-cc">{{ joined }}</pre>
  </div>
</template>

// packages/react/core/src/components/pagination/examples/events.tsx
import { useState } from 'react'
import { Pagination } from '../index'

export function PaginationEventsExample() {
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [lines, setLines] = useState<string[]>([])

  function push(line: string) {
    setLines(current => [line, ...current].slice(0, 8))
  }

  const joined = lines.length ? lines.join('\n') : '（暂无事件）'

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="text-sm text-gray-cc">
        监听：onPageChange / onPageSizeChange
      </div>

      <div className="w-full max-w-[720px] rounded-md border border-gray-33 p-3">
        <Pagination
          page={page}
          pageSize={pageSize}
          count={123}
          siblingCount={1}
          onPageChange={(details) => {
            setPage(details.page)
            push(`page-change: page=${details.page} pageSize=${details.pageSize}`)
          }}
          onPageSizeChange={(details) => {
            setPageSize(details.pageSize)
            push(`page-size-change: pageSize=${details.pageSize}`)
          }}
        >
          <Pagination.PageSize />
        </Pagination>
      </div>

      <pre className="w-full max-w-[720px] whitespace-pre-wrap rounded-md bg-gray-0c p-3 text-xs text-gray-cc">
        {joined}
      </pre>
    </div>
  )
}
