// packages/react/core/src/components/skeleton/examples/variants.tsx
import { Skeleton } from '../index'

export function SkeletonVariantsExample() {
  return (
    <div className="w-full flex flex-col gap-4">
      <div className="flex flex-col gap-2">
        <div className="text-sm text-gray-cc">variant=pulse</div>
        <Skeleton className="h-4 w-64" variant="pulse" />
      </div>
      <div className="flex flex-col gap-2">
        <div className="text-sm text-gray-cc">variant=wave</div>
        <Skeleton className="h-4 w-64" variant="wave" />
      </div>
    </div>
  )
}

// packages/vue/core/src/components/radio-group/examples/variants.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { ref } from 'vue'
import { RadioGroup, RadioGroupItem } from '../index'

const items = Array.from({ length: 6 }, () => {
  const fruit = fakerEN.food.fruit()
  return { text: fruit, value: fruit }
})
const value = ref<string | undefined>(items[0]?.value)
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="text-sm text-gray-ff">
      Mixed variants
    </div>
    <RadioGroup v-model="value">
      <RadioGroupItem
        v-for="(item, index) in items"
        :key="item.value"
        :variant="index % 2 === 0 ? 'default' : 'checkbox'"
        :text="item.text"
        :value="item.value"
      />
    </RadioGroup>
  </div>
</template>
