// packages/vue/core/src/components/number-input/examples/triggers.vue
<script setup lang="ts">
import { ref } from 'vue'
import { NumberInput } from '../index'

const value = ref('10')
</script>

<template>
  <div class="w-full flex flex-col gap-2">
    <div class="text-sm text-gray-cc">
      showTrigger=true
    </div>

    <div class="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
      <NumberInput v-model="value" show-trigger :min="0" :max="100" :step="1" />
    </div>
  </div>
</template>

// packages/react/core/src/components/number-input/examples/triggers.tsx
import { useState } from 'react'
import { NumberInput } from '../index'

export function NumberInputTriggersExample() {
  const [value, setValue] = useState('10')

  return (
    <div className="w-full flex flex-col gap-2">
      <div className="text-sm text-gray-cc">
        showTrigger=true
      </div>

      <div className="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
        <NumberInput
          value={value}
          showTrigger
          min={0}
          max={100}
          step={1}
          onValueChange={details => setValue(details.value)}
        />
      </div>
    </div>
  )
}
