// packages/vue/core/src/components/hotkey/examples/states.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Hotkey } from '../index'

const normal = ref('Ctrl + Shift + K')
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <Hotkey v-model:hotkey="normal" class="w-80" />
    <Hotkey hotkey="" class="w-80" disabled />
    <Hotkey hotkey="Ctrl + Shift + P" class="w-80" readonly />
  </div>
</template>

// packages/react/core/src/components/hotkey/examples/states.tsx
import { useState } from 'react'
import { Hotkey } from '../index'

export function HotkeyStatesExample() {
  const [normal, setNormal] = useState('Ctrl + Shift + K')

  return (
    <div className="w-full flex flex-col gap-3">
      <Hotkey hotkey={normal} className="w-80" onHotkeyChange={setNormal} />
      <Hotkey hotkey="" className="w-80" disabled />
      <Hotkey hotkey="Ctrl + Shift + P" className="w-80" readOnly />
    </div>
  )
}
