// packages/vue/core/src/components/rating-group/RatingGroupItem.vue
<script setup lang="ts">
import type { RatingGroupItemProps } from '.'
import { RatingGroup } from '@ark-ui/vue/rating-group'
import { useForwardProps } from '@ark-ui/vue/utils'
import { Star } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'
import { computed } from 'vue'

const { class: propsClass, theme: propsTheme, ui, ...props } = defineProps<RatingGroupItemProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvRatingGroup')
const indicatorClx = computed(() => crafts.value.itemIndicator(cxc(ui?.indicator)))
const iconClx = computed(() => crafts.value.itemIndicatorIcon(cxc(ui?.icon)))
</script>

<template>
  <RatingGroup.Item
    v-bind="forwarded"
    :class="crafts.item(cxc(ui?.root, propsClass))"
  >
    <RatingGroup.ItemContext v-slot="{ highlighted, half, checked }">
      <slot
        v-bind="{
          classes: {
            indicator: indicatorClx,
            icon: iconClx,
          },
          context: {
            highlighted,
            half,
            checked,
          },
          index: forwarded.index,
        }"
      >
        <span
          :class="indicatorClx"
          :data-highlighted="highlighted ? '' : undefined"
          :data-half="half ? '' : undefined"
        >
          <Star
            :class="iconClx"
            data-bg=""
          />
          <Star
            :class="iconClx"
            data-fg=""
          />
        </span>
      </slot>
    </RatingGroup.ItemContext>
  </RatingGroup.Item>
</template>

// packages/react/core/src/components/rating-group/RatingGroupItem.tsx
import type { RatingGroupItemProps } from './props'
import { RatingGroup as ArkRatingGroup, useRatingGroupItemContext } from '@ark-ui/react/rating-group'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { Star } from 'lucide-react'
import { forwardRef } from 'react'

function DefaultIndicator({
  indicatorClassName,
  iconClassName,
}: {
  indicatorClassName?: string
  iconClassName?: string
}) {
  const { highlighted, half } = useRatingGroupItemContext()

  return (
    <span
      className={indicatorClassName}
      data-highlighted={highlighted ? '' : undefined}
      data-half={half ? '' : undefined}
    >
      <Star className={iconClassName} data-bg="" />
      <Star className={iconClassName} data-fg="" />
    </span>
  )
}

export const RatingGroupItem = forwardRef<HTMLSpanElement, RatingGroupItemProps>(
  ({ className, theme: propsTheme, ui, indicator, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvRatingGroup')

    return (
      <ArkRatingGroup.Item
        ref={ref}
        className={crafts.item(cxc(ui?.root, className))}
        {...props}
      >
        {indicator ?? children ?? (
          <DefaultIndicator
            indicatorClassName={crafts.itemIndicator(cxc(ui?.indicator))}
            iconClassName={crafts.itemIndicatorIcon(cxc(ui?.icon))}
          />
        )}
      </ArkRatingGroup.Item>
    )
  },
)

RatingGroupItem.displayName = 'RatingGroup.Item'
