// packages/react/core/src/components/toast/Toast.tsx
import type { ToastProps } from './props'
import { ark } from '@ark-ui/react/factory'
import {
  ToastCloseTrigger,
  ToastDescription,
  ToastRoot,
  ToastTitle,
  useToastContext,
} from '@ark-ui/react/toast'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cn, cxc } from '@raxium/themes/utils'
import { CircleAlert, CircleCheck, CircleX, Info, LoaderCircle, X } from 'lucide-react'

function TypeIcon({ className, type }: { className?: string, type?: string }) {
  const props = { className, 'data-type': type }
  switch (type) {
    case 'success':
      return <CircleCheck {...props} />
    case 'error':
      return <CircleX {...props} />
    case 'warning':
      return <CircleAlert {...props} />
    case 'loading':
      return <LoaderCircle {...props} className={cn(className, 'animate-spin')} />
    case 'info':
    default:
      return <Info {...props} />
  }
}

export function Toast({
  className,
  theme: propsTheme,
  options,
  ui,
  icon,
  close,
  ...props
}: ToastProps) {
  const toast = useToastContext()
  const theme = useInheritedTheme({ ...propsTheme, ...options?.theme })
  const crafts = useCraft(theme, 'tvToast')

  return (
    <ToastRoot className={crafts.root(cxc(ui?.root, className))} {...props}>
      <ark.div
        className={crafts.content(cxc(ui?.content))}
        data-scope="toast"
        data-part="content"
        data-placement={toast.placement}
        data-type={toast.type}
      >
        {options?.render
          ? options.render()
          : (
              <>
                {icon ?? <TypeIcon className={crafts.icon(cxc(ui?.icon))} type={toast.type} />}
                <ark.div
                  className={crafts.inner(cxc(ui?.inner))}
                  data-part="inner"
                  data-scope="toast"
                >
                  {options?.title != null && (
                    <ToastTitle className={crafts.title(cxc(ui?.title))}>
                      {options.title}
                    </ToastTitle>
                  )}
                  {options?.description != null && (
                    <ToastDescription className={crafts.description(cxc(ui?.description))}>
                      {options.description}
                    </ToastDescription>
                  )}
                </ark.div>
                {toast.type !== 'loading' && (
                  close ?? (
                    <ToastCloseTrigger className={crafts.close(cxc(ui?.close))}>
                      <X />
                    </ToastCloseTrigger>
                  )
                )}
              </>
            )}
      </ark.div>
    </ToastRoot>
  )
}

Toast.displayName = 'Toast'

// packages/vue/core/src/components/toast/Toast.vue
<script setup lang="ts">
import type { UnwrapRef } from 'vue'
import type { ToastProps, UseToastContext } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { ark } from '@ark-ui/vue/factory'
import { Toast, useToastContext } from '@ark-ui/vue/toast'
import { CircleAlert, CircleCheck, CircleX, Info, LoaderCircle, X } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme } from '@raxium/vue/composables'
import { computed, h } from 'vue'

const { class: propsClass, theme: propsTheme, options, ui, ...props } = defineProps<ToastProps>()
defineSlots<{
  default: (props: UnwrapRef<typeof slotBindings>) => any
  icon: (props: UnwrapRef<typeof slotBindings>) => any
  inner: (props: UnwrapRef<typeof slotBindings>) => any
  close: (props: UnwrapRef<typeof slotBindings>) => any
}>()
const forwarded = useForwardProps(props)
const toastContext: UseToastContext = useToastContext()
const slotBindings = computed(() => ({
  options,
  context: toastContext.value,
}))

// theme
const theme = useTheme(() => Object.assign({}, propsTheme, options?.theme))
const crafts = useCraft(theme, 'tvToast')
const iconVNode = computed(() => {
  const className = crafts.value.icon(cxc(ui?.icon))
  switch (toastContext.value.type) {
    case 'info':
      return h(Info, {
        'class': className,
        'data-type': toastContext.value.type,
      })
    case 'success':
      return h(CircleCheck, {
        'class': className,
        'data-type': toastContext.value.type,
      })
    case 'error':
      return h(CircleX, {
        'class': className,
        'data-type': toastContext.value.type,
      })
    case 'warning':
      return h(CircleAlert, {
        'class': className,
        'data-type': toastContext.value.type,
      })
    case 'loading':
      return h(LoaderCircle, {
        'class': className,
        'data-type': toastContext.value.type,
      })
    default:
      return h(Info, {
        'class': className,
        'data-type': toastContext.value.type,
      })
  }
})
</script>

<template>
  <Toast.Root
    v-bind="forwarded"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <ark.div
      :class="crafts.content(cxc(ui?.content))"
      data-scope="toast"
      data-part="content"
      :data-placement="toastContext.placement"
      :data-type="toastContext.type"
    >
      <component
        :is="options?.render(toastContext)"
        v-if="options?.render"
      />
      <slot
        v-else
        name="default"
        v-bind="slotBindings"
      >
        <slot
          name="icon"
          v-bind="slotBindings"
        >
          <component :is="iconVNode" />
        </slot>
        <ark.div
          :class="crafts.inner(cxc(ui?.inner))"
          data-part="inner"
          data-scope="toast"
        >
          <slot
            name="inner"
            v-bind="slotBindings"
          >
            <template v-if="typeof options?.title === 'function'">
              <component :is="options?.title(toastContext)" />
            </template>
            <template v-else>
              <Toast.Title :class="crafts.title(cxc(ui?.title))">
                {{ options?.title }}
              </Toast.Title>
            </template>
            <template v-if="typeof options?.description === 'function'">
              <component :is="options?.description(toastContext)" />
            </template>
            <template v-else>
              <Toast.Description :class="crafts.description(cxc(ui?.description))">
                {{ options?.description }}
              </Toast.Description>
            </template>
          </slot>
        </ark.div>
        <slot
          name="close"
          v-bind="slotBindings"
        >
          <Toast.CloseTrigger
            v-if="toastContext.type !== 'loading'"
            :class="crafts.close(cxc(ui?.close))"
          >
            <X />
          </Toast.CloseTrigger>
        </slot>
      </slot>
    </ark.div>
  </Toast.Root>
</template>
