// packages/react/core/src/components/toast/ToasterManager.tsx
import type { ToasterManagerExpose, ToasterManagerProps, ToasterWrap } from './props'
import { useCallback, useMemo, useState } from 'react'
import { DEFAULT_TOASTER_ID } from './props'
import { Toaster } from './Toaster'
import { ToasterRegistryProvider } from './toaster-registry'

export function ToasterManager({
  disableDefaultToaster = false,
  defaultToasterProps,
  children,
}: ToasterManagerProps) {
  const [toasters, setToasters] = useState<ToasterWrap[]>([])

  const register = useCallback((wrap: ToasterWrap) => {
    setToasters(prev => [...prev.filter(item => item.toasterId !== wrap.toasterId), wrap])
    return () => {
      setToasters(prev => prev.filter(item => item.toasterId !== wrap.toasterId))
    }
  }, [])

  const expose = useMemo<ToasterManagerExpose>(() => ({ toasters }), [toasters])
  void expose

  return (
    <ToasterRegistryProvider register={register} toasters={toasters}>
      {children}
      {!disableDefaultToaster && (
        <Toaster
          placement="bottom-end"
          overlap
          {...defaultToasterProps}
          toasterId={DEFAULT_TOASTER_ID}
        />
      )}
    </ToasterRegistryProvider>
  )
}

ToasterManager.displayName = 'ToasterManager'

// packages/vue/core/src/components/toast/ToasterManager.vue
<script setup lang="ts">
import type { VNode } from 'vue'
import type { ToasterManagerProps, ToasterWrap } from '.'
import { computed, ref, useSlots } from 'vue'
import { DEFAULT_TOASTER_ID, Toast, Toaster } from '.'

const { disableDefaultToaster = false, defaultToasterProps } = defineProps<ToasterManagerProps>()

const slots = useSlots()
const defaultSlots = computed(() => slots.default?.())
const toasterVNodes = computed(() => {
  if (
    defaultSlots.value?.length === 1
    && typeof defaultSlots.value?.[0] === 'object'
    && Array.isArray((defaultSlots.value?.[0] as VNode)?.children)
  ) {
    // is slot node
    return (defaultSlots.value?.[0] as any).children as VNode[]
  }
  return defaultSlots.value
})

// expose
const slotsToasters = ref<ToasterWrap[]>([])
const defaultToaster = ref<ToasterWrap>()
defineExpose({
  toasters: computed(() =>
    [...slotsToasters.value, defaultToaster.value].filter(r => r && r.toaster),
  ),
})
</script>

<template>
  <template v-if="toasterVNodes?.length">
    <component
      :is="node"
      v-for="(node, index) in toasterVNodes"
      :key="node.key"
      :ref="(el: ToasterWrap) => { slotsToasters[index] = el }"
    />
  </template>
  <Toaster
    v-if="!disableDefaultToaster"
    v-slot="{ toast, props }"
    ref="defaultToaster"
    placement="bottom-end"
    overlap
    v-bind="defaultToasterProps"
    :toaster-id="DEFAULT_TOASTER_ID"
  >
    <Toast
      :options="toast"
      v-bind="props"
    />
  </Toaster>
</template>
