// packages/react/core/src/components/spin/SpinProvider.tsx
import type { ReactNode } from 'react'
import type { SpinProviderProps, SpinRenderProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { LoaderCircle } from 'lucide-react'
import { clsx } from '@raxium/themes/utils'
import { createContext, useContext } from 'react'

export interface SpinProviderValue {
  renderIcon: (props: SpinRenderProps) => ReactNode
}

const SpinProviderContext = createContext<SpinProviderValue | null>(null)

export function SpinProvider({ children, icon }: SpinProviderProps) {
  function renderIcon(props: SpinRenderProps) {
    const crafts = props.theme?.crafts?.tvSpin?.()
    const custom = typeof icon === 'function' ? icon(props) : icon
    if (custom != null) {
      return (
        <ark.span
          className={crafts?.icon({ class: clsx(props.className), ...props.theme })}
          asChild
          data-variant="custom"
        >
          {custom}
        </ark.span>
      )
    }
    return (
      <LoaderCircle
        className={crafts?.icon({ class: clsx('animate-spin', props.className), ...props.theme })}
        data-variant="default"
      />
    )
  }

  return (
    <SpinProviderContext.Provider value={{ renderIcon }}>
      {children}
    </SpinProviderContext.Provider>
  )
}

export function useSpinProvider() {
  return useContext(SpinProviderContext)
}

// packages/vue/core/src/components/spin/SpinProvider.tsx
import type { SlotsType, VNode } from 'vue'
import type { SpinRenderProps } from '.'
import { ark } from '@ark-ui/vue/factory'
import { LoaderCircle } from '@lucide/vue'
import { clsx } from '@raxium/themes/utils'
import { isEmptyVNode } from '@raxium/vue/utils'
import { computed, defineComponent, provide } from 'vue'

/**
 * rslib无法解析<script setup lang="tsx">的组件, 会解析为虚拟请求(?vue), 导致解析链断掉
 * 继续使用bundle:false, 需要直接解析tsx文件
 */
type Slots = {
  default: () => VNode
  icon: (props: SpinRenderProps) => VNode | null | undefined
}
export default defineComponent({
  name: 'SpinProvider',
  slots: Object as SlotsType<Slots>,
  setup(_, { slots }) {
    function renderIcon(props: SpinRenderProps) {
      const icon = slots?.icon?.(props)
      const crafts = computed(() => props.theme?.crafts?.tvSpin?.())
      if (!isEmptyVNode(icon)) {
        return (
          <ark.span
            class={crafts.value?.icon({
              class: clsx(props.class),
              ...props.theme,
            })}
            as-child
            data-variant="custom"
          >
            {icon}
          </ark.span>
        )
      }
      return (
        <LoaderCircle
          class={crafts.value?.icon({
            class: clsx('animate-spin', props.class),
            ...props.theme,
          })}
          data-variant="default"
        />
      )
    }
    provide('SpinProvider', { renderIcon })

    // render
    return () => slots.default?.()
  },
})
