// packages/react/core/src/components/select/SelectItem.tsx
import type { SelectItemProps } from './props'
import { Select as ArkSelect } from '@ark-ui/react/select'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { Check } from 'lucide-react'
import { forwardRef } from 'react'

export const SelectItem = forwardRef<HTMLDivElement, SelectItemProps>(
  ({ className, theme: propsTheme, indicator, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvSelect')

    return (
      <ArkSelect.Item
        ref={ref}
        className={crafts.item(cxc(className))}
        {...props}
      >
        <ArkSelect.ItemText>
          {children}
        </ArkSelect.ItemText>
        {indicator ?? (
          <ArkSelect.ItemIndicator className={crafts.itemIndicator()}>
            <Check />
          </ArkSelect.ItemIndicator>
        )}
      </ArkSelect.Item>
    )
  },
)

SelectItem.displayName = 'Select.Item'

// packages/vue/core/src/components/select/SelectItem.vue
<script setup lang="ts">
import type { SelectItemProps } from '.'
import { Select } from '@ark-ui/vue/select'
import { useForwardProps } from '@ark-ui/vue/utils'
import { Check } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<SelectItemProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvSelect')
</script>

<template>
  <Select.Item
    v-bind="forwarded"
    :class="crafts.item(cxc(propsClass))"
  >
    <Select.ItemText>
      <slot />
    </Select.ItemText>
    <slot name="indicator">
      <Select.ItemIndicator :class="crafts.itemIndicator()">
        <Check />
      </Select.ItemIndicator>
    </slot>
  </Select.Item>
</template>
