// packages/react/core/src/components/select/SelectValue.tsx
import type { SelectValueProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { Select as ArkSelect } from '@ark-ui/react/select'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const SelectValue = forwardRef<HTMLSpanElement, SelectValueProps>(
  ({ className, theme: propsTheme, asChild, placeholder, children }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvSelect')

    return (
      <ark.span
        ref={ref}
        className={crafts.value(cxc(className))}
        asChild={asChild}
      >
        {children ?? <ArkSelect.ValueText placeholder={placeholder} />}
      </ark.span>
    )
  },
)

SelectValue.displayName = 'Select.Value'

// packages/vue/core/src/components/select/SelectValue.vue
<script setup lang="ts">
import type { SelectValueProps } from '.'
import { ark } from '@ark-ui/vue/factory'
import { Select } from '@ark-ui/vue/select'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  asChild,
  placeholder,
} = defineProps<SelectValueProps>()

const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvSelect')
</script>

<template>
  <ark.span
    :class="crafts.value(cxc(propsClass))"
    :as-child="asChild"
  >
    <slot>
      <Select.ValueText :placeholder="placeholder" />
    </slot>
  </ark.span>
</template>
