// packages/react/core/src/components/floating-panel/FloatingPanelCloseTrigger.tsx
import type { FloatingPanelCloseTriggerProps } from './props'
import { FloatingPanel as ArkFloatingPanel } from '@ark-ui/react/floating-panel'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { X } from 'lucide-react'
import { forwardRef } from 'react'

export const FloatingPanelCloseTrigger = forwardRef<HTMLButtonElement, FloatingPanelCloseTriggerProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvFloatingPanel')

    return (
      <ArkFloatingPanel.CloseTrigger
        ref={ref}
        className={crafts.trigger(cxc(className))}
        {...props}
      >
        {children ?? <X />}
      </ArkFloatingPanel.CloseTrigger>
    )
  },
)

FloatingPanelCloseTrigger.displayName = 'FloatingPanel.CloseTrigger'

// packages/vue/core/src/components/floating-panel/FloatingPanelCloseTrigger.vue
<script setup lang="ts">
import type { FloatingPanelCloseTriggerProps } from '.'
import { FloatingPanel, useForwardProps } from '@ark-ui/vue'
import { X } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'

const {
  class: propsClass,
  theme: propsTheme,
  ...props
} = defineProps<FloatingPanelCloseTriggerProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvFloatingPanel')
</script>

<template>
  <FloatingPanel.CloseTrigger
    v-bind="forwarded"
    :class="crafts.trigger(cxc(propsClass))"
  >
    <slot>
      <X />
    </slot>
  </FloatingPanel.CloseTrigger>
</template>
