// packages/react/core/src/components/floating-panel/FloatingPanelContent.tsx
import type { CSSProperties } from 'react'
import type { FloatingPanelContentProps } from './props'
import { FloatingPanel as ArkFloatingPanel, useFloatingPanelContext } from '@ark-ui/react/floating-panel'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { DepthOwnerProvider, useDepthOwner } from '@raxium/react/hooks/useDepth'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { cxc } from '@raxium/themes/utils'
import { isNil } from 'es-toolkit'
import { forwardRef, useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'
import { useFloatingPanelAppearance } from './floating-panel-appearance-context'
import { floatingPanelResizeTriggers } from './resize-triggers'

export const FloatingPanelContent = forwardRef<HTMLDivElement, FloatingPanelContentProps>(
  ({ className, theme: propsTheme, ui, children, style, ...props }, ref) => {
    const { opacity, resizeAxis } = useFloatingPanelAppearance()
    const api = useFloatingPanelContext()
    const depthOwner = useDepthOwner('floating-panel', { active: true })
    const wasTopmost = useRef(false)
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvFloatingPanel')
    const topmost = !isNil((api.getContentProps() as Record<string, unknown>)['data-topmost'])

    useEffect(() => {
      if (topmost && !wasTopmost.current)
        depthOwner.bringToFront()
      wasTopmost.current = topmost
    }, [depthOwner.bringToFront, topmost])

    if (typeof document === 'undefined')
      return null

    return createPortal(
      <ProvideStructuralComponentTheme theme={theme}>
        <DepthOwnerProvider owner={depthOwner}>
          <ArkFloatingPanel.Positioner
            className={crafts.positioner(cxc(ui?.positioner))}
            style={{ zIndex: depthOwner.contentZIndex } as CSSProperties}
          >
            <ArkFloatingPanel.Content
              ref={ref}
              className={crafts.content(cxc(ui?.content, className))}
              {...props}
              style={{ opacity: opacity / 100, ...style }}
            >
              {children}
              {floatingPanelResizeTriggers(resizeAxis, {
                resizeVertical: crafts.resizeVertical(cxc(ui?.resizeVertical)),
                resizeHorizontal: crafts.resizeHorizontal(cxc(ui?.resizeHorizontal)),
                resizeCorner: crafts.resizeCorner(cxc(ui?.resizeCorner)),
              })}
            </ArkFloatingPanel.Content>
          </ArkFloatingPanel.Positioner>
        </DepthOwnerProvider>
      </ProvideStructuralComponentTheme>,
      document.body,
    )
  },
)

FloatingPanelContent.displayName = 'FloatingPanel.Content'

// packages/vue/core/src/components/floating-panel/FloatingPanelContent.vue
<script setup lang="ts">
import type { ResizeTriggerAxis } from '@zag-js/floating-panel'
import type { VNode } from 'vue'
import type { FloatingPanelContentProps } from '.'
import { FloatingPanel, useFloatingPanelContext } from '@ark-ui/vue'
import { cxc } from '@raxium/themes/utils'
import {
  provideDepthOwner,
  useCraft,
  useDepthOwner,
  useProvideStructuralComponentTheme,
} from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { isNil } from 'es-toolkit'
import { computed, h, toValue, watch } from 'vue'
import { injectFloatingPanelAppearanceContext } from './floating-panel-appearance-context'

const {
  class: propsClass,
  theme: propsTheme,
  ui,
  ...props
} = defineProps<FloatingPanelContentProps>()

const { opacity, resizeAxis } = injectFloatingPanelAppearanceContext()
const api = useFloatingPanelContext()

// depth
const depthOwner = useDepthOwner('floating-panel', { active: true })
provideDepthOwner(depthOwner)
watch(
  () => {
    return !isNil((api.value.getContentProps() as Record<string, unknown>)['data-topmost'])
  },
  (topmost, prev) => {
    if (topmost && !prev)
      depthOwner.bringToFront()
  },
  { immediate: true },
)

// theme
const theme = useInheritedTheme(() => propsTheme)
useProvideStructuralComponentTheme(theme, () => propsTheme)
const crafts = useCraft(theme, 'tvFloatingPanel')
const style = computed(() => ({
  opacity: opacity.value / 100,
}))
const positionerStyle = computed(() => ({
  zIndex: depthOwner.contentZIndex.value,
}))

const resizeNodes = computed(() => {
  const axis = toValue(resizeAxis)
  let nodes: VNode[] = []
  switch (axis) {
    case 'x':
      nodes = ['e', 'w'].map(ax =>
        h(FloatingPanel.ResizeTrigger, {
          axis: ax as ResizeTriggerAxis,
          class: crafts.value.resizeVertical(cxc(ui?.resizeVertical)),
        }),
      )
      break
    case 'y':
      nodes = ['n', 's'].map(ax =>
        h(FloatingPanel.ResizeTrigger, {
          axis: ax as ResizeTriggerAxis,
          class: crafts.value.resizeHorizontal(cxc(ui?.resizeHorizontal)),
        }),
      )
      break
    case 'xy':
      nodes = ['e', 'w', 'n', 's'].map(ax =>
        h(FloatingPanel.ResizeTrigger, {
          axis: ax as ResizeTriggerAxis,
          class:
            ax === 'e' || ax === 'w'
              ? crafts.value.resizeVertical(cxc(ui?.resizeVertical))
              : crafts.value.resizeHorizontal(cxc(ui?.resizeHorizontal)),
        }),
      )
      break
    case 'xyc':
      nodes = ['e', 'w', 'n', 's', 'ne', 'nw', 'se', 'sw'].map((ax) => {
        if (ax.length === 1) {
          // line
          return h(FloatingPanel.ResizeTrigger, {
            axis: ax as ResizeTriggerAxis,
            class:
              ax === 'e' || ax === 'w'
                ? crafts.value.resizeVertical(cxc(ui?.resizeVertical))
                : crafts.value.resizeHorizontal(cxc(ui?.resizeHorizontal)),
          })
        }
        // corner
        return h(FloatingPanel.ResizeTrigger, {
          axis: ax as ResizeTriggerAxis,
          class: crafts.value.resizeCorner(cxc(ui?.resizeCorner)),
        })
      })
      break
    case 'custom':
    default:
      break
  }
  return nodes
})
</script>

<template>
  <Teleport to="body">
    <FloatingPanel.Positioner
      :class="crafts.positioner(cxc(ui?.positioner, propsClass))"
      :style="positionerStyle"
    >
      <FloatingPanel.Content
        v-bind="props"
        :class="crafts.content(cxc(ui?.content, propsClass))"
        :style="style"
      >
        <slot />
        <template
          v-for="node in resizeNodes"
          :key="node.key"
        >
          <component :is="node" />
        </template>
      </FloatingPanel.Content>
    </FloatingPanel.Positioner>
  </Teleport>
</template>
