// packages/react/core/src/components/floating-panel/FloatingPanelOpacityTrigger.tsx
import type { FloatingPanelOpacityTriggerProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const FloatingPanelOpacityTrigger = forwardRef<HTMLButtonElement, FloatingPanelOpacityTriggerProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvFloatingPanel')

    return (
      <ark.button
        ref={ref}
        type="button"
        className={crafts.trigger(cxc(className))}
        {...props}
      >
        {children}
      </ark.button>
    )
  },
)

FloatingPanelOpacityTrigger.displayName = 'FloatingPanel.OpacityTrigger'

// packages/vue/core/src/components/floating-panel/FloatingPanelOpacityTrigger.vue
<script setup lang="ts">
import type { FloatingPanelOpacityTriggerProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { ark } from '@ark-ui/vue/factory'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { injectFloatingPanelAppearanceContext } from './floating-panel-appearance-context'

const {
  class: propsClass,
  theme: propsTheme,
  ...props
} = defineProps<FloatingPanelOpacityTriggerProps>()
const forwarded = useForwardProps(props)
const { opacity, setOpacity } = injectFloatingPanelAppearanceContext()

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvFloatingPanel')
</script>

<template>
  <ark.button
    v-bind="forwarded"
    :class="crafts.trigger(cxc(propsClass))"
  >
    <slot v-bind="{ opacity, opacityGetter: () => opacity, setOpacity }" />
  </ark.button>
</template>
