// packages/react/core/src/components/menu/examples/submenu.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Menu } from '../index'

const vegetables = ['Carrot', 'Broccoli', 'Spinach', 'Kale', 'Celery']
const fruits = ['Apple', 'Banana', 'Cherry', 'Mango', 'Pear']

export function MenuSubmenuExample() {
  const [selected, setSelected] = useState<string | undefined>()

  return (
    <div className="w-full flex items-center gap-4">
      <span className="text-sm text-gray-ff">
        Selected:
        {' '}
        {selected}
      </span>

      <Menu theme={{ size: 'sm' }} onSelect={details => setSelected(details.value)}>
        <Menu.Trigger asChild>
          <Button>Submenu</Button>
        </Menu.Trigger>
        <Menu.Content>
          <Menu.Arrow />
          <Menu positioning={{ placement: 'right', offset: { mainAxis: 10 } }}>
            <Menu.TriggerItem>
              Vegetables
            </Menu.TriggerItem>
            <Menu.Content>
              {vegetables.map(vegetable => (
                <Menu.Item key={vegetable} value={vegetable}>
                  <Menu.ItemText>{vegetable}</Menu.ItemText>
                </Menu.Item>
              ))}
            </Menu.Content>
          </Menu>
          <Menu positioning={{ placement: 'right', offset: { mainAxis: 10 } }}>
            <Menu.TriggerItem>
              Fruits
            </Menu.TriggerItem>
            <Menu.Content>
              {fruits.map(fruit => (
                <Menu.Item key={fruit} value={fruit}>
                  <Menu.ItemText>{fruit}</Menu.ItemText>
                </Menu.Item>
              ))}
            </Menu.Content>
          </Menu>
        </Menu.Content>
      </Menu>
    </div>
  )
}

// packages/vue/core/src/components/menu/examples/submenu.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { ref } from 'vue'
import { Button } from '../../button'
import {
  Menu,
  MenuArrow,
  MenuContent,
  MenuItem,
  MenuItemText,
  MenuTrigger,
  MenuTriggerItem,
} from '../index'

const vegetables = Array.from({ length: 5 }, () => fakerEN.food.vegetable())
const fruits = Array.from({ length: 5 }, () => fakerEN.food.fruit())
const selected = ref<string | undefined>(undefined)
</script>

<template>
  <div class="w-full flex items-center gap-4">
    <span class="text-sm text-gray-ff">Selected: {{ selected }}</span>

    <Menu :theme="{ size: 'sm' }" @select="selected = $event.value">
      <MenuTrigger as-child>
        <Button>Submenu</Button>
      </MenuTrigger>
      <MenuContent>
        <MenuArrow />

        <Menu
          key="vegetables"
          :positioning="{ placement: 'right', offset: { mainAxis: 10 } }"
        >
          <MenuTriggerItem value="vegetables">
            Vegetables
          </MenuTriggerItem>
          <Teleport to="body">
            <MenuContent>
              <MenuItem
                v-for="vegetable in vegetables"
                :key="vegetable"
                :value="vegetable"
              >
                <MenuItemText>{{ vegetable }}</MenuItemText>
              </MenuItem>
            </MenuContent>
          </Teleport>
        </Menu>

        <Menu
          key="fruits"
          :positioning="{ placement: 'right', offset: { mainAxis: 10 } }"
        >
          <MenuTriggerItem value="fruits">
            Fruits
          </MenuTriggerItem>
          <Teleport to="body">
            <MenuContent>
              <MenuItem
                v-for="fruit in fruits"
                :key="fruit"
                :value="fruit"
              >
                <MenuItemText>{{ fruit }}</MenuItemText>
              </MenuItem>
            </MenuContent>
          </Teleport>
        </Menu>
      </MenuContent>
    </Menu>
  </div>
</template>
