// packages/vue/core/src/components/pagination/PaginationGoToTrigger.vue
<script setup lang="ts">
import type { PaginationGoToTriggerProps } from '.'
import { ark } from '@ark-ui/vue/factory'
import { inject } from 'vue'
import { PAGINATION_GO_TO_PROVIDE_KEY } from '.'

const props = defineProps<PaginationGoToTriggerProps>()
const { goInputPage } = inject(PAGINATION_GO_TO_PROVIDE_KEY, { goInputPage: () => {} })
</script>

<template>
  <ark.button
    v-bind="props"
    @click="() => goInputPage()"
  >
    <slot :go="goInputPage" />
  </ark.button>
</template>

// packages/react/core/src/components/pagination/PaginationGoToTrigger.tsx
import type { PaginationGoToTriggerProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { usePaginationGoTo } from './pagination-goto-context'

export function PaginationGoToTrigger({ children, ...props }: PaginationGoToTriggerProps) {
  const { goInputPage } = usePaginationGoTo()

  return (
    <ark.button type="button" {...props} onClick={() => goInputPage()}>
      {children}
    </ark.button>
  )
}

PaginationGoToTrigger.displayName = 'Pagination.GoToTrigger'
