// packages/vue/core/src/components/pagination/PaginationPageSize.vue
<script setup lang="ts">
import type { PaginationPageSizeProps } from '.'
import { usePaginationContext } from '@ark-ui/vue'
import { createListCollection } from '@ark-ui/vue/collection'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'
import { uniq } from 'es-toolkit'
import { computed, ref, watch } from 'vue'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../select'

const {
  class: propsClass,
  theme: propsTheme,
  sizes,
  placeholder,
  ui,
} = defineProps<PaginationPageSizeProps>()

const context = usePaginationContext()
const modelValue = ref([context.value.pageSize])
watch(modelValue, v => context.value.setPageSize(v[0]), { immediate: true })

const sizeItems = computed(() => {
  const list = uniq(sizes?.length ? sizes : [10, 20, 30, 50])
  return list.map(n => ({ label: String(n), value: n }))
})
const collection = computed(() => createListCollection({ items: sizeItems.value }))

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvPaginationPageSize')
</script>

<template>
  <div
    :class="crafts.root(cxc(ui?.root, propsClass))"
    data-scope="pagination"
    data-part="page-size"
  >
    <slot name="prefix" />
    <Select
      v-model="modelValue"
      :theme="theme"
      :collection="collection"
      :class="crafts.control(cxc(ui?.control))"
    >
      <SelectTrigger :class="crafts.trigger(cxc(ui?.trigger))">
        <SelectValue
          :class="crafts.value(cxc(ui?.value))"
          :placeholder="placeholder ?? 'Page size'"
        />
        <SelectIndicator />
      </SelectTrigger>
      <SelectContent :class="crafts.content(cxc(ui?.content))">
        <SelectItem
          v-for="item in collection.items"
          :key="item.value"
          :item="item"
          :class="crafts.item(cxc(ui?.item))"
        >
          {{ item.label }}
          <template #indicator>
            {{ "" }}
          </template>
        </SelectItem>
      </SelectContent>
    </Select>
    <slot name="suffix" />
  </div>
</template>

// packages/react/core/src/components/pagination/PaginationPageSize.tsx
import type { ResolvedTheme, ThemeProps } from '@raxium/react/providers/theme'
import type { PaginationPageSizeProps } from './props'
import { usePaginationContext } from '@ark-ui/react/pagination'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { uniq } from 'es-toolkit'
import { useMemo } from 'react'
import { createListCollection, Select } from '../select'

function tokensFromTheme(theme: ResolvedTheme): ThemeProps {
  return {
    size: theme.size,
    skin: theme.skin,
    surface: theme.surface,
    unstyled: theme.unstyled,
    bordered: theme.bordered,
  }
}

export function PaginationPageSize({
  className,
  theme: propsTheme,
  sizes,
  placeholder,
  prefix,
  suffix,
  ui,
}: PaginationPageSizeProps) {
  const context = usePaginationContext()
  const theme = useInheritedTheme(propsTheme)
  const crafts = useCraft(theme, 'tvPaginationPageSize')
  const selectTheme = useMemo(() => tokensFromTheme(theme), [theme])
  const items = useMemo(() => {
    const list = uniq(sizes?.length ? sizes : [10, 20, 30, 50])
    return list.map(n => ({ label: String(n), value: String(n) }))
  }, [sizes])
  const collection = useMemo(() => createListCollection({ items }), [items])

  return (
    <div
      className={crafts.root(cxc(ui?.root, className))}
      data-scope="pagination"
      data-part="page-size"
    >
      {prefix}
      <Select
        collection={collection}
        theme={selectTheme}
        className={crafts.control(cxc(ui?.control))}
        value={[String(context.pageSize)]}
        onValueChange={(details) => {
          const next = Number(details.value[0])
          if (Number.isFinite(next))
            context.setPageSize(next)
        }}
      >
        <Select.Trigger className={crafts.trigger(cxc(ui?.trigger))}>
          <Select.Value className={crafts.value(cxc(ui?.value))} placeholder={placeholder ?? 'Page size'} />
        </Select.Trigger>
        <Select.Content className={crafts.content(cxc(ui?.content))}>
          {items.map(item => (
            <Select.Item
              key={item.value}
              item={item}
              className={crafts.item(cxc(ui?.item))}
              indicator={<></>}
            >
              {item.label}
            </Select.Item>
          ))}
        </Select.Content>
      </Select>
      {suffix}
    </div>
  )
}

PaginationPageSize.displayName = 'Pagination.PageSize'
