// packages/vue/core/src/components/pagination/PaginationGoTo.vue
<script setup lang="ts">
import type { PaginationGoToProps } from '.'
import { usePaginationContext } from '@ark-ui/vue'
import { cxc } from '@raxium/themes/utils'
import { NumberInput } from '@raxium/vue/components/number-input'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'
import { provide, ref, watch } from 'vue'
import { PAGINATION_GO_TO_PROVIDE_KEY } from '.'

const { class: propsClass, theme: propsTheme, ui, widget } = defineProps<PaginationGoToProps>()

const context = usePaginationContext()
const innerValue = ref<string>(`${context.value.page}`)
watch(
  () => context.value.page,
  (p) => {
    innerValue.value = String(p)
  },
  { immediate: true },
)

function clampPage(page: string | number) {
  const nPage = Number(page)
  if (!Number.isFinite(nPage))
    return 1
  return Math.min(Math.max(Math.trunc(nPage), 1), Math.max(1, context.value.totalPages ?? 1))
}

function goInputPage() {
  const page = clampPage(innerValue.value)
  innerValue.value = String(page)
  context.value.setPage(page)
}

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvPaginationGoto')

provide(PAGINATION_GO_TO_PROVIDE_KEY, { goInputPage })
</script>

<template>
  <div
    :class="crafts.root(cxc(ui?.root, propsClass))"
    data-scope="pagination"
    data-part="goto"
  >
    <slot name="prefix" />
    <NumberInput
      v-bind="widget?.input"
      v-model="innerValue"
      :theme="theme"
      :class="crafts.input(cxc(widget?.input?.class, ui?.input))"
      :min="1"
      :max="context.totalPages"
      clamp-value-on-blur
      type="number"
      @keydown.enter.prevent="goInputPage"
    />
    <slot name="suffix" />
  </div>
</template>

// packages/react/core/src/components/pagination/PaginationGoTo.tsx
import type { KeyboardEvent } from 'react'
import type { ResolvedTheme, ThemeProps } from '@raxium/react/providers/theme'
import type { PaginationGoToProps } from './props'
import { usePaginationContext } from '@ark-ui/react/pagination'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { useEffect, useMemo, useState } from 'react'
import { NumberInput } from '../number-input'
import { PaginationGoToProvider } from './pagination-goto-context'

function tokensFromTheme(theme: ResolvedTheme): ThemeProps {
  return {
    size: theme.size,
    skin: theme.skin,
    surface: theme.surface,
    unstyled: theme.unstyled,
    bordered: theme.bordered,
  }
}

export function PaginationGoTo({
  className,
  theme: propsTheme,
  ui,
  widget,
  prefix,
  suffix,
  children,
}: PaginationGoToProps) {
  const context = usePaginationContext()
  const theme = useInheritedTheme(propsTheme)
  const crafts = useCraft(theme, 'tvPaginationGoto')
  const [innerValue, setInnerValue] = useState(String(context.page))
  const inputTheme = useMemo(() => tokensFromTheme(theme), [theme])

  useEffect(() => {
    setInnerValue(String(context.page))
  }, [context.page])

  function clampPage(page: string | number) {
    const parsed = Number(page)
    if (!Number.isFinite(parsed))
      return 1
    return Math.min(Math.max(Math.trunc(parsed), 1), Math.max(1, context.totalPages ?? 1))
  }

  function goInputPage() {
    const page = clampPage(innerValue)
    setInnerValue(String(page))
    context.setPage(page)
  }

  function onRootKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    if (event.key !== 'Enter')
      return
    if (!(event.target instanceof HTMLInputElement))
      return
    event.preventDefault()
    goInputPage()
  }

  return (
    <PaginationGoToProvider value={{ goInputPage }}>
      <div
        className={crafts.root(cxc(ui?.root, className))}
        data-scope="pagination"
        data-part="goto"
        onKeyDown={onRootKeyDown}
      >
        {prefix}
        <NumberInput
          {...widget?.input}
          theme={inputTheme}
          className={crafts.input(cxc(widget?.input?.className, ui?.input))}
          min={1}
          max={context.totalPages}
          clampValueOnBlur
          value={innerValue}
          onValueChange={details => setInnerValue(details.value)}
        />
        {suffix}
        {children}
      </div>
    </PaginationGoToProvider>
  )
}

PaginationGoTo.displayName = 'Pagination.GoTo'
