// packages/react/core/src/components/date-picker/examples/events.tsx
import type { DateValue } from '@ark-ui/react/date-picker'
import { useState } from 'react'
import { DatePicker } from '../index'

export function DatePickerEventsExample() {
  const [value, setValue] = useState<DateValue[]>([])
  const [open, setOpen] = useState(false)
  const [lines, setLines] = useState<string[]>([])

  function push(line: string) {
    setLines(prev => [line, ...prev].slice(0, 8))
  }

  const joined = lines.length ? lines.join('\n') : '（暂无事件）'

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="text-sm text-gray-cc">
        监听：onOpenChange / onViewChange / onValueChange
      </div>
      <div className="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
        <DatePicker
          value={value}
          open={open}
          onValueChange={(details) => {
            setValue(details.value)
            push(`onValueChange: ${details.value.map(v => String(v)).join(', ')}`)
          }}
          onOpenChange={(details) => {
            setOpen(details.open)
            push(`onOpenChange: open=${details.open}`)
          }}
          onViewChange={details => push(`onViewChange: view=${details.view}`)}
        >
          <DatePicker.Control>
            <DatePicker.Trigger className="rounded-md border border-gray-33 px-3 py-2 text-sm text-gray-ff">
              <DatePicker.ValueText placeholder="选择日期" />
            </DatePicker.Trigger>
          </DatePicker.Control>
          <DatePicker.Content>
            <DatePicker.DayView />
          </DatePicker.Content>
        </DatePicker>
      </div>
      <pre className="w-full max-w-[520px] whitespace-pre-wrap rounded-md bg-gray-0c p-3 text-xs text-gray-cc">
        {joined}
      </pre>
    </div>
  )
}

// packages/vue/core/src/components/date-picker/examples/events.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import {
  DatePicker,
  DatePickerContent,
  DatePickerControl,
  DatePickerDayView,
  DatePickerTrigger,
  DatePickerValueText,
} from '../index'

const value = ref([])
const open = ref(false)
const lines = ref<string[]>([])

function push(line: string) {
  lines.value = [line, ...lines.value].slice(0, 8)
}

const joined = computed(() => (lines.value.length ? lines.value.join('\n') : '（暂无事件）'))
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="text-sm text-gray-cc">
      监听：open-change / view-change / value-change / update:modelValue / update:open
    </div>

    <div class="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
      <DatePicker
        v-model="value"
        v-model:open="open"
        @open-change="(d) => push(`open-change: open=${d.open}`)"
        @view-change="(d) => push(`view-change: view=${d.view}`)"
        @value-change="(d) => push(`value-change: ${d.value.map((v) => String(v)).join(', ')}`)"
        @update:model-value="(v) => push(`update:modelValue: len=${v.length}`)"
        @update:open="(o) => push(`update:open: ${o}`)"
      >
        <DatePickerControl>
          <DatePickerTrigger class="rounded-md border border-gray-33 px-3 py-2 text-sm text-gray-ff">
            <DatePickerValueText placeholder="选择日期" />
          </DatePickerTrigger>
        </DatePickerControl>

        <DatePickerContent>
          <DatePickerDayView />
        </DatePickerContent>
      </DatePicker>
    </div>

    <pre class="w-full max-w-[520px] whitespace-pre-wrap rounded-md bg-gray-0c p-3 text-xs text-gray-cc">{{
      joined
    }}</pre>
  </div>
</template>
