// packages/react/core/src/components/date-picker/examples/range.tsx
import type { DateValue } from '@ark-ui/react/date-picker'
import { useState } from 'react'
import { DatePicker } from '../index'

export function DatePickerRangeExample() {
  const [value, setValue] = useState<DateValue[]>([])
  const text = value.length ? value.map(v => String(v)).join(' ~ ') : '(empty)'

  return (
    <div className="w-full flex flex-col gap-2">
      <div className="text-sm text-gray-cc">
        range:
        {' '}
        <span className="text-gray-ff">{text}</span>
      </div>
      <div className="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
        <DatePicker
          value={value}
          selectionMode="range"
          onValueChange={details => setValue(details.value)}
        >
          <DatePicker.Control>
            <DatePicker.Trigger className="rounded-md border border-gray-33 px-3 py-2 text-sm text-gray-ff">
              <DatePicker.ValueText placeholder="选择日期范围" />
            </DatePicker.Trigger>
          </DatePicker.Control>
          <DatePicker.Content>
            <DatePicker.DayView />
            <DatePicker.MonthView />
          </DatePicker.Content>
        </DatePicker>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/date-picker/examples/range.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import {
  DatePicker,
  DatePickerContent,
  DatePickerControl,
  DatePickerDayView,
  DatePickerMonthView,
  DatePickerTrigger,
  DatePickerValueText,
} from '../index'

const value = ref([])
const text = computed(() =>
  value.value.length ? value.value.map(v => String(v)).join(' ~ ') : '(empty)',
)
</script>

<template>
  <div class="w-full flex flex-col gap-2">
    <div class="text-sm text-gray-cc">
      range: <span class="text-gray-ff">{{ text }}</span>
    </div>

    <div class="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
      <DatePicker
        v-model="value"
        selection-mode="range"
      >
        <DatePickerControl>
          <DatePickerTrigger class="rounded-md border border-gray-33 px-3 py-2 text-sm text-gray-ff">
            <DatePickerValueText placeholder="选择日期范围" />
          </DatePickerTrigger>
        </DatePickerControl>

        <DatePickerContent>
          <DatePickerDayView />
          <DatePickerMonthView />
        </DatePickerContent>
      </DatePicker>
    </div>
  </div>
</template>
