// packages/react/core/src/components/skeleton/examples/shapes.tsx
import { Skeleton } from '../index'

export function SkeletonShapesExample() {
  return (
    <div className="w-full flex items-center gap-6">
      <div className="flex flex-col items-start gap-2">
        <div className="text-sm text-gray-cc">rect</div>
        <Skeleton className="h-14 w-56" shape="rect" />
      </div>
      <div className="flex flex-col items-start gap-2">
        <div className="text-sm text-gray-cc">circle</div>
        <Skeleton className="size-14" shape="circle" />
      </div>
    </div>
  )
}

// packages/vue/core/src/components/skeleton/examples/shapes.vue
<script setup lang="ts">
import { Skeleton } from '../index'
</script>

<template>
  <div class="w-full flex items-center gap-6">
    <div class="flex flex-col items-start gap-2">
      <div class="text-sm text-gray-cc">
        rect
      </div>
      <Skeleton class="h-14 w-56" shape="rect" />
    </div>

    <div class="flex flex-col items-start gap-2">
      <div class="text-sm text-gray-cc">
        circle
      </div>
      <Skeleton class="size-14" shape="circle" />
    </div>
  </div>
</template>
