// packages/react/core/src/components/skeleton/examples/variants.tsx
import { Skeleton } from '../index'

export function SkeletonVariantsExample() {
  return (
    <div className="w-full flex flex-col gap-4">
      <div className="flex flex-col gap-2">
        <div className="text-sm text-gray-cc">variant=pulse</div>
        <Skeleton className="h-4 w-64" variant="pulse" />
      </div>
      <div className="flex flex-col gap-2">
        <div className="text-sm text-gray-cc">variant=wave</div>
        <Skeleton className="h-4 w-64" variant="wave" />
      </div>
    </div>
  )
}

// packages/vue/core/src/components/skeleton/examples/variants.vue
<script setup lang="ts">
import { Skeleton } from '../index'
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="flex flex-col gap-2">
      <div class="text-sm text-gray-cc">
        variant=pulse
      </div>
      <Skeleton class="h-4 w-64" variant="pulse" />
    </div>

    <div class="flex flex-col gap-2">
      <div class="text-sm text-gray-cc">
        variant=wave
      </div>
      <Skeleton class="h-4 w-64" variant="wave" />
    </div>
  </div>
</template>
