// packages/vue/core/src/components/tabs/Tabs.vue
<script setup lang="ts">
import type { TabsRootEmits } from '@ark-ui/vue/tabs'
import type { TabsProps } from '.'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { Tabs, useTabs } from '@ark-ui/vue/tabs'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { computed, ref, useTemplateRef, watch } from 'vue'
import TabsProviderEx from './TabsProviderEx.vue'

const { class: propsClass, theme: propsTheme, craft, ...props } = defineProps<TabsProps>()
const emit = defineEmits<TabsRootEmits>()
const forwarded = useForwardProps(props)
const tabs = useTabs(forwarded, emit)
const tabsRoot = useTemplateRef('tabsRoot')

const triggerDomRevision = ref(0) // 单纯的计数器，用于触发dom变化后的computed/watchEffect
watch(
  () => tabsRoot.value?.$el as Element | undefined,
  (rootEl) => {
    if (!rootEl)
      return
    const observer = new MutationObserver(() => {
      triggerDomRevision.value++
    })
    observer.observe(rootEl, { childList: true, subtree: true })
    return () => observer.disconnect()
  },
  { flush: 'post', immediate: true },
)

const index = computed(() => {
  triggerDomRevision.value
  if (!tabsRoot.value?.$el)
    return 0
  const tabTriggerEls = Array.from(
    tabsRoot.value?.$el.querySelectorAll('[data-part="trigger"]'),
  ) as HTMLElement[]
  if (!tabTriggerEls.length)
    return 0
  const curIndex = tabTriggerEls.findIndex(
    el => el.getAttribute('data-value') === tabs.value.value,
  )
  return curIndex < 0 ? 0 : curIndex
})

// theme
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvTabs', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvTabs', () => ({
  orientation: forwarded.value.orientation ?? 'horizontal',
}))

// expose
defineExpose({ $api: tabs })
useForwardExpose()
</script>

<template>
  <Tabs.RootProvider
    ref="tabsRoot"
    :value="tabs"
    :lazy-mount="forwarded.lazyMount"
    :unmount-on-exit="forwarded.unmountOnExit"
    :class="crafts.root(cxc(propsClass))"
  >
    <TabsProviderEx
      :value="{
        index,
        orientation: forwarded.orientation ?? 'horizontal',
        domRevision: triggerDomRevision,
      }"
    >
      <slot />
    </TabsProviderEx>
  </Tabs.RootProvider>
</template>

// packages/react/core/src/components/tabs/Tabs.tsx
import type { TabsProps } from './props'
import type { TabsContextEx } from './tabs-context-ex'
import { Tabs as ArkTabs, useTabsContext } from '@ark-ui/react/tabs'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useCallback, useLayoutEffect, useMemo, useState } from 'react'
import { TabsContextExProvider } from './tabs-context-ex'

function TabsExBridge({
  rootEl,
  orientation,
  children,
}: {
  rootEl: HTMLDivElement | null
  orientation: TabsContextEx['orientation']
  children: TabsProps['children']
}) {
  const tabs = useTabsContext()
  const [domRevision, setDomRevision] = useState(0)

  useLayoutEffect(() => {
    if (!rootEl)
      return
    const observer = new MutationObserver(() => {
      setDomRevision(revision => revision + 1)
    })
    observer.observe(rootEl, { childList: true, subtree: true })
    return () => observer.disconnect()
  }, [rootEl])

  const index = useMemo(() => {
    void domRevision
    if (!rootEl)
      return 0
    const tabTriggerEls = Array.from(
      rootEl.querySelectorAll('[data-part="trigger"]'),
    ) as HTMLElement[]
    if (!tabTriggerEls.length)
      return 0
    const curIndex = tabTriggerEls.findIndex(
      el => el.getAttribute('data-value') === tabs.value,
    )
    return curIndex < 0 ? 0 : curIndex
  }, [domRevision, rootEl, tabs.value])

  const value = useMemo<TabsContextEx>(() => ({
    index,
    orientation,
    domRevision,
  }), [domRevision, index, orientation])

  return (
    <TabsContextExProvider value={value}>
      {children}
    </TabsContextExProvider>
  )
}

export const TabsRoot = forwardRef<HTMLDivElement, TabsProps>(
  ({ className, theme: propsTheme, craft, children, orientation = 'horizontal', ...props }, ref) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvTabs', craft)
    const crafts = useCraft(themed, 'tvTabs', { orientation })
    const [rootEl, setRootEl] = useState<HTMLDivElement | null>(null)

    const setRootRef = useCallback((node: HTMLDivElement | null) => {
      setRootEl(node)
      if (typeof ref === 'function')
        ref(node)
      else if (ref)
        ref.current = node
    }, [ref])

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkTabs.Root
          ref={setRootRef}
          className={crafts.root(cxc(className))}
          orientation={orientation}
          {...props}
        >
          <TabsExBridge rootEl={rootEl} orientation={orientation}>
            {children}
          </TabsExBridge>
        </ArkTabs.Root>
      </ProvideComponentTheme>
    )
  },
)

TabsRoot.displayName = 'Tabs'
