// packages/vue/core/src/components/tabs/TabsContent.vue
<script setup lang="ts">
import type { TabsContentProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Tabs } from '@ark-ui/vue/tabs'
import { cxc } from '@raxium/themes/utils'
import {
  useCraft,
  useInheritedTheme,
  useProvideStructuralComponentTheme,
} from '@raxium/vue/composables'
import { computed, ref, watch } from 'vue'
import { injectTabsContextEx } from './TabsProviderEx.vue'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<TabsContentProps>()
const forwarded = useForwardProps(props)
const contextEx = injectTabsContextEx()
const direction = ref(0)
watch(() => contextEx.value.index, (index, oldIndex) => {
  direction.value = index - oldIndex
})

const dataDirection = computed(() => {
  if (direction.value < 0)
    return 'prev'
  if (direction.value > 0)
    return 'next'
  return undefined
})

// theme
const theme = useInheritedTheme(() => propsTheme)
useProvideStructuralComponentTheme(theme, () => propsTheme)
const crafts = useCraft(theme, 'tvTabs')
</script>

<template>
  <Tabs.Content
    v-bind="forwarded"
    :class="crafts.content(cxc(propsClass))"
    :data-direction="dataDirection"
    :data-orientation="contextEx.orientation"
  >
    <slot />
  </Tabs.Content>
</template>

// packages/react/core/src/components/tabs/TabsContent.tsx
import type { TabsContentProps } from './props'
import { Tabs as ArkTabs } from '@ark-ui/react/tabs'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useLayoutEffect, useRef, useState } from 'react'
import { useTabsContextEx } from './tabs-context-ex'

export const TabsContent = forwardRef<HTMLDivElement, TabsContentProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const { index, orientation } = useTabsContextEx()
    const prevIndex = useRef(index)
    const [direction, setDirection] = useState(0)

    useLayoutEffect(() => {
      setDirection(index - prevIndex.current)
      prevIndex.current = index
    }, [index])

    const crafts = useCraft(theme, 'tvTabs')
    const dataDirection = direction < 0 ? 'prev' : direction > 0 ? 'next' : undefined

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <ArkTabs.Content
          ref={ref}
          className={crafts.content(cxc(className))}
          {...props}
          data-direction={dataDirection}
          data-orientation={orientation}
        >
          {children}
        </ArkTabs.Content>
      </ProvideStructuralComponentTheme>
    )
  },
)

TabsContent.displayName = 'Tabs.Content'
