// packages/vue/core/src/components/tabs/TabsIndicator.vue
<script setup lang="ts">
import type { TabsIndicatorProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Tabs } from '@ark-ui/vue/tabs'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'
import { injectTabsContextEx } from './TabsProviderEx.vue'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<TabsIndicatorProps>()
const forwarded = useForwardProps(props)
const contextEx = injectTabsContextEx()

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvTabs', () => ({
  orientation: contextEx.value.orientation,
}))
</script>

<template>
  <Tabs.Indicator
    v-bind="forwarded"
    :class="crafts.indicator(cxc(propsClass))"
  >
    <slot />
  </Tabs.Indicator>
</template>

// packages/react/core/src/components/tabs/TabsIndicator.tsx
import type { TabsIndicatorProps } from './props'
import { Tabs as ArkTabs } from '@ark-ui/react/tabs'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'
import { useTabsContextEx } from './tabs-context-ex'

export const TabsIndicator = forwardRef<HTMLDivElement, TabsIndicatorProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const { orientation } = useTabsContextEx()
    const crafts = useCraft(theme, 'tvTabs', { orientation })

    return (
      <ArkTabs.Indicator
        ref={ref}
        className={crafts.indicator(cxc(className))}
        {...props}
      >
        {children}
      </ArkTabs.Indicator>
    )
  },
)

TabsIndicator.displayName = 'Tabs.Indicator'
