// packages/react/core/src/components/switch/examples/with-label.tsx
import { Switch } from '../index'

export function SwitchWithLabelExample() {
  return (
    <div className="w-full flex flex-col gap-4">
      <Switch>
        <Switch.Label>Switch with label</Switch.Label>
      </Switch>
      <Switch theme={{ size: 'lg' }}>
        <Switch.Label className="font-medium">Large switch label</Switch.Label>
      </Switch>
    </div>
  )
}

// packages/vue/core/src/components/switch/examples/with-label.vue
<script setup lang="ts">
import { Switch, SwitchLabel } from '../index'
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <Switch>
      <SwitchLabel>Switch with label</SwitchLabel>
    </Switch>

    <Switch :theme="{ size: 'lg' }">
      <SwitchLabel class="font-medium">
        Large switch label
      </SwitchLabel>
    </Switch>
  </div>
</template>
