// packages/react/core/src/components/editable/examples/custom-controls.tsx
import { Check, Pencil, X } from 'lucide-react'
import { Button } from '../../button'
import { Editable, useEditableContext } from '../index'

function EditableControls() {
  const { editing } = useEditableContext()

  return (
    <Editable.Control className="flex items-center gap-2">
      {!editing && (
        <Editable.EditTrigger asChild>
          <Button className="p-0 size-5" variant="text">
            <Pencil className="size-3" />
          </Button>
        </Editable.EditTrigger>
      )}
      {editing && (
        <Editable.SubmitTrigger asChild>
          <Button className="p-0 size-5">
            <Check className="size-3" />
          </Button>
        </Editable.SubmitTrigger>
      )}
      {editing && (
        <Editable.CancelTrigger asChild>
          <Button variant="text" className="p-0 size-5">
            <X className="size-3" />
          </Button>
        </Editable.CancelTrigger>
      )}
    </Editable.Control>
  )
}

export function EditableCustomControlsExample() {
  return (
    <Editable
      placeholder="Edit me"
      className="flex gap-2"
      activationMode="none"
      suffix={<EditableControls />}
    >
      <Editable.Input clearable />
      <Editable.Preview />
    </Editable>
  )
}

// packages/vue/core/src/components/editable/examples/custom-controls.vue
<script setup lang="ts">
import { Check, Pencil, X } from '@lucide/vue'
import { Button } from '../../button'
import {
  Editable,
  EditableCancelTrigger,
  EditableControl,
  EditableEditTrigger,
  EditableInput,
  EditablePreview,
  EditableSubmitTrigger,
} from '../index'
</script>

<template>
  <Editable
    placeholder="Edit me"
    class="flex gap-2"
    activation-mode="none"
  >
    <EditableInput clearable />
    <EditablePreview />
    <template #suffix="{ editing }">
      <EditableControl class="flex items-center gap-2">
        <EditableEditTrigger
          v-if="!editing"
          as-child
        >
          <Button
            class="p-0 size-5"
            variant="text"
          >
            <Pencil class="size-3" />
          </Button>
        </EditableEditTrigger>
        <EditableSubmitTrigger
          v-if="editing"
          as-child
        >
          <Button class="p-0 size-5">
            <Check class="size-3" />
          </Button>
        </EditableSubmitTrigger>
        <EditableCancelTrigger
          v-if="editing"
          as-child
        >
          <Button
            variant="text"
            class="p-0 size-5"
          >
            <X class="size-3" />
          </Button>
        </EditableCancelTrigger>
      </EditableControl>
    </template>
  </Editable>
</template>
