// packages/react/core/src/components/editable/examples/states.tsx
import { useState } from 'react'
import { Editable } from '../index'

export function EditableStatesExample() {
  const [value, setValue] = useState('')

  return (
    <div className="w-full flex flex-col gap-4">
      <Editable
        value={value}
        placeholder="Empty value shows placeholder"
        onValueChange={details => setValue(details.value)}
      >
        <Editable.Input clearable />
        <Editable.Preview />
      </Editable>

      <Editable defaultValue="Default value" placeholder="Edit me" disabled>
        <Editable.Input clearable />
        <Editable.Preview />
      </Editable>

      <Editable defaultValue="Read only" placeholder="Edit me" readOnly>
        <Editable.Input clearable />
        <Editable.Preview />
      </Editable>
    </div>
  )
}

// packages/vue/core/src/components/editable/examples/states.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Editable, EditableInput, EditablePreview } from '../index'

const value = ref('')
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <Editable v-model="value" placeholder="Empty value shows placeholder" clearable>
      <EditableInput clearable />
      <EditablePreview />
    </Editable>

    <Editable default-value="Default value" placeholder="Edit me" disabled>
      <EditableInput clearable />
      <EditablePreview />
    </Editable>

    <Editable default-value="Read only" placeholder="Edit me" read-only>
      <EditableInput clearable />
      <EditablePreview />
    </Editable>
  </div>
</template>
