// packages/react/core/src/components/hover-card/HoverCardContent.tsx
import type { CSSProperties } from 'react'
import type { HoverCardContentProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { HoverCard as ArkHoverCard } from '@ark-ui/react/hover-card'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useTeleportedDepthOwner } from '@raxium/react/hooks/useDepth'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTeleportDetection } from '@raxium/react/hooks/useTeleportDetection'
import { useThemeAttrs } from '@raxium/react/hooks/useThemeAttrs'
import { cn, cxc } from '@raxium/themes/utils'
import { forwardRef, useMemo } from 'react'
import { splitHoverCardArrow } from './split-hover-card-arrow'

export const HoverCardContent = forwardRef<HTMLDivElement, HoverCardContentProps>(
  ({ className, theme: propsTheme, ui, children, ...props }, ref) => {
    const { isTeleported, setElementRef } = useTeleportDetection()
    const depth = useTeleportedDepthOwner({
      type: 'hover-card',
      active: isTeleported,
      fallbackZIndex: 'var(--z-popover, var(--z-index))',
    })
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvHoverCard')
    const themeAttrs = useThemeAttrs(theme)
    const { arrows, rest } = useMemo(() => splitHoverCardArrow(children), [children])

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <ArkHoverCard.Positioner
          ref={setElementRef}
          className={cn(ui?.positioner)}
          style={{ '--rui-z-index': isTeleported ? depth.zIndex : 'auto' } as CSSProperties}
        >
          <ArkHoverCard.Content
            ref={ref}
            className={crafts.content(cxc(ui?.content, className))}
            {...props}
            {...themeAttrs}
          >
            {arrows}
            <ark.div
              className={crafts.contentInner(cxc(ui?.inner))}
              {...themeAttrs}
            >
              {rest}
            </ark.div>
          </ArkHoverCard.Content>
        </ArkHoverCard.Positioner>
      </ProvideStructuralComponentTheme>
    )
  },
)

HoverCardContent.displayName = 'HoverCard.Content'

// packages/vue/core/src/components/hover-card/HoverCardContent.vue
<script setup lang="ts">
import type { HoverCardContentProps } from '.'
import { useForwardExpose } from '@ark-ui/vue'
import { HoverCard } from '@ark-ui/vue/hover-card'
import { useForwardProps } from '@ark-ui/vue/utils'
import { clsx, cxc } from '@raxium/themes/utils'
import {
  useCraft,
  useInheritedTheme,
  useProvideStructuralComponentTheme,
  useTeleportDetection,
  useTeleportedDepthOwner,
  useThemeAttrs,
} from '@raxium/vue/composables'
import {
  checkContextVNodePosition,
  excludeVNodesByName,
  findVNodeByName,
} from '@raxium/vue/utils/vnode'
import { computed, useSlots } from 'vue'

const { class: propsClass, theme: propsTheme, ui, ...props } = defineProps<HoverCardContentProps>()
const forwarded = useForwardProps<HoverCardContentProps, { asChild?: boolean }>(props)
const slots = useSlots()
const defaultSlots = computed(() => slots.default?.())
checkContextVNodePosition(defaultSlots.value, 'HoverCardContext', 'HoverCardContent')
const arrowNode = computed(() => findVNodeByName(defaultSlots.value, 'HoverCardArrow'))
const otherNodes = computed(() => excludeVNodesByName(defaultSlots.value, 'HoverCardArrow'))

// teleport detection
const { isTeleported, setElementRef: setPositionerRef } = useTeleportDetection()
const depth = useTeleportedDepthOwner({
  type: 'hover-card',
  active: isTeleported,
  fallbackZIndex: 'var(--z-popover, var(--z-index))',
})

// theme
const theme = useInheritedTheme(() => propsTheme)
useProvideStructuralComponentTheme(theme, () => propsTheme)
const crafts = useCraft(theme, 'tvHoverCard')
const themeAttrs = useThemeAttrs(theme)
const positionerStyle = computed(() => ({
  '--rui-z-index': isTeleported.value ? depth.zIndex.value : 'auto',
}))

// forward expose
const { forwardRef } = useForwardExpose()
</script>

<template>
  <HoverCard.Positioner
    :ref="setPositionerRef"
    :class="clsx(ui?.positioner)"
    :style="positionerStyle"
  >
    <HoverCard.Content
      v-bind="{ ...forwarded, ...themeAttrs }"
      :ref="forwardRef"
      :class="crafts.content(cxc(ui?.content, propsClass))"
    >
      <template v-if="arrowNode">
        <component :is="arrowNode" />
      </template>
      <div :class="crafts.contentInner(cxc(ui?.inner))" v-bind="themeAttrs">
        <template
          v-for="node in otherNodes"
          :key="node.key"
        >
          <component :is="node" />
        </template>
      </div>
    </HoverCard.Content>
  </HoverCard.Positioner>
</template>
