// packages/react/core/src/components/editable/EditableInput.tsx
import type { EditableInputProps } from './props'
import { Editable as ArkEditable, useEditableContext } from '@ark-ui/react/editable'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { useComposedRefs } from '@raxium/react/utils'
import { cxc } from '@raxium/themes/utils'
import { CircleX } from 'lucide-react'
import { forwardRef, useRef, useState } from 'react'

export const EditableInput = forwardRef<HTMLInputElement, EditableInputProps>(
  ({ className, theme: propsTheme, clearable, onFocus, onBlur, ...props }, forwardedRef) => {
    const context = useEditableContext()
    const inputRef = useRef<HTMLInputElement>(null)
    const ref = useComposedRefs(forwardedRef, inputRef)
    const [focused, setFocused] = useState(false)
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvEditableInput')
    const showClear = Boolean(clearable) && context.editing && !context.empty
    const dataState = focused ? 'focused' : 'idle'

    function onClear() {
      context.clearValue()
      setTimeout(() => {
        inputRef.current?.focus()
        setFocused(true)
      })
    }

    return (
      <ark.div
        className={crafts.root(cxc(!context.editing && 'hidden', className))}
        data-scope="editable"
        data-part="input-area"
        data-state={dataState}
      >
        <ArkEditable.Input
          ref={ref}
          className={crafts.input()}
          data-state={dataState}
          {...props}
          onFocus={(event) => {
            setFocused(true)
            onFocus?.(event)
          }}
          onBlur={(event) => {
            setFocused(false)
            onBlur?.(event)
          }}
        />
        {showClear && (
          clearable === true
            ? (
                <CircleX
                  data-scope="editable"
                  data-part="clear-button"
                  className={crafts.clearable()}
                  onPointerDown={(event) => {
                    event.stopPropagation()
                    onClear()
                  }}
                />
              )
            : (
                <span
                  data-scope="editable"
                  data-part="clear-button"
                  className={crafts.clearable()}
                  onPointerDown={(event) => {
                    event.stopPropagation()
                    onClear()
                  }}
                >
                  {clearable}
                </span>
              )
        )}
      </ark.div>
    )
  },
)

EditableInput.displayName = 'Editable.Input'

// packages/vue/core/src/components/editable/EditableInput.vue
<script setup lang="ts">
import type { EditableInputProps } from '.'
import { Editable, useEditableContext } from '@ark-ui/vue/editable'
import { ark } from '@ark-ui/vue/factory'
import { useForwardProps } from '@ark-ui/vue/utils'
import { CircleX } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { ref } from 'vue'

const {
  class: propsClass,
  theme: propsTheme,
  clearable,
  ...props
} = defineProps<EditableInputProps>()

const forwarded = useForwardProps(props)
const context = useEditableContext()
const inputRef = ref<{ $el: HTMLInputElement } | null>(null)

const isFocus = ref(false)
function onFocus() {
  isFocus.value = true
}
function onBlur() {
  isFocus.value = false
}

function onClear() {
  context.value.clearValue()
  // we reforcus on next microtask to avoid blur event
  setTimeout(() => {
    inputRef.value?.$el.focus()
    isFocus.value = true
  })
}

const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvEditableInput')
</script>

<template>
  <ark.div
    :class="
      crafts.root(cxc(!context.editing && 'hidden', propsClass))
    "
    data-scope="editable"
    data-part="input-area"
    :data-state="isFocus ? 'focused' : 'idle'"
  >
    <Editable.Input
      v-bind="forwarded"
      ref="inputRef"
      :class="crafts.input(cxc(propsClass))"
      :data-state="isFocus ? 'focused' : 'idle'"
      @focus="onFocus"
      @blur="onBlur"
    />
    <slot name="clearable">
      <CircleX
        v-if="clearable && context.editing && !context.empty"
        data-scope="editable"
        data-part="clear-button"
        :class="crafts.clearable(cxc(propsClass))"
        @pointerdown.stop="onClear"
      />
    </slot>
  </ark.div>
</template>
