// packages/react/core/src/components/editable/EditablePreview.tsx
import type { EditablePreviewProps } from './props'
import { Editable as ArkEditable } from '@ark-ui/react/editable'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const EditablePreview = forwardRef<HTMLSpanElement, EditablePreviewProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvEditable')

    return (
      <ArkEditable.Preview
        ref={ref}
        className={crafts.preview(cxc(className))}
        {...props}
      >
        {children}
      </ArkEditable.Preview>
    )
  },
)

EditablePreview.displayName = 'Editable.Preview'

// packages/vue/core/src/components/editable/EditablePreview.vue
<script setup lang="ts">
import type { EditablePreviewProps } from '.'
import { EditablePreview } from '@ark-ui/vue/editable'
import { useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<EditablePreviewProps>()
const forwarded = useForwardProps(props)

const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvEditable')
</script>

<template>
  <EditablePreview
    v-bind="forwarded"
    :class="crafts.preview(cxc(propsClass))"
  >
    <slot />
  </EditablePreview>
</template>
