// packages/react/core/src/components/slider/examples/controlled.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Slider } from '../index'

export function SliderControlledExample() {
  const [value, setValue] = useState([10])

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <Button variant="outlined" onClick={() => setValue([0])}>
          Set 0
        </Button>
        <Button variant="outlined" onClick={() => setValue([50])}>
          Set 50
        </Button>
        <Button variant="outlined" onClick={() => setValue([100])}>
          Set 100
        </Button>
        <span className="text-sm text-gray-ff">
          value:
          {' '}
          {value[0]}
        </span>
      </div>

      <Slider
        className="w-90"
        min={0}
        max={100}
        step={1}
        value={value}
        onValueChange={details => setValue(details.value)}
      >
        <Slider.TooltipThumb index={0} />
      </Slider>
    </div>
  )
}

// packages/vue/core/src/components/slider/examples/controlled.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import { Slider, SliderTooltipThumb } from '../index'

const value = ref([10])
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="flex items-center gap-2">
      <Button variant="outlined" @click="value = [0]">
        Set 0
      </Button>
      <Button variant="outlined" @click="value = [50]">
        Set 50
      </Button>
      <Button variant="outlined" @click="value = [100]">
        Set 100
      </Button>
      <span class="text-sm text-gray-ff">value: {{ value[0] }}</span>
    </div>

    <Slider v-model="value" class="w-90" :min="0" :max="100" :step="1">
      <SliderTooltipThumb :index="0" />
    </Slider>
  </div>
</template>
