// packages/react/core/src/components/slider/examples/markers-and-tooltips.tsx
import { useState } from 'react'
import { Slider } from '../index'

export function SliderMarkersAndTooltipsExample() {
  const [value, setValue] = useState([100])

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="text-sm text-gray-ff">
        value:
        {' '}
        {value[0]}
      </div>

      <div className="flex flex-col gap-40">
        <Slider
          className="w-90"
          theme={{ size: 'lg' }}
          min={0}
          max={100}
          step={1}
          value={value}
          onValueChange={details => setValue(details.value)}
          suffix={(
            <Slider.MarkerGroup>
              <Slider.Marker value={0} />
              <Slider.Marker value={25} />
              <Slider.TooltipMarker value={50} theme={{ surface: 'razer' }} content="Mid: 50" />
              <Slider.Marker value={75} />
              <Slider.Marker value={100} />
            </Slider.MarkerGroup>
          )}
        >
          <Slider.TooltipThumb
            index={0}
            theme={{ surface: 'razer' }}
            positioning={{ placement: 'top' }}
          />
        </Slider>

        <Slider
          className="w-full"
          theme={{ size: 'lg' }}
          value={value}
          onValueChange={details => setValue(details.value)}
          suffix={(
            <Slider.MarkerGroup>
              <Slider.Marker value={10} interactive />
              <Slider.TooltipMarker value={20} theme={{ surface: 'razer' }} interactive />
              <Slider.TooltipMarker
                value={50}
                theme={{ surface: value[0] >= 50 ? 'razer' : 'dark' }}
                interactive
              />
              <Slider.TooltipMarker value={100} />
            </Slider.MarkerGroup>
          )}
        >
          <Slider.TooltipThumb
            index={0}
            open={() => true}
            positioning={{ placement: 'top' }}
          />
        </Slider>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/slider/examples/markers-and-tooltips.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  Slider,
  SliderMarker,
  SliderMarkerGroup,
  SliderTooltipMarker,
  SliderTooltipThumb,
} from '../index'

const value = ref([100])
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="text-sm text-gray-ff">
      value: {{ value[0] }}
    </div>

    <div class="flex flex-col gap-40">
      <Slider
        v-model="value"
        class="w-90"
        :theme="{ size: 'lg' }"
        :min="0"
        :max="100"
        :step="1"
      >
        <SliderTooltipThumb
          :index="0"
          :theme="{ surface: 'razer' }"
          :positioning="{ placement: 'top' }"
        />
        <template #suffix>
          <SliderMarkerGroup>
            <SliderMarker :value="0" />
            <SliderMarker :value="25" />
            <SliderTooltipMarker
              :value="50"
              :theme="{ surface: 'razer' }"
            >
              <template #content>
                Mid: 50
              </template>
            </SliderTooltipMarker>
            <SliderMarker :value="75" />
            <SliderMarker :value="100" />
          </SliderMarkerGroup>
        </template>
      </Slider>

      <Slider
        v-model="value"
        class="w-full"
        :theme="{ size: 'lg' }"
      >
        <SliderTooltipThumb
          :index="0"
          :open="() => true"
          :positioning="{
            placement: 'top',
          }"
        />
        <template #suffix>
          <SliderMarkerGroup>
            <SliderMarker :value="10" interactive />
            <SliderTooltipMarker
              :value="20"
              :theme="{ surface: 'razer' }"
              interactive
            />
            <SliderTooltipMarker
              :value="50"
              :theme="{ surface: value[0] >= 50 ? 'razer' : 'dark' }"
              interactive
            />
            <SliderTooltipMarker :value="100" />
          </SliderMarkerGroup>
        </template>
      </Slider>
    </div>
  </div>
</template>
