// packages/react/core/src/components/input/Input.tsx
import type { InputProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useStableId } from '@raxium/react/hooks/useStableId'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { cxc } from '@raxium/themes/utils'
import { CircleX } from 'lucide-react'
import { forwardRef, useState } from 'react'

type InputState = 'disabled' | 'readonly' | 'focused' | 'blur'

export const Input = forwardRef<HTMLInputElement, InputProps>(
  (
    {
      id,
      className,
      theme: propsTheme,
      craft,
      clearable = false,
      ui,
      disabled,
      readOnly,
      placeholder,
      defaultValue,
      value: valueProp,
      maxLength,
      minLength,
      type,
      prefix,
      suffix,
      onValueChange,
      onClear,
      onChange,
      onFocus,
      onBlur,
      ...props
    },
    forwardedRef,
  ) => {
    const generatedId = useStableId('input')
    const theme = useTheme(propsTheme)
    const crafts = useCraft(theme, 'tvInput', undefined, craft)
    const isControlled = valueProp !== undefined
    const [uncontrolled, setUncontrolled] = useState(defaultValue ?? '')
    const [focused, setFocused] = useState(false)
    const value = isControlled ? (valueProp ?? '') : uncontrolled
    const inputState: InputState = disabled
      ? 'disabled'
      : readOnly
        ? 'readonly'
        : focused
          ? 'focused'
          : 'blur'
    const showClear = inputState === 'focused' && clearable && Boolean(value)

    function commit(next: string) {
      if (!isControlled)
        setUncontrolled(next)
      onValueChange?.(next)
    }

    return (
      <ark.div
        className={crafts.root(cxc(ui?.root, className))}
        data-state={inputState}
      >
        {prefix}
        <ark.input
          ref={forwardedRef}
          id={id ?? generatedId}
          className={crafts.input(cxc(ui?.input))}
          data-state={inputState}
          placeholder={placeholder}
          disabled={disabled ? true : undefined}
          readOnly={readOnly ? true : undefined}
          maxLength={maxLength}
          minLength={minLength}
          type={type}
          value={value}
          {...props}
          onChange={(event) => {
            commit(event.target.value)
            onChange?.(event)
          }}
          onFocus={(event) => {
            setFocused(true)
            onFocus?.(event)
          }}
          onBlur={(event) => {
            window.setTimeout(() => {
              onBlur?.(event)
              setFocused(false)
            })
          }}
        />
        {showClear && (
          <ark.div
            className={crafts.clearable(cxc(ui?.clearable))}
            onMouseDown={(event) => {
              event.stopPropagation()
              commit('')
              onClear?.(event, '')
            }}
          >
            <CircleX />
          </ark.div>
        )}
        {suffix}
      </ark.div>
    )
  },
)

Input.displayName = 'Input'

// packages/vue/core/src/components/input/Input.vue
<script setup lang="ts">
import type { InputProps } from '.'
import { ark } from '@ark-ui/vue/factory'
import { clsx } from '@raxium/themes/utils'
import { useTheme } from '@raxium/vue/composables/useTheme'
import { useVModel } from '@vueuse/core'
import { CircleX } from 'lucide-vue-next'
import { computed, ref, useId, useTemplateRef } from 'vue'

const {
  id,
  class: propsClass,
  theme: propsTheme,
  clearable = false,
  ui,
  disabled,
  readonly,
  defaultValue,
  placeholder,
  maxlength,
  ...props
} = defineProps<InputProps>()
const emits = defineEmits<{
  'update:modelValue': [value: string]
  'focus': [e: FocusEvent]
  'blur': [e: FocusEvent]
  'input': [e: InputEvent, value: string | undefined]
  'change': [e: Event, value: string | undefined]
  'clear': [e: Event, value: string | undefined]
  'beforeInput': [e: InputEvent, value: string | undefined]
  'compositionStart': [e: CompositionEvent]
  'compositionEnd': [e: CompositionEvent]
}>()

const inputId = useId()
const modelValue = useVModel(props, 'modelValue', emits, {
  passive: true,
  defaultValue,
})

const isFocus = ref(false)
const inputState = computed(() => {
  if (disabled)
    return 'disabled'
  if (readonly)
    return 'readonly'
  return isFocus.value ? 'focused' : 'blur'
})

const inputRef = useTemplateRef<HTMLInputElement | null>('input')
const rejectBlur = ref(false)

function onFocus(event: FocusEvent) {
  isFocus.value = true
  emits('focus', event)
}

function onBlur(event: FocusEvent) {
  setTimeout(() => {
    emits('blur', event)
    if (rejectBlur.value) {
      rejectBlur.value = false
      return
    }
    isFocus.value = false
  })
}

function onClear() {
  rejectBlur.value = true
  inputRef.value?.focus()
  modelValue.value = ''
  emits('clear', new CustomEvent('clear'), modelValue.value)
}

// theme
const theme = useTheme(() => propsTheme)
const crafts = computed(() => theme.value.crafts.tvInput())
</script>

<template>
  <ark.div
    :as-child="false"
    :class="crafts.root({ class: clsx(ui?.root, propsClass), ...theme })"
    :data-state="inputState"
  >
    <slot name="prefix" />
    <input
      :id="id ?? `input:${inputId}`"
      ref="input"
      v-model="modelValue"
      :class="crafts.input({ class: clsx(ui?.input), ...theme })"
      :placeholder="placeholder"
      :data-state="inputState"
      :disabled="disabled ? true : undefined"
      :readonly="readonly ? true : undefined"
      :maxlength="maxlength"
      @focus="onFocus"
      @blur="onBlur"
      @input="emits('input', $event, modelValue)"
      @change="emits('change', $event, modelValue)"
      @beforeinput="emits('beforeInput', $event, modelValue)"
      @compositionstart="emits('compositionStart', $event)"
      @compositionend="emits('compositionEnd', $event)"
    >
    <ark.div
      v-if="inputState === 'focused' && clearable && modelValue"
      :class="crafts.clearable({ class: clsx(ui?.clearable), ...theme })"
      @mousedown.stop="onClear"
    >
      <CircleX />
    </ark.div>
    <slot name="suffix" />
  </ark.div>
</template>
