// packages/react/core/src/components/input/examples/prefix-suffix-and-ui.tsx
import { Icon } from '../../icon'
import { Input } from '../index'

export function InputPrefixSuffixAndUiExample() {
  return (
    <div className="w-full flex flex-col gap-3">
      <Input
        className="w-70"
        placeholder="Search..."
        prefix={<Icon icon="lucide:search" className="text-gray-cc" />}
        suffix={<Icon icon="lucide:corner-down-left" className="text-gray-55" />}
        ui={{ root: 'border-rz-green', input: 'text-gray-ff' }}
      />
      <Input
        className="w-70"
        placeholder="Clearable with custom clear icon size"
        clearable
        prefix={<Icon icon="lucide:mail" className="text-gray-cc" />}
        ui={{ clearable: 'text-rz-green' }}
      />
    </div>
  )
}

// packages/vue/core/src/components/input/examples/prefix-suffix-and-ui.vue
<script setup lang="ts">
import { Icon } from '../../icon'
import { Input } from '../index'
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <Input
      class="w-70"
      placeholder="Search..."
      :ui="{ root: 'border-rz-green', input: 'text-gray-ff' }"
    >
      <template #prefix>
        <Icon
          icon="lucide:search"
          class="text-gray-cc"
        />
      </template>
      <template #suffix>
        <Icon
          icon="lucide:corner-down-left"
          class="text-gray-55"
        />
      </template>
    </Input>

    <Input
      class="w-70"
      placeholder="Clearable with custom clear icon size"
      clearable
      :ui="{ clearable: 'text-rz-green' }"
    >
      <template #prefix>
        <Icon
          icon="lucide:mail"
          class="text-gray-cc"
        />
      </template>
    </Input>
  </div>
</template>
