// packages/vue/core/src/components/menu/examples/checkbox.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { computed, ref } from 'vue'
import { Button } from '../../button'
import { Menu, MenuCheckboxItem, MenuContent, MenuItemText, MenuTrigger } from '../index'

const items = Array.from({ length: 6 }, () => fakerEN.food.vegetable())
const checked = ref<string[]>([])
const label = computed(() => checked.value.length ? `(${checked.value.length}) selected` : 'none')

function toggle(value: string, isChecked: boolean) {
  checked.value = isChecked
    ? Array.from(new Set([...checked.value, value]))
    : checked.value.filter(v => v !== value)
}
</script>

<template>
  <div class="w-full flex items-center gap-4">
    <span class="text-sm text-gray-ff">Checked: {{ label }}</span>

    <Menu>
      <MenuTrigger as-child>
        <Button>Menu Checkbox</Button>
      </MenuTrigger>
      <MenuContent>
        <MenuCheckboxItem
          v-for="value in items"
          :key="value"
          :value="value"
          :close-on-select="false"
          :checked="checked.includes(value)"
          @update:checked="(val) => toggle(value, val)"
        >
          <MenuItemText>{{ value }}</MenuItemText>
        </MenuCheckboxItem>
      </MenuContent>
    </Menu>
  </div>
</template>

// packages/react/core/src/components/menu/examples/checkbox.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Menu } from '../index'

const items = ['Carrot', 'Broccoli', 'Spinach', 'Kale', 'Celery', 'Onion']

export function MenuCheckboxExample() {
  const [checked, setChecked] = useState<string[]>([])
  const label = checked.length ? `(${checked.length}) selected` : 'none'

  function toggle(value: string, isChecked: boolean) {
    setChecked(current =>
      isChecked
        ? Array.from(new Set([...current, value]))
        : current.filter(item => item !== value),
    )
  }

  return (
    <div className="w-full flex items-center gap-4">
      <span className="text-sm text-gray-ff">
        Checked:
        {' '}
        {label}
      </span>

      <Menu>
        <Menu.Trigger asChild>
          <Button>Menu Checkbox</Button>
        </Menu.Trigger>
        <Menu.Content>
          {items.map(value => (
            <Menu.CheckboxItem
              key={value}
              value={value}
              closeOnSelect={false}
              checked={checked.includes(value)}
              onCheckedChange={next => toggle(value, next)}
            >
              <Menu.ItemText>{value}</Menu.ItemText>
            </Menu.CheckboxItem>
          ))}
        </Menu.Content>
      </Menu>
    </div>
  )
}
