// packages/vue/core/src/components/menu/examples/context-trigger.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { ref } from 'vue'
import {
  Menu,
  MenuContent,
  MenuContextTrigger,
  MenuItem,
  MenuItemText,
} from '../index'

const items = Array.from({ length: 6 }, () => fakerEN.hacker.verb())
const selected = ref<string | undefined>(undefined)
</script>

<template>
  <div class="w-full flex items-center gap-4">
    <span class="text-sm text-gray-ff">Selected: {{ selected }}</span>

    <Menu @select="selected = $event.value">
      <MenuContextTrigger as-child>
        <div class="w-80 h-24 border border-gray-55 rounded flex items-center justify-center text-sm text-gray-ff select-none">
          Right click here
        </div>
      </MenuContextTrigger>
      <MenuContent>
        <MenuItem
          v-for="value in items"
          :key="value"
          :value="value"
        >
          <MenuItemText>{{ value }}</MenuItemText>
        </MenuItem>
      </MenuContent>
    </Menu>
  </div>
</template>

// packages/react/core/src/components/menu/examples/context-trigger.tsx
import { useState } from 'react'
import { Menu } from '../index'

const items = ['compile', 'refactor', 'deploy', 'debug', 'patch', 'ship']

export function MenuContextTriggerExample() {
  const [selected, setSelected] = useState<string | undefined>()

  return (
    <div className="w-full flex items-center gap-4">
      <span className="text-sm text-gray-ff">
        Selected:
        {' '}
        {selected}
      </span>

      <Menu onSelect={details => setSelected(details.value)}>
        <Menu.ContextTrigger asChild>
          <div className="w-80 h-24 border border-gray-55 rounded flex items-center justify-center text-sm text-gray-ff select-none">
            Right click here
          </div>
        </Menu.ContextTrigger>
        <Menu.Content>
          {items.map(value => (
            <Menu.Item key={value} value={value}>
              <Menu.ItemText>{value}</Menu.ItemText>
            </Menu.Item>
          ))}
        </Menu.Content>
      </Menu>
    </div>
  )
}
