// packages/vue/core/src/components/menu/examples/controlled-open.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import { Menu, MenuContent, MenuItem, MenuItemText, MenuTrigger } from '../index'

const open = ref(false)
const highlightedValue = ref<string>()
</script>

<template>
  <div class="w-full flex items-center gap-4">
    <div class="flex items-center gap-3">
      <Button @click="open = !open">
        Toggle open: {{ open }}
      </Button>
      <span class="text-sm text-gray-ff">highlighted: {{ highlightedValue ?? 'null' }}</span>
    </div>

    <Menu
      v-model:open="open"
      v-model:highlighted-value="highlightedValue"
      :close-on-select="false"
      :loop-focus="true"
      :typeahead="true"
    >
      <MenuTrigger as-child>
        <Button variant="outlined">
          Controlled Menu
        </Button>
      </MenuTrigger>
      <MenuContent>
        <MenuItem value="copy">
          <MenuItemText>Copy</MenuItemText>
        </MenuItem>
        <MenuItem value="paste">
          <MenuItemText>Paste</MenuItemText>
        </MenuItem>
        <MenuItem value="delete" :disabled="true">
          <MenuItemText>Delete (disabled)</MenuItemText>
        </MenuItem>
      </MenuContent>
    </Menu>
  </div>
</template>

// packages/react/core/src/components/menu/examples/controlled-open.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Menu } from '../index'

export function MenuControlledOpenExample() {
  const [open, setOpen] = useState(false)
  const [highlightedValue, setHighlightedValue] = useState<string | undefined>()

  return (
    <div className="w-full flex items-center gap-4">
      <div className="flex items-center gap-3">
        <Button onClick={() => setOpen(current => !current)}>
          Toggle open:
          {' '}
          {String(open)}
        </Button>
        <span className="text-sm text-gray-ff">
          highlighted:
          {' '}
          {highlightedValue ?? 'null'}
        </span>
      </div>

      <Menu
        open={open}
        highlightedValue={highlightedValue}
        closeOnSelect={false}
        loopFocus
        typeahead
        onOpenChange={details => setOpen(details.open)}
        onHighlightChange={details => setHighlightedValue(details.highlightedValue ?? undefined)}
      >
        <Menu.Trigger asChild>
          <Button variant="outlined">
            Controlled Menu
          </Button>
        </Menu.Trigger>
        <Menu.Content>
          <Menu.Item value="copy">
            <Menu.ItemText>Copy</Menu.ItemText>
          </Menu.Item>
          <Menu.Item value="paste">
            <Menu.ItemText>Paste</Menu.ItemText>
          </Menu.Item>
          <Menu.Item value="delete" disabled>
            <Menu.ItemText>Delete (disabled)</Menu.ItemText>
          </Menu.Item>
        </Menu.Content>
      </Menu>
    </div>
  )
}
