// packages/vue/core/src/components/menu/examples/radio.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { ref } from 'vue'
import { Button } from '../../button'
import {
  Menu,
  MenuContent,
  MenuItemText,
  MenuRadioItem,
  MenuRadioItemGroup,
  MenuTrigger,
} from '../index'

const items = Array.from({ length: 6 }, () => fakerEN.food.vegetable())
const selected = ref<string | undefined>(items[0])
</script>

<template>
  <div class="w-full flex items-center gap-4">
    <span class="text-sm text-gray-ff">Selected: {{ selected }}</span>

    <Menu>
      <MenuTrigger as-child>
        <Button>Menu Radio</Button>
      </MenuTrigger>
      <MenuContent>
        <MenuRadioItemGroup v-model="selected">
          <MenuRadioItem
            v-for="(value, index) in items"
            :key="value"
            :value="value"
            :close-on-select="false"
            :variant="index % 2 === 0 ? 'default' : 'checkbox'"
          >
            <MenuItemText>{{ value }}</MenuItemText>
          </MenuRadioItem>
        </MenuRadioItemGroup>
      </MenuContent>
    </Menu>
  </div>
</template>

// packages/react/core/src/components/menu/examples/radio.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Menu } from '../index'

const items = ['Carrot', 'Broccoli', 'Spinach', 'Kale', 'Celery', 'Onion']

export function MenuRadioExample() {
  const [selected, setSelected] = useState<string | undefined>(items[0])

  return (
    <div className="w-full flex items-center gap-4">
      <span className="text-sm text-gray-ff">
        Selected:
        {' '}
        {selected}
      </span>

      <Menu>
        <Menu.Trigger asChild>
          <Button>Menu Radio</Button>
        </Menu.Trigger>
        <Menu.Content>
          <Menu.RadioItemGroup
            value={selected}
            onValueChange={details => setSelected(details.value)}
          >
            {items.map((value, index) => (
              <Menu.RadioItem
                key={value}
                value={value}
                closeOnSelect={false}
                variant={index % 2 === 0 ? 'default' : 'checkbox'}
              >
                <Menu.ItemText>{value}</Menu.ItemText>
              </Menu.RadioItem>
            ))}
          </Menu.RadioItemGroup>
        </Menu.Content>
      </Menu>
    </div>
  )
}
