// packages/react/core/src/components/floating-panel/examples/initial-state.tsx
import { Button } from '../../button'
import { FloatingPanel } from '../index'

export function FloatingPanelInitialStateExample() {
  return (
    <FloatingPanel minSize={{ width: 360, height: 240 }} opacity={60} pinned>
      <FloatingPanel.Trigger asChild>
        <Button className="w-fit">Open FloatingPanel</Button>
      </FloatingPanel.Trigger>
      <FloatingPanel.Content>
        <FloatingPanel.Header
          control={(
            <>
              <FloatingPanel.PinTrigger />
              <FloatingPanel.CloseTrigger />
            </>
          )}
        >
          Initial state
        </FloatingPanel.Header>
        <div className="p-3 space-y-2">
          <div>Start with pinned = true, opacity = 60.</div>
          <div className="text-sm opacity-70">When pinned, dragging is disabled.</div>
        </div>
      </FloatingPanel.Content>
    </FloatingPanel>
  )
}

// packages/vue/core/src/components/floating-panel/examples/initial-state.vue
<script setup lang="ts">
import { Button } from '../../button'
import {
  FloatingPanel,
  FloatingPanelCloseTrigger,
  FloatingPanelContent,
  FloatingPanelHeader,
  FloatingPanelPinTrigger,
  FloatingPanelTrigger,
} from '../index'
</script>

<template>
  <FloatingPanel
    :min-size="{ width: 360, height: 240 }"
    :opacity="60"
    :pinned="true"
  >
    <FloatingPanelTrigger as-child>
      <Button class="w-fit">
        Open FloatingPanel
      </Button>
    </FloatingPanelTrigger>

    <FloatingPanelContent>
      <FloatingPanelHeader>
        Initial state
        <template #control>
          <FloatingPanelPinTrigger />
          <FloatingPanelCloseTrigger />
        </template>
      </FloatingPanelHeader>

      <div class="p-3 space-y-2">
        <div>Start with pinned = true, opacity = 60.</div>
        <div class="text-sm opacity-70">
          When pinned, dragging is disabled.
        </div>
      </div>
    </FloatingPanelContent>
  </FloatingPanel>
</template>
