// packages/react/core/src/components/dialog/examples/footer-widget.tsx
import { Button } from '../../button'
import { Dialog } from '../index'

export function DialogFooterWidgetExample() {
  return (
    <Dialog>
      <Dialog.Trigger asChild>
        <Button variant="outlined">Footer widget props</Button>
      </Dialog.Trigger>
      <Dialog.Content className="w-120">
        <Dialog.Header>Customize footer buttons</Dialog.Header>
        <Dialog.Body>Footer widget maps onto Button props plus text.</Dialog.Body>
        <Dialog.Footer
          widget={{
            cancel: { text: 'No', variant: 'text' },
            ok: { text: 'Yes', variant: 'solid' },
          }}
          ui={{
            cancel: 'text-gray-ff',
            ok: 'bg-rz-green text-black',
          }}
        />
      </Dialog.Content>
    </Dialog>
  )
}

// packages/vue/core/src/components/dialog/examples/footer-widget.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { Button } from '../../button'
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTrigger,
} from '../index'

const content = fakerEN.lorem.sentences(2)
</script>

<template>
  <Dialog>
    <DialogTrigger as-child>
      <Button variant="outlined">
        Footer widget props
      </Button>
    </DialogTrigger>
    <DialogContent class="w-120">
      <DialogHeader> Customize footer buttons </DialogHeader>
      <DialogBody>
        {{ content }}
      </DialogBody>
      <DialogFooter
        :widget="{
          cancel: { text: 'No', variant: 'text' },
          ok: { text: 'Yes', variant: 'normal' },
        }"
        :ui="{
          cancel: 'text-gray-ff',
          ok: 'bg-rz-green text-black',
        }"
      />
    </DialogContent>
  </Dialog>
</template>
