// packages/react/core/src/components/dialog/examples/variants.tsx
import { THEME_SIZE } from '@raxium/shared/constant'
import { Button } from '../../button'
import { Dialog } from '../index'

const body = 'Dialog body copy for size variants. The grid and footer spacing follow theme.size.'

export function DialogVariantsExample() {
  return (
    <div className="w-full flex flex-wrap items-center gap-4">
      {THEME_SIZE.map(size => (
        <Dialog key={size} theme={{ size }}>
          <Dialog.Trigger asChild>
            <Button theme={{ size }} variant="outlined">{size}</Button>
          </Dialog.Trigger>
          <Dialog.Content className="w-110">
            <Dialog.Header>
              {size}
              {' '}
              Dialog
            </Dialog.Header>
            <Dialog.Body>{body}</Dialog.Body>
            <Dialog.Footer />
          </Dialog.Content>
        </Dialog>
      ))}
    </div>
  )
}

// packages/vue/core/src/components/dialog/examples/variants.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { THEME_SIZE } from '@raxium/shared/constant'
import { Button } from '../../button'
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTrigger,
} from '../index'

const content = fakerEN.lorem.sentences(3)
</script>

<template>
  <div class="w-full flex flex-wrap items-center gap-4">
    <Dialog
      v-for="size in THEME_SIZE"
      :key="size"
      :theme="{ size }"
    >
      <DialogTrigger as-child>
        <Button :theme="{ size }" variant="outlined">
          {{ size }}
        </Button>
      </DialogTrigger>
      <DialogContent class="w-110">
        <DialogHeader>{{ size }} Dialog</DialogHeader>
        <DialogBody>{{ content }}</DialogBody>
        <DialogFooter />
      </DialogContent>
    </Dialog>
  </div>
</template>
