// packages/react/core/src/components/menu/examples/controlled-open.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Menu } from '../index'

export function MenuControlledOpenExample() {
  const [open, setOpen] = useState(false)
  const [highlightedValue, setHighlightedValue] = useState<string | undefined>()

  return (
    <div className="w-full flex items-center gap-4">
      <div className="flex items-center gap-3">
        <Button onClick={() => setOpen(current => !current)}>
          Toggle open:
          {' '}
          {String(open)}
        </Button>
        <span className="text-sm text-gray-ff">
          highlighted:
          {' '}
          {highlightedValue ?? 'null'}
        </span>
      </div>

      <Menu
        open={open}
        highlightedValue={highlightedValue}
        closeOnSelect={false}
        loopFocus
        typeahead
        onOpenChange={details => setOpen(details.open)}
        onHighlightChange={details => setHighlightedValue(details.highlightedValue ?? undefined)}
      >
        <Menu.Trigger asChild>
          <Button variant="outlined">
            Controlled Menu
          </Button>
        </Menu.Trigger>
        <Menu.Content>
          <Menu.Item value="copy">
            <Menu.ItemText>Copy</Menu.ItemText>
          </Menu.Item>
          <Menu.Item value="paste">
            <Menu.ItemText>Paste</Menu.ItemText>
          </Menu.Item>
          <Menu.Item value="delete" disabled>
            <Menu.ItemText>Delete (disabled)</Menu.ItemText>
          </Menu.Item>
        </Menu.Content>
      </Menu>
    </div>
  )
}

// packages/vue/core/src/components/popover/examples/controlled-open.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import {
  Popover,
  PopoverArrow,
  PopoverClose,
  PopoverContent,
  PopoverTrigger,
} from '../index'

const open = ref(false)
</script>

<template>
  <div class="w-full flex items-center gap-4">
    <Button @click="open = !open">
      Toggle open: {{ open }}
    </Button>

    <Popover v-model:open="open" :positioning="{ placement: 'bottom-start' }">
      <PopoverTrigger as-child>
        <Button variant="outlined">
          Controlled Popover
        </Button>
      </PopoverTrigger>
      <PopoverContent>
        <PopoverArrow />
        <div class="flex flex-col gap-2">
          <PopoverClose />
          <div class="text-sm text-gray-ff">
            Controlled via v-model:open
          </div>
        </div>
      </PopoverContent>
    </Popover>
  </div>
</template>
