// packages/vue/core/src/components/floating-panel/FloatingPanelStageTrigger.vue
<script setup lang="ts">
import type { FloatingPanelStageTriggerProps } from '.'
import { FloatingPanel, useForwardProps } from '@ark-ui/vue'
import { Minus, Square, SquareArrowOutDownLeft } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { computed, h } from 'vue'

const {
  class: propsClass,
  theme: propsTheme,
  stage,
  ...props
} = defineProps<FloatingPanelStageTriggerProps>()
const forwarded = useForwardProps(props)

const stageComponent = computed(() => {
  switch (stage) {
    case 'minimized':
      return h(Minus)
    case 'maximized':
      return h(Square)
    case 'default':
    default:
      return h(SquareArrowOutDownLeft)
  }
})

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvFloatingPanel')
</script>

<template>
  <FloatingPanel.StageTrigger
    v-bind="forwarded"
    :stage="stage"
    :class="crafts.trigger(cxc(propsClass))"
  >
    <slot>
      <component :is="stageComponent" />
    </slot>
  </FloatingPanel.StageTrigger>
</template>

// packages/react/core/src/components/floating-panel/FloatingPanelStageTrigger.tsx
import type { FloatingPanelStage } from '@ark-ui/react/floating-panel'
import type { ReactNode } from 'react'
import type { FloatingPanelStageTriggerProps } from './props'
import { FloatingPanel as ArkFloatingPanel } from '@ark-ui/react/floating-panel'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { Minus, Square, SquareArrowOutDownLeft } from 'lucide-react'
import { forwardRef } from 'react'

function stageIcon(stage: FloatingPanelStage): ReactNode {
  switch (stage) {
    case 'minimized':
      return <Minus />
    case 'maximized':
      return <Square />
    case 'default':
      return <SquareArrowOutDownLeft />
    default: {
      const _exhaustive: never = stage
      return _exhaustive
    }
  }
}

export const FloatingPanelStageTrigger = forwardRef<HTMLButtonElement, FloatingPanelStageTriggerProps>(
  ({ className, theme: propsTheme, stage, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvFloatingPanel')

    return (
      <ArkFloatingPanel.StageTrigger
        ref={ref}
        stage={stage}
        className={crafts.trigger(cxc(className))}
        {...props}
      >
        {children ?? stageIcon(stage)}
      </ArkFloatingPanel.StageTrigger>
    )
  },
)

FloatingPanelStageTrigger.displayName = 'FloatingPanel.StageTrigger'
