// packages/vue/core/src/components/floating-panel/FloatingPanel.vue
<script setup lang="ts">
import type { FloatingPanelProps, FloatingPanelRootEmits } from '.'
import { FloatingPanel, useFloatingPanel, useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { useTheme } from '@raxium/vue/composables/useTheme'
import { useThemeCraft } from '@raxium/vue/composables/useThemeCraft'
import { clamp } from 'es-toolkit'
import { computed, ref } from 'vue'
import { provideFloatingPanelAppearanceContext } from './floating-panel-appearance-context'

const {
  class: propsClass,
  theme: propsTheme,
  opacity: propsOpacity = 100,
  pinned: propsPinned = false,
  resizeAxis = 'xyc',
  lazyMount = undefined,
  unmountOnExit = undefined,
  draggable = true,
  craft,
  ...props
} = defineProps<FloatingPanelProps>()
const emit = defineEmits<FloatingPanelRootEmits>()
const forwarded = useForwardProps(props)

const pinned = ref(propsPinned)
function setPinned(_pinned: boolean) {
  pinned.value = _pinned
}
const opacity = ref(propsOpacity)
function setOpacity(_opacity: number) {
  opacity.value = clamp(_opacity, 0, 100)
}
const mergedProps = computed(() => {
  return {
    ...forwarded.value,
    draggable: !pinned.value && draggable,
  }
})
const floatingPanel = useFloatingPanel(mergedProps, emit)

// appearance context
provideFloatingPanelAppearanceContext({
  opacity,
  pinned,
  setOpacity,
  setPinned,
  resizeAxis: () => resizeAxis,
})

// theme
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvFloatingPanel', () => craft)
useProvideComponentTheme(themed, () => propsTheme)

// expose
defineExpose({
  $api: Object.assign({}, floatingPanel, {
    pinned,
    setPinned: (p: boolean) => {
      pinned.value = p
    },
    opacity,
    setOpacity: (o: number) => {
      opacity.value = clamp(o, 0, 100)
    },
  }),
})
useForwardExpose()
</script>

<template>
  <FloatingPanel.RootProvider :value="floatingPanel">
    <slot />
  </FloatingPanel.RootProvider>
</template>

// packages/react/core/src/components/floating-panel/FloatingPanel.tsx
import type { FloatingPanelProps } from './props'
import { FloatingPanel as ArkFloatingPanel } from '@ark-ui/react/floating-panel'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { clamp } from 'es-toolkit'
import { useCallback, useMemo, useState } from 'react'
import { FloatingPanelAppearanceContext } from './floating-panel-appearance-context'

export function FloatingPanelRoot({
  className: _className,
  theme: propsTheme,
  craft,
  opacity: propsOpacity = 100,
  pinned: propsPinned = false,
  resizeAxis = 'xyc',
  draggable = true,
  children,
  ...props
}: FloatingPanelProps) {
  const [pinned, setPinnedState] = useState(propsPinned)
  const [opacity, setOpacityState] = useState(propsOpacity)
  const setPinned = useCallback((next: boolean) => {
    setPinnedState(next)
  }, [])
  const setOpacity = useCallback((next: number) => {
    setOpacityState(clamp(next, 0, 100))
  }, [])
  const appearance = useMemo(
    () => ({ resizeAxis, opacity, pinned, setOpacity, setPinned }),
    [opacity, pinned, resizeAxis, setOpacity, setPinned],
  )
  const theme = useTheme(propsTheme)
  const themed = useThemeCraft(theme, 'tvFloatingPanel', craft)

  return (
    <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
      <FloatingPanelAppearanceContext.Provider value={appearance}>
        <ArkFloatingPanel.Root
          draggable={!pinned && draggable}
          {...props}
        >
          {children}
        </ArkFloatingPanel.Root>
      </FloatingPanelAppearanceContext.Provider>
    </ProvideComponentTheme>
  )
}

FloatingPanelRoot.displayName = 'FloatingPanel'
