// packages/vue/core/src/components/floating-panel/FloatingPanelHeader.vue
<script setup lang="ts">
import type { FloatingPanelHeaderProps } from '.'
import { FloatingPanel, useForwardProps } from '@ark-ui/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'

const {
  class: propsClass,
  theme: propsTheme,
  ui,
  ...props
} = defineProps<FloatingPanelHeaderProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvFloatingPanel')
</script>

<template>
  <FloatingPanel.DragTrigger>
    <FloatingPanel.Header
      v-bind="forwarded"
      :class="crafts.header(cxc(ui?.root, propsClass))"
    >
      <FloatingPanel.Title :class="crafts.title(cxc(ui?.title))">
        <slot />
      </FloatingPanel.Title>
      <FloatingPanel.Control :class="crafts.control(cxc(ui?.control))">
        <slot name="control" />
      </FloatingPanel.Control>
    </FloatingPanel.Header>
  </FloatingPanel.DragTrigger>
</template>

// packages/react/core/src/components/floating-panel/FloatingPanelHeader.tsx
import type { FloatingPanelHeaderProps } from './props'
import { FloatingPanel as ArkFloatingPanel } from '@ark-ui/react/floating-panel'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const FloatingPanelHeader = forwardRef<HTMLDivElement, FloatingPanelHeaderProps>(
  ({ className, theme: propsTheme, ui, control, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvFloatingPanel')

    return (
      <ArkFloatingPanel.DragTrigger>
        <ArkFloatingPanel.Header
          ref={ref}
          className={crafts.header(cxc(ui?.root, className))}
          {...props}
        >
          <ArkFloatingPanel.Title className={crafts.title(cxc(ui?.title))}>
            {children}
          </ArkFloatingPanel.Title>
          <ArkFloatingPanel.Control className={crafts.control(cxc(ui?.control))}>
            {control}
          </ArkFloatingPanel.Control>
        </ArkFloatingPanel.Header>
      </ArkFloatingPanel.DragTrigger>
    )
  },
)

FloatingPanelHeader.displayName = 'FloatingPanel.Header'
