// packages/vue/core/src/components/floating-panel/FloatingPanelPinTrigger.vue
<script setup lang="ts">
import type { FloatingPanelPinTriggerProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { ark } from '@ark-ui/vue/factory'
import { Pin, PinOff } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { injectFloatingPanelAppearanceContext } from './floating-panel-appearance-context'

const {
  class: propsClass,
  theme: propsTheme,
  ...props
} = defineProps<FloatingPanelPinTriggerProps>()
const emit = defineEmits<{ click: [event: MouseEvent] }>()

const forwarded = useForwardProps(props)
const { pinned, setPinned } = injectFloatingPanelAppearanceContext()

function handleClick(e: MouseEvent) {
  emit('click', e)
  if (e.defaultPrevented)
    return
  setPinned(!pinned.value)
}

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvFloatingPanel')
</script>

<template>
  <ark.button
    v-bind="forwarded"
    :class="crafts.trigger(cxc(propsClass))"
    @click="handleClick"
  >
    <slot v-bind="{ pinned, setPinned }">
      <PinOff v-if="pinned" />
      <Pin v-else />
    </slot>
  </ark.button>
</template>

// packages/react/core/src/components/floating-panel/FloatingPanelPinTrigger.tsx
import type { FloatingPanelPinTriggerProps } from './props'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { Pin, PinOff } from 'lucide-react'
import { forwardRef } from 'react'
import { useFloatingPanelAppearance } from './floating-panel-appearance-context'

export const FloatingPanelPinTrigger = forwardRef<HTMLButtonElement, FloatingPanelPinTriggerProps>(
  ({ className, theme: propsTheme, children, onClick, ...props }, ref) => {
    const { pinned, setPinned } = useFloatingPanelAppearance()
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvFloatingPanel')

    return (
      <ark.button
        ref={ref}
        type="button"
        className={crafts.trigger(cxc(className))}
        {...props}
        onClick={(event) => {
          onClick?.(event)
          if (event.defaultPrevented)
            return
          setPinned(!pinned)
        }}
      >
        {children ?? (pinned ? <PinOff /> : <Pin />)}
      </ark.button>
    )
  },
)

FloatingPanelPinTrigger.displayName = 'FloatingPanel.PinTrigger'
