// packages/vue/core/src/components/menu/MenuItem.vue
<script setup lang="ts">
import type { MenuItemProps } from '.'
import { MenuItem } from '@ark-ui/vue/menu'
import { useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  ...props
} = defineProps<MenuItemProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvMenu')
</script>

<template>
  <MenuItem v-bind="forwarded" :class="crafts.item(cxc(propsClass))">
    <slot />
  </MenuItem>
</template>

// packages/react/core/src/components/menu/MenuItem.tsx
import type { MenuItemProps } from './props'
import { Menu as ArkMenu } from '@ark-ui/react/menu'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const MenuItem = forwardRef<HTMLDivElement, MenuItemProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvMenu')

    return (
      <ArkMenu.Item
        ref={ref}
        className={crafts.item(cxc(className))}
        {...props}
      >
        {children}
      </ArkMenu.Item>
    )
  },
)

MenuItem.displayName = 'Menu.Item'
