// packages/vue/core/src/components/menu/MenuItemGroup.vue
<script setup lang="ts">
import type { MenuItemGroupProps } from '.'
import { Menu } from '@ark-ui/vue/menu'
import { useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  label,
  ui,
  ...props
} = defineProps<MenuItemGroupProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvMenu')
</script>

<template>
  <Menu.ItemGroup
    v-bind="forwarded"
    :class="crafts.itemGroup(cxc(ui?.root, propsClass))"
  >
    <slot name="label">
      <Menu.ItemGroupLabel
        :class="crafts.itemGroupLabel(cxc(ui?.label))"
      >
        {{ label }}
      </Menu.ItemGroupLabel>
    </slot>
    <slot />
  </Menu.ItemGroup>
</template>

// packages/react/core/src/components/menu/MenuItemGroup.tsx
import type { MenuItemGroupProps } from './props'
import { Menu as ArkMenu } from '@ark-ui/react/menu'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const MenuItemGroup = forwardRef<HTMLDivElement, MenuItemGroupProps>(
  ({ className, theme: propsTheme, label, ui, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvMenu')
    const showLabel = label != null && label !== ''

    return (
      <ArkMenu.ItemGroup
        ref={ref}
        className={crafts.itemGroup(cxc(ui?.root, className))}
        {...props}
      >
        {showLabel && (
          <ArkMenu.ItemGroupLabel className={crafts.itemGroupLabel(cxc(ui?.label))}>
            {label}
          </ArkMenu.ItemGroupLabel>
        )}
        {children}
      </ArkMenu.ItemGroup>
    )
  },
)

MenuItemGroup.displayName = 'Menu.ItemGroup'
