// packages/vue/core/src/components/menu/MenuTriggerItem.vue
<script setup lang="ts">
import type { MenuTriggerItemProps } from '.'
import { Menu } from '@ark-ui/vue/menu'
import { useForwardProps } from '@ark-ui/vue/utils'
import { ChevronRight } from '@lucide/vue'
import { cn, cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<MenuTriggerItemProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvMenu')
</script>

<template>
  <Menu.TriggerItem
    v-bind="forwarded"
    :class="cn(crafts.item(cxc(propsClass)), crafts.triggerItem())"
  >
    <Menu.ItemText>
      <slot />
    </Menu.ItemText>
    <Menu.Indicator :class="crafts.triggerItemIndicator()">
      <ChevronRight />
    </Menu.Indicator>
  </Menu.TriggerItem>
</template>

// packages/react/core/src/components/menu/MenuTriggerItem.tsx
import type { MenuTriggerItemProps } from './props'
import { Menu as ArkMenu } from '@ark-ui/react/menu'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cn, cxc } from '@raxium/themes/utils'
import { ChevronRight } from 'lucide-react'
import { forwardRef } from 'react'

export const MenuTriggerItem = forwardRef<HTMLDivElement, MenuTriggerItemProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvMenu')

    return (
      <ArkMenu.TriggerItem
        ref={ref}
        className={cn(crafts.item(cxc(className)), crafts.triggerItem())}
        {...props}
      >
        <ArkMenu.ItemText>
          {children}
        </ArkMenu.ItemText>
        <ArkMenu.Indicator className={crafts.triggerItemIndicator()}>
          <ChevronRight />
        </ArkMenu.Indicator>
      </ArkMenu.TriggerItem>
    )
  },
)

MenuTriggerItem.displayName = 'Menu.TriggerItem'
