// packages/vue/core/src/components/menu/MenuCheckboxItem.vue
<script setup lang="ts">
import type { MenuCheckboxItemEmits, UseMenuItemContext } from '@ark-ui/vue/menu'
import type { UnwrapRef } from 'vue'
import type { MenuCheckboxItemProps } from '.'
import { Menu, MenuItemIndicator } from '@ark-ui/vue/menu'
import { useForwardPropsEmits } from '@ark-ui/vue/utils'
import { Check } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const { class: propsClass, theme: propsTheme, ui, ...props } = defineProps<MenuCheckboxItemProps>()
const emit = defineEmits<MenuCheckboxItemEmits>()
defineSlots<{
  default: (props: UnwrapRef<UseMenuItemContext>) => any
  indicator: (props: UnwrapRef<UseMenuItemContext>) => any
}>()
const forwarded = useForwardPropsEmits(props, emit)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvMenu')
const checkboxCrafts = useCraft(theme, 'tvCheckbox')
</script>

<template>
  <Menu.CheckboxItem
    v-bind="forwarded"
    :class="crafts.item(cxc(ui?.root, propsClass))"
  >
    <Menu.ItemContext v-slot="context">
      <slot
        name="indicator"
        v-bind="context"
      >
        <span
          :class="checkboxCrafts.control(cxc(ui?.checkbox))"
          :data-state="context.checked ? 'checked' : 'unchecked'"
          :data-disabled="context.disabled ? '' : undefined"
          aria-hidden="true"
        >
          <MenuItemIndicator :class="checkboxCrafts.indicator()">
            <Check :class="checkboxCrafts.indicatorChecked()" />
          </MenuItemIndicator>
        </span>
      </slot>
      <slot
        name="default"
        v-bind="context"
      />
    </Menu.ItemContext>
  </Menu.CheckboxItem>
</template>

// packages/react/core/src/components/menu/MenuCheckboxItem.tsx
import type { MenuCheckboxItemProps } from './props'
import { Menu as ArkMenu, useMenuItemContext } from '@ark-ui/react/menu'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { Check } from 'lucide-react'
import { forwardRef } from 'react'

function DefaultCheckboxIndicator({ checkboxClassName }: { checkboxClassName?: string }) {
  const context = useMenuItemContext()
  const theme = useInheritedTheme()
  const checkboxCrafts = useCraft(theme, 'tvCheckbox')

  return (
    <span
      className={checkboxCrafts.control(cxc(checkboxClassName))}
      data-state={context.checked ? 'checked' : 'unchecked'}
      data-disabled={context.disabled ? '' : undefined}
      aria-hidden="true"
    >
      <ArkMenu.ItemIndicator className={checkboxCrafts.indicator()}>
        <Check className={checkboxCrafts.indicatorChecked()} />
      </ArkMenu.ItemIndicator>
    </span>
  )
}

export const MenuCheckboxItem = forwardRef<HTMLDivElement, MenuCheckboxItemProps>(
  ({ className, theme: propsTheme, ui, indicator, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvMenu')

    return (
      <ArkMenu.CheckboxItem
        ref={ref}
        className={crafts.item(cxc(ui?.root, className))}
        {...props}
      >
        {indicator ?? <DefaultCheckboxIndicator checkboxClassName={ui?.checkbox} />}
        {children}
      </ArkMenu.CheckboxItem>
    )
  },
)

MenuCheckboxItem.displayName = 'Menu.CheckboxItem'
