// packages/react/core/src/components/slider/SliderTooltipThumb.tsx
import type { SliderTooltipThumbProps } from './props'
import { Slider as ArkSlider, useSliderContext } from '@ark-ui/react/slider'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { cxc } from '@raxium/themes/utils'
import { merge } from 'es-toolkit/compat'
import { forwardRef, useMemo } from 'react'
import { Tooltip } from '../tooltip'
import { useSliderBoundary } from './slider-boundary-context'
import { SliderTooltipReposition } from './SliderTooltipReposition'

export const SliderTooltipThumb = forwardRef<HTMLDivElement, SliderTooltipThumbProps>(
  (
    {
      className,
      theme: propsTheme,
      index,
      name,
      open,
      widget,
      children,
      positioning,
      ...tooltipProps
    },
    ref,
  ) => {
    const context = useSliderContext()
    const boundary = useSliderBoundary()
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvSlider')
    const tooltipOpen = open?.(context) ?? context.dragging
    const mergedPositioning = useMemo(
      () =>
        merge(
          {
            boundary: () => boundary,
            overflowPadding: 0,
            placement: 'top',
            flip: false,
            shift: true,
            slide: true,
            overlap: false,
          },
          positioning,
        ),
      [boundary, positioning],
    )

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <Tooltip
          open={tooltipOpen}
          positioning={mergedPositioning}
          theme={propsTheme}
          {...tooltipProps}
        >
          <SliderTooltipReposition valueKey={String(context.value)} />
          <Tooltip.Trigger asChild>
            <ArkSlider.Thumb
              ref={ref}
              className={crafts.thumb(cxc(className))}
              data-theme-size={theme.size}
              index={index}
              name={name}
            >
              <ArkSlider.HiddenInput />
            </ArkSlider.Thumb>
          </Tooltip.Trigger>
          <Tooltip.Content {...widget?.tooltipContent}>
            <Tooltip.Arrow {...widget?.tooltipArrow} />
            {children ?? <ArkSlider.ValueText />}
          </Tooltip.Content>
        </Tooltip>
      </ProvideStructuralComponentTheme>
    )
  },
)

SliderTooltipThumb.displayName = 'Slider.TooltipThumb'

// packages/vue/core/src/components/slider/SliderTooltipThumb.vue
<script setup lang="ts">
import type { SliderTooltipThumbProps } from '.'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { Slider, useSliderContext } from '@ark-ui/vue/slider'
import { TooltipRootProvider, useTooltip } from '@ark-ui/vue/tooltip'
import { cxc } from '@raxium/themes/utils'
import { TooltipArrow, TooltipContent, TooltipTrigger } from '@raxium/vue/components/tooltip'
import { useConfig } from '@raxium/vue/composables/useConfig'
import { useCraft, useTheme } from '@raxium/vue/composables'
import { ThemeProvider } from '@raxium/vue/providers/theme'
import { merge } from 'es-toolkit/compat'
import { computed, watch } from 'vue'
import { injectSliderBoundaryContext } from './SliderBoundaryProvider.vue'

const {
  class: propsClass,
  theme: propsTheme,
  index, // thumb prop
  name, // thumb prop
  open, // tooltip prop
  widget,
  ...props
} = defineProps<SliderTooltipThumbProps>()
const context = useSliderContext()

const boundary = injectSliderBoundaryContext()
const tooltipForwarded = useForwardProps(props)
const configs = useConfig('tooltip')
const tooltip = useTooltip(
  computed(() =>
    merge(
      {
        open: open?.(context.value) ?? context.value.dragging,
        positioning: {
          boundary: boundary.value,
          overflowPadding: 0,
          placement: 'top',
          shift: 0,
          flip: false,
        },
      },
      configs.value,
      tooltipForwarded.value,
    ),
  ),
)

watch(
  () => context.value.value,
  () => {
    // we reposition when the value changes, it will be smoother when thumb fast dragging
    tooltip.value.reposition()
  },
)

// theme
const theme = useTheme(() => propsTheme)
const tooltipTheme = useTheme(() => ({ ...configs.value?.theme, ...propsTheme }))
const crafts = useCraft(theme, 'tvSlider')

// expose
const { forwardRef } = useForwardExpose()
</script>

<template>
  <ThemeProvider :value="theme">
    <TooltipRootProvider :value="tooltip">
      <TooltipTrigger as-child>
        <Slider.Thumb
          :ref="(el) => el && forwardRef(el)"
          :class="crafts.thumb(cxc(propsClass))"
          :data-theme-size="theme.size"
          :index="index"
          :name="name"
        >
          <Slider.HiddenInput />
        </Slider.Thumb>
      </TooltipTrigger>
      <ThemeProvider :value="tooltipTheme">
        <Teleport
          v-if="tooltipForwarded.positioning?.strategy === 'fixed'"
          to="body"
        >
          <TooltipContent v-bind="widget?.tooltipContent">
            <slot name="arrow">
              <TooltipArrow v-bind="widget?.tooltipArrow" />
            </slot>
            <slot name="default">
              <Slider.ValueText />
            </slot>
          </TooltipContent>
        </Teleport>
        <TooltipContent
          v-else
          v-bind="widget?.tooltipContent"
        >
          <slot name="arrow">
            <TooltipArrow v-bind="widget?.tooltipArrow" />
          </slot>
          <slot name="default">
            <Slider.ValueText />
          </slot>
        </TooltipContent>
      </ThemeProvider>
    </TooltipRootProvider>
  </ThemeProvider>
</template>
