// packages/react/core/src/components/date-picker/DatePickerYearView.tsx
import type { DatePickerYearViewProps } from './props'
import { DatePicker as ArkDatePicker, useDatePickerContext } from '@ark-ui/react/date-picker'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { flatten } from 'es-toolkit'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { forwardRef, useMemo } from 'react'

export const DatePickerYearView = forwardRef<HTMLDivElement, DatePickerYearViewProps>(
  ({ className, theme: propsTheme }, ref) => {
    const context = useDatePickerContext()
    const theme = useInheritedTheme(propsTheme)
    const viewVariants = useMemo(() => ({ view: 'year' as const }), [])
    const crafts = useCraft(theme, 'tvDatePickerView', viewVariants)

    return (
      <ArkDatePicker.View ref={ref} view="year" className={crafts.view(cxc(className))}>
        <ArkDatePicker.ViewControl className={crafts.viewControl()}>
          <ArkDatePicker.PrevTrigger asChild className={crafts.viewControlTrigger()}>
            <ChevronLeft />
          </ArkDatePicker.PrevTrigger>
          <ArkDatePicker.RangeText />
          <ArkDatePicker.NextTrigger asChild className={crafts.viewControlTrigger()}>
            <ChevronRight />
          </ArkDatePicker.NextTrigger>
        </ArkDatePicker.ViewControl>
        <ArkDatePicker.Table className={crafts.table()}>
          <div {...context.getTableBodyProps()} className={crafts.tableBody()}>
            {flatten(context.getYearsGrid({ columns: 4 })).map((year, yid) => (
              <ArkDatePicker.TableCell
                key={`year-${yid}`}
                value={year.value}
                className={crafts.tableCell()}
              >
                <ArkDatePicker.TableCellTrigger
                  className={crafts.tableCellTrigger(context.getYearTableCellState({ value: year.value }))}
                >
                  {year.label}
                </ArkDatePicker.TableCellTrigger>
              </ArkDatePicker.TableCell>
            ))}
          </div>
        </ArkDatePicker.Table>
      </ArkDatePicker.View>
    )
  },
)

DatePickerYearView.displayName = 'DatePicker.YearView'

// packages/vue/core/src/components/date-picker/DatePickerYearView.vue
<script setup lang="ts">
import type { DatePickerYearViewProps } from '.'
import { DatePicker, useDatePickerContext } from '@ark-ui/vue'
import { ChevronLeft, ChevronRight } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { flatten } from 'es-toolkit'

const { class: propsClass, theme: propsTheme } = defineProps<DatePickerYearViewProps>()
const context = useDatePickerContext()

// theme
const theme = useInheritedTheme(() => Object.assign({}, propsTheme, { view: 'year' }))
const crafts = useCraft(theme, 'tvDatePickerView', () => ({ view: 'year' as const }))
</script>

<template>
  <DatePicker.View
    view="year"
    :class="crafts.view(cxc(propsClass))"
  >
    <DatePicker.ViewControl :class="crafts.viewControl()">
      <DatePicker.PrevTrigger
        as-child
        :class="crafts.viewControlTrigger()"
      >
        <ChevronLeft />
      </DatePicker.PrevTrigger>
      <DatePicker.RangeText />
      <DatePicker.NextTrigger
        as-child
        :class="crafts.viewControlTrigger()"
      >
        <ChevronRight />
      </DatePicker.NextTrigger>
    </DatePicker.ViewControl>

    <DatePicker.Table :class="crafts.table()">
      <div
        v-bind="context.getTableBodyProps()"
        :class="crafts.tableBody()"
      >
        <DatePicker.TableCell
          v-for="(year, yid) in flatten(context.getYearsGrid({ columns: 4 }))"
          :key="`year-${yid}`"
          :value="year.value"
          :class="crafts.tableCell()"
        >
          <DatePicker.TableCellTrigger
            :class="crafts.tableCellTrigger(context.getYearTableCellState({ value: year.value }))"
          >
            {{ year.label }}
          </DatePicker.TableCellTrigger>
        </DatePicker.TableCell>
      </div>
    </DatePicker.Table>
  </DatePicker.View>
</template>
