// packages/react/core/src/components/date-picker/DatePickerControl.tsx
import type { DatePickerControlProps } from './props'
import { DatePicker as ArkDatePicker } from '@ark-ui/react/date-picker'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const DatePickerControl = forwardRef<HTMLDivElement, DatePickerControlProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvDatePicker')

    return (
      <ArkDatePicker.Control
        ref={ref}
        className={crafts.control(cxc(className))}
        {...props}
      >
        {children}
      </ArkDatePicker.Control>
    )
  },
)

DatePickerControl.displayName = 'DatePicker.Control'

// packages/vue/core/src/components/date-picker/DatePickerControl.vue
<script setup lang="ts">
import type { DatePickerControlProps } from '.'
import { DatePicker } from '@ark-ui/vue'
import { useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<DatePickerControlProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvDatePicker')
</script>

<template>
  <DatePicker.Control
    v-bind="forwarded"
    :class="crafts.control(cxc(propsClass))"
  >
    <slot />
  </DatePicker.Control>
</template>
