// packages/react/core/src/components/date-picker/DatePickerMonthView.tsx
import type { DatePickerMonthViewProps } from './props'
import { DatePicker as ArkDatePicker, useDatePickerContext } from '@ark-ui/react/date-picker'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { forwardRef, useMemo } from 'react'
import { useDatePickerContentContext } from './date-picker-content-context'

export const DatePickerMonthView = forwardRef<HTMLDivElement, DatePickerMonthViewProps>(
  ({ className, theme: propsTheme, monthType = 'short' }, ref) => {
    const viewsState = useDatePickerContentContext()
    const context = useDatePickerContext()
    const theme = useInheritedTheme(propsTheme)
    const viewVariants = useMemo(() => ({ view: 'month' as const }), [])
    const crafts = useCraft(theme, 'tvDatePickerView', viewVariants)

    return (
      <ArkDatePicker.View ref={ref} view="month" className={crafts.view(cxc(className))}>
        <ArkDatePicker.ViewControl className={crafts.viewControl()}>
          <ArkDatePicker.PrevTrigger asChild className={crafts.viewControlTrigger()}>
            <ChevronLeft />
          </ArkDatePicker.PrevTrigger>
          {viewsState.count > 1 && viewsState.hasYearView
            ? (
                <ArkDatePicker.ViewTrigger className={crafts.viewTrigger()}>
                  <ArkDatePicker.RangeText />
                </ArkDatePicker.ViewTrigger>
              )
            : <ArkDatePicker.RangeText />}
          <ArkDatePicker.NextTrigger asChild className={crafts.viewControlTrigger()}>
            <ChevronRight />
          </ArkDatePicker.NextTrigger>
        </ArkDatePicker.ViewControl>
        <ArkDatePicker.Table className={crafts.table()}>
          <div {...context.getTableBodyProps()} className={crafts.tableBody()}>
            {context.getMonths({ format: monthType }).map((month, mid) => (
              <ArkDatePicker.TableCell key={mid} value={month.value} className={crafts.tableCell()}>
                <ArkDatePicker.TableCellTrigger
                  className={crafts.tableCellTrigger(context.getMonthTableCellState({ value: month.value }))}
                >
                  {month.label}
                </ArkDatePicker.TableCellTrigger>
              </ArkDatePicker.TableCell>
            ))}
          </div>
        </ArkDatePicker.Table>
      </ArkDatePicker.View>
    )
  },
)

DatePickerMonthView.displayName = 'DatePicker.MonthView'

// packages/vue/core/src/components/date-picker/DatePickerMonthView.vue
<script setup lang="ts">
import type { DatePickerContentProvide, DatePickerMonthViewProps } from '.'
import { DatePicker, useDatePickerContext } from '@ark-ui/vue'
import { ChevronLeft, ChevronRight } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { computed, inject } from 'vue'
import { DATE_PICKER_CONTENT_PROVIDE_KEY } from '.'

const {
  class: propsClass,
  theme: propsTheme,
  monthType = 'short',
} = defineProps<DatePickerMonthViewProps>()
const { viewsState } = inject<DatePickerContentProvide>(DATE_PICKER_CONTENT_PROVIDE_KEY, {
  viewsState: computed(() => ({
    count: 1,
    hasDayView: false,
    hasMonthView: true,
    hasYearView: false,
  })),
})
const context = useDatePickerContext()

// theme
const theme = useInheritedTheme(() =>
  Object.assign({}, propsTheme, {
    view: 'month',
    monthType,
  }),
)
const crafts = useCraft(theme, 'tvDatePickerView', () => ({ view: 'month' as const }))
</script>

<template>
  <DatePicker.View
    view="month"
    :class="crafts.view(cxc(propsClass))"
  >
    <DatePicker.ViewControl :class="crafts.viewControl()">
      <DatePicker.PrevTrigger
        as-child
        :class="crafts.viewControlTrigger()"
      >
        <ChevronLeft />
      </DatePicker.PrevTrigger>
      <DatePicker.ViewTrigger
        v-if="viewsState.count > 1 && viewsState.hasYearView"
        :class="crafts.viewTrigger()"
      >
        <DatePicker.RangeText />
      </DatePicker.ViewTrigger>
      <DatePicker.RangeText v-else />
      <DatePicker.NextTrigger
        as-child
        :class="crafts.viewControlTrigger()"
      >
        <ChevronRight />
      </DatePicker.NextTrigger>
    </DatePicker.ViewControl>

    <DatePicker.Table :class="crafts.table()">
      <div
        v-bind="context.getTableBodyProps()"
        :class="crafts.tableBody()"
      >
        <DatePicker.TableCell
          v-for="(month, mid) in context.getMonths({ format: monthType })"
          :key="mid"
          :value="month.value"
          :class="crafts.tableCell()"
        >
          <DatePicker.TableCellTrigger
            :class="crafts.tableCellTrigger(context.getMonthTableCellState({ value: month.value }))"
          >
            {{ month.label }}
          </DatePicker.TableCellTrigger>
        </DatePicker.TableCell>
      </div>
    </DatePicker.Table>
  </DatePicker.View>
</template>
