// packages/react/core/src/components/date-picker/DatePickerDayView.tsx
import type { DatePickerDayViewProps } from './props'
import { DatePicker as ArkDatePicker, useDatePickerContext } from '@ark-ui/react/date-picker'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { flatten } from 'es-toolkit'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { forwardRef, useMemo } from 'react'
import { useDatePickerContentContext } from './date-picker-content-context'

function weekDayLabel(
  weekDay: { short: string, long: string, narrow: string },
  type: NonNullable<DatePickerDayViewProps['weekDayType']>,
) {
  switch (type) {
    case 'short':
      return weekDay.short
    case 'long':
      return weekDay.long
    case 'narrow':
      return weekDay.narrow
    default: {
      const _exhaustive: never = type
      return _exhaustive
    }
  }
}

export const DatePickerDayView = forwardRef<HTMLDivElement, DatePickerDayViewProps>(
  ({ className, theme: propsTheme, weekDayType = 'short' }, ref) => {
    const viewsState = useDatePickerContentContext()
    const context = useDatePickerContext()
    const theme = useInheritedTheme(propsTheme)
    const viewVariants = useMemo(() => ({ view: 'day' as const }), [])
    const crafts = useCraft(theme, 'tvDatePickerView', viewVariants)

    return (
      <ArkDatePicker.View ref={ref} view="day" className={crafts.view(cxc(className))}>
        <ArkDatePicker.ViewControl className={crafts.viewControl()}>
          <ArkDatePicker.PrevTrigger asChild className={crafts.viewControlTrigger()}>
            <ChevronLeft />
          </ArkDatePicker.PrevTrigger>
          {viewsState.count > 1 && viewsState.hasMonthView
            ? (
                <ArkDatePicker.ViewTrigger className={crafts.viewTrigger()}>
                  <ArkDatePicker.RangeText />
                </ArkDatePicker.ViewTrigger>
              )
            : <ArkDatePicker.RangeText />}
          <ArkDatePicker.NextTrigger asChild className={crafts.viewControlTrigger()}>
            <ChevronRight />
          </ArkDatePicker.NextTrigger>
        </ArkDatePicker.ViewControl>
        <ArkDatePicker.Table className={crafts.table()}>
          <div {...context.getTableHeadProps()} className={crafts.tableHead()}>
            {context.weekDays.map((weekDay, id) => (
              <div
                key={id}
                {...context.getTableHeaderProps()}
                className={crafts.tableHeader()}
              >
                {weekDayLabel(weekDay, weekDayType)}
              </div>
            ))}
          </div>
          <div {...context.getTableBodyProps()} className={crafts.tableBody()}>
            {flatten(context.weeks).map((day, did) => (
              <ArkDatePicker.TableCell key={did} value={day} className={crafts.tableCell()}>
                <ArkDatePicker.TableCellTrigger
                  className={crafts.tableCellTrigger(context.getDayTableCellState({ value: day }))}
                >
                  {day.day}
                </ArkDatePicker.TableCellTrigger>
              </ArkDatePicker.TableCell>
            ))}
          </div>
        </ArkDatePicker.Table>
      </ArkDatePicker.View>
    )
  },
)

DatePickerDayView.displayName = 'DatePicker.DayView'

// packages/vue/core/src/components/date-picker/DatePickerDayView.vue
<script setup lang="ts">
import type { DatePickerContentProvide, DatePickerDayViewProps } from '.'
import { DatePicker, useDatePickerContext } from '@ark-ui/vue'
import { ChevronLeft, ChevronRight } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { flatten } from 'es-toolkit'
import { computed, inject } from 'vue'
import { DATE_PICKER_CONTENT_PROVIDE_KEY } from '.'

const {
  class: propsClass,
  theme: propsTheme,
  weekDayType = 'short',
} = defineProps<DatePickerDayViewProps>()
const { viewsState } = inject<DatePickerContentProvide>(DATE_PICKER_CONTENT_PROVIDE_KEY, {
  viewsState: computed(() => ({
    count: 1,
    hasDayView: true,
    hasMonthView: false,
    hasYearView: false,
  })),
})

const context = useDatePickerContext()

// theme
const theme = useInheritedTheme(() =>
  Object.assign({}, propsTheme, {
    view: 'day',
    weekDayType,
  }),
)
const crafts = useCraft(theme, 'tvDatePickerView', () => ({ view: 'day' as const }))
</script>

<template>
  <DatePicker.View
    view="day"
    :class="crafts.view(cxc(propsClass))"
  >
    <DatePicker.ViewControl :class="crafts.viewControl()">
      <DatePicker.PrevTrigger
        as-child
        :class="crafts.viewControlTrigger()"
      >
        <ChevronLeft />
      </DatePicker.PrevTrigger>
      <DatePicker.ViewTrigger
        v-if="viewsState.count > 1 && viewsState.hasMonthView"
        :class="crafts.viewTrigger()"
      >
        <DatePicker.RangeText />
      </DatePicker.ViewTrigger>
      <DatePicker.RangeText v-else />
      <DatePicker.NextTrigger
        as-child
        :class="crafts.viewControlTrigger()"
      >
        <ChevronRight />
      </DatePicker.NextTrigger>
    </DatePicker.ViewControl>
    <DatePicker.Table :class="crafts.table()">
      <div
        v-bind="context.getTableHeadProps()"
        :class="crafts.tableHead()"
      >
        <div
          v-for="(weekDay, id) in context.weekDays"
          v-bind="context.getTableHeaderProps()"
          :key="id"
          :class="crafts.tableHeader()"
        >
          {{ weekDay[weekDayType] }}
        </div>
      </div>
      <div
        v-bind="context.getTableBodyProps()"
        :class="crafts.tableBody()"
      >
        <DatePicker.TableCell
          v-for="(day, did) in flatten(context.weeks)"
          :key="did"
          :value="day"
          :class="crafts.tableCell()"
        >
          <DatePicker.TableCellTrigger
            :class="crafts.tableCellTrigger(context.getDayTableCellState({ value: day }))"
          >
            {{ day.day }}
          </DatePicker.TableCellTrigger>
        </DatePicker.TableCell>
      </div>
    </DatePicker.Table>
  </DatePicker.View>
</template>
