// packages/react/core/src/components/radio-group/RadioGroup.tsx
import type { RadioGroupProps } from './props'
import { RadioGroup as ArkRadioGroup } from '@ark-ui/react/radio-group'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const RadioGroupRoot = forwardRef<HTMLDivElement, RadioGroupProps>(
  ({ className, theme: propsTheme, craft, ui, label, children, ...props }, ref) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvRadioGroup', craft)
    const crafts = useCraft(themed, 'tvRadioGroup')
    const showLabel = label != null && label !== ''

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkRadioGroup.Root
          ref={ref}
          className={crafts.root(cxc(ui?.root, className))}
          {...props}
        >
          {showLabel && (
            <ArkRadioGroup.Label className={crafts.label(cxc(ui?.label))}>
              {label}
            </ArkRadioGroup.Label>
          )}
          {children}
        </ArkRadioGroup.Root>
      </ProvideComponentTheme>
    )
  },
)

RadioGroupRoot.displayName = 'RadioGroup'

// packages/vue/core/src/components/radio-group/RadioGroup.vue
<script setup lang="ts" generic="T extends RadioGroupValueType">
import type { UseRadioGroupProps } from '@ark-ui/vue/radio-group'
import type { RadioGroupProps, RadioGroupRootEmits, RadioGroupValueType } from '.'
import { RadioGroup, useRadioGroup } from '@ark-ui/vue/radio-group'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'

const {
  class: propsClass,
  theme: propsTheme,
  craft,
  ui,
  label,
  ...props
} = defineProps<RadioGroupProps<T>>()
const emit = defineEmits<RadioGroupRootEmits<T>>()
const radioGroup = useRadioGroup(useForwardProps(props) as unknown as UseRadioGroupProps, emit)

// theme
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvRadioGroup', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvRadioGroup')

// expose
defineExpose({ $api: radioGroup })
useForwardExpose()
</script>

<template>
  <RadioGroup.RootProvider
    :value="radioGroup"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <RadioGroup.Label
      v-if="label || $slots.label"
      :class="crafts.label(cxc(ui?.label))"
    >
      <slot name="label">
        {{ label }}
      </slot>
    </RadioGroup.Label>
    <slot />
  </RadioGroup.RootProvider>
</template>
