// packages/react/core/src/components/radio-group/RadioGroupLayout.tsx
import type { RadioGroupLayoutProps } from './props'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'

export function RadioGroupLayout({
  className,
  layout = 'stack',
  children,
}: RadioGroupLayoutProps) {
  const theme = useInheritedTheme()
  const crafts = useCraft(theme, 'tvRadioGroup', { layout })

  return (
    <div
      className={crafts.layout(cxc(className))}
      data-scope="radio-group"
      data-part="layout"
    >
      {children}
    </div>
  )
}

RadioGroupLayout.displayName = 'RadioGroup.Layout'

// packages/vue/core/src/components/radio-group/RadioGroupLayout.vue
<script setup lang="ts">
import type { RadioGroupLayoutProps } from './props'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const { class: propsClass, layout = 'stack' } = defineProps<RadioGroupLayoutProps>()

const theme = useInheritedTheme()
const crafts = useCraft(theme, 'tvRadioGroup', () => ({ layout }))
</script>

<template>
  <div
    :class="crafts.layout(cxc(propsClass))"
    data-scope="radio-group"
    data-part="layout"
  >
    <slot />
  </div>
</template>
