// packages/vue/core/src/components/slider/examples/range.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Slider, SliderThumb } from '../index'

const value = ref([20, 70])
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="text-sm text-gray-cc">
      defaultValue: [20, 70]
      value: {{ value }}
    </div>

    <Slider v-model="value" class="w-80" :min="0" :max="100" :step="5" :default-value="[20, 70]">
      <SliderThumb :index="0" />
      <SliderThumb :index="1" />
    </Slider>
  </div>
</template>

// packages/react/core/src/components/slider/examples/range.tsx
import { useState } from 'react'
import { Slider } from '../index'

export function SliderRangeExample() {
  const [value, setValue] = useState([20, 70])

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="text-sm text-gray-cc">
        defaultValue: [20, 70]
        value:
        {' '}
        {JSON.stringify(value)}
      </div>

      <Slider
        className="w-80"
        min={0}
        max={100}
        step={5}
        value={value}
        onValueChange={details => setValue(details.value)}
      >
        <Slider.Thumb index={0} />
        <Slider.Thumb index={1} />
      </Slider>
    </div>
  )
}
