// packages/react/core/src/components/collapsible/examples/states.tsx
import { Collapsible } from '../index'

const content = 'Collapsible content for the React port. Toggle the trigger to show or hide this copy.'

export function CollapsibleStatesExample() {
  return (
    <div className="w-full flex flex-col gap-4">
      <Collapsible className="w-full" defaultOpen>
        <Collapsible.Trigger>
          <div className="text-sm text-gray-ff">Default open</div>
        </Collapsible.Trigger>
        <Collapsible.Content className="mt-2">
          <p className="text-sm text-gray-cc">{content}</p>
        </Collapsible.Content>
      </Collapsible>

      <Collapsible className="w-full" disabled>
        <Collapsible.Trigger>
          <div className="text-sm text-gray-ff">Disabled (cannot toggle)</div>
        </Collapsible.Trigger>
        <Collapsible.Content className="mt-2">
          <p className="text-sm text-gray-cc">{content}</p>
        </Collapsible.Content>
      </Collapsible>
    </div>
  )
}

// packages/vue/core/src/components/collapsible/examples/states.vue
<script setup lang="ts">
import { fakerEN } from '@faker-js/faker'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '../index'

const content = fakerEN.lorem.sentences(10)
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <Collapsible class="w-full" default-open>
      <CollapsibleTrigger>
        <div class="text-sm text-gray-ff">
          Default open
        </div>
      </CollapsibleTrigger>
      <CollapsibleContent class="mt-2">
        <p class="text-sm text-gray-cc">
          {{ content }}
        </p>
      </CollapsibleContent>
    </Collapsible>

    <Collapsible class="w-full" disabled>
      <CollapsibleTrigger>
        <div class="text-sm text-gray-ff">
          Disabled (cannot toggle)
        </div>
      </CollapsibleTrigger>
      <CollapsibleContent class="mt-2">
        <p class="text-sm text-gray-cc">
          {{ content }}
        </p>
      </CollapsibleContent>
    </Collapsible>
  </div>
</template>
