// packages/vue/core/src/components/accordion/AccordionContent.vue
<script setup lang="ts">
import type { AccordionContentProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Accordion } from '@ark-ui/vue/accordion'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'

const {
  class: propsClass,
  theme: propsTheme,
  ...props
} = defineProps<AccordionContentProps>()
const forwarded = useForwardProps(props)

const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvAccordion')
</script>

<template>
  <Accordion.ItemContent
    v-bind="forwarded"
    :class="crafts.content(cxc(propsClass))"
  >
    <slot />
  </Accordion.ItemContent>
</template>

// packages/react/core/src/components/accordion/AccordionContent.tsx
import type { AccordionContentProps } from './props'
import { Accordion as ArkAccordion } from '@ark-ui/react/accordion'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const AccordionContent = forwardRef<HTMLDivElement, AccordionContentProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvAccordion')

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <ArkAccordion.ItemContent
          ref={ref}
          className={crafts.content(cxc(className))}
          {...props}
        >
          {children}
        </ArkAccordion.ItemContent>
      </ProvideStructuralComponentTheme>
    )
  },
)

AccordionContent.displayName = 'Accordion.Content'
