// packages/react/core/src/components/rating-group/examples/allow-half.tsx
import { useState } from 'react'
import { RatingGroup } from '../index'

const items = [1, 2, 3, 4, 5]

export function RatingGroupAllowHalfExample() {
  const [value, setValue] = useState(2.5)

  return (
    <div className="w-full flex flex-col gap-2">
      <div className="text-sm text-gray-cc">
        value:
        {' '}
        <span className="text-gray-ff">{value}</span>
        （allow-half）
      </div>

      <div className="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
        <RatingGroup
          value={value}
          allowHalf
          count={5}
          onValueChange={details => setValue(details.value)}
        >
          {items.map(index => (
            <RatingGroup.Item key={index} index={index} />
          ))}
        </RatingGroup>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/rating-group/examples/allow-half.vue
<script setup lang="ts">
import { ref } from 'vue'
import { RatingGroup, RatingGroupItem } from '../index'

const value = ref<number>(2.5)
</script>

<template>
  <div class="w-full flex flex-col gap-2">
    <div class="text-sm text-gray-cc">
      value: <span class="text-gray-ff">{{ value }}</span>（allow-half）
    </div>

    <div class="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
      <RatingGroup v-model="value" allow-half :count="5">
        <template #default="{ items }">
          <RatingGroupItem v-for="item in items" :key="item" :index="item" />
        </template>
      </RatingGroup>
    </div>
  </div>
</template>
