// packages/react/core/src/components/rating-group/examples/programmatic.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { RatingGroup } from '../index'

const items = [1, 2, 3, 4, 5]

export function RatingGroupProgrammaticExample() {
  const [value, setValue] = useState(3)

  return (
    <div className="w-full flex flex-col gap-3">
      <div className="flex flex-wrap items-center gap-2">
        <Button variant="outlined" onClick={() => setValue(1)}>
          Set 1
        </Button>
        <Button variant="outlined" onClick={() => setValue(3)}>
          Set 3
        </Button>
        <Button variant="outlined" onClick={() => setValue(5)}>
          Set 5
        </Button>
        <Button variant="outlined" onClick={() => setValue(-1)}>
          Clear
        </Button>
        <div className="text-sm text-gray-cc">
          value:
          {' '}
          <span className="text-gray-ff">{value}</span>
        </div>
      </div>

      <div className="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
        <RatingGroup value={value} count={5} onValueChange={details => setValue(details.value)}>
          {items.map(index => (
            <RatingGroup.Item key={index} index={index} />
          ))}
        </RatingGroup>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/rating-group/examples/programmatic.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import { RatingGroup, RatingGroupItem } from '../index'

const value = ref<number>(3)
const ratingRef = ref<any>(null)
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="flex flex-wrap items-center gap-2">
      <Button variant="outlined" @click="ratingRef?.$api?.setValue(1)">
        Set 1
      </Button>
      <Button variant="outlined" @click="ratingRef?.$api?.setValue(3)">
        Set 3
      </Button>
      <Button variant="outlined" @click="ratingRef?.$api?.setValue(5)">
        Set 5
      </Button>
      <Button variant="outlined" @click="ratingRef?.$api?.clearValue()">
        Clear
      </Button>
      <div class="text-sm text-gray-cc">
        value: <span class="text-gray-ff">{{ value }}</span>
      </div>
    </div>

    <div class="w-full max-w-[520px] rounded-md border border-gray-33 p-3">
      <RatingGroup ref="ratingRef" v-model="value" :count="5">
        <template #default="{ items }">
          <RatingGroupItem v-for="item in items" :key="item" :index="item" />
        </template>
      </RatingGroup>
    </div>
  </div>
</template>
