// packages/react/core/src/components/rating-group/examples/states.tsx
import { RatingGroup } from '../index'

const items = [1, 2, 3, 4, 5]

export function RatingGroupStatesExample() {
  return (
    <div className="w-full flex flex-col gap-4">
      <div className="w-full max-w-[520px] flex flex-col gap-3">
        <div className="text-sm text-gray-cc">
          Disabled
        </div>
        <div className="rounded-md border border-gray-33 p-3">
          <RatingGroup defaultValue={3} disabled count={5}>
            {items.map(index => (
              <RatingGroup.Item key={index} index={index} />
            ))}
          </RatingGroup>
        </div>

        <div className="text-sm text-gray-cc">
          ReadOnly
        </div>
        <div className="rounded-md border border-gray-33 p-3">
          <RatingGroup defaultValue={4} readOnly count={5}>
            {items.map(index => (
              <RatingGroup.Item key={index} index={index} />
            ))}
          </RatingGroup>
        </div>
      </div>
    </div>
  )
}

// packages/vue/core/src/components/rating-group/examples/states.vue
<script setup lang="ts">
import { RatingGroup, RatingGroupItem } from '../index'
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="w-full max-w-[520px] flex flex-col gap-3">
      <div class="text-sm text-gray-cc">
        Disabled
      </div>
      <div class="rounded-md border border-gray-33 p-3">
        <RatingGroup :default-value="3" disabled :count="5">
          <template #default="{ items }">
            <RatingGroupItem v-for="item in items" :key="item" :index="item" />
          </template>
        </RatingGroup>
      </div>

      <div class="text-sm text-gray-cc">
        ReadOnly
      </div>
      <div class="rounded-md border border-gray-33 p-3">
        <RatingGroup :default-value="4" read-only :count="5">
          <template #default="{ items }">
            <RatingGroupItem v-for="item in items" :key="item" :index="item" />
          </template>
        </RatingGroup>
      </div>
    </div>
  </div>
</template>
