// packages/react/core/src/components/popover/examples/controlled.tsx
import { useState } from 'react'
import { Button } from '../../button'
import { Popover } from '../index'

export function PopoverControlledExample() {
  const [open, setOpen] = useState(false)

  return (
    <div className="w-full flex items-center gap-4">
      <Button onClick={() => setOpen(!open)}>
        Toggle open:
        {' '}
        {String(open)}
      </Button>

      <Popover
        open={open}
        onOpenChange={details => setOpen(details.open)}
        positioning={{ placement: 'bottom-start' }}
      >
        <Popover.Trigger asChild>
          <Button variant="outlined">Controlled Popover</Button>
        </Popover.Trigger>
        <Popover.Content>
          <Popover.Arrow />
          <div className="flex flex-col gap-2">
            <Popover.Close />
            <div className="text-sm text-gray-ff">Controlled via open + onOpenChange</div>
          </div>
        </Popover.Content>
      </Popover>
    </div>
  )
}

// packages/vue/core/src/components/toggle/examples/controlled.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '../../button'
import { Toggle } from '../index'

const pressed = ref(false)
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="flex items-center gap-2">
      <Button variant="outlined" @click="pressed = false">
        Set off
      </Button>
      <Button variant="outlined" @click="pressed = true">
        Set on
      </Button>
      <span class="text-sm text-gray-ff">pressed: {{ pressed }}</span>
    </div>

    <Toggle v-model:pressed="pressed">
      Controlled toggle
    </Toggle>
  </div>
</template>
