// packages/vue/core/src/components/switch/Switch.vue
<script setup lang="ts">
import type { SwitchRootEmits } from '@ark-ui/vue'
import type { SwitchProps } from '.'
import { Switch, useForwardExpose, useForwardProps, useSwitch } from '@ark-ui/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'

const { class: propsClass, theme: propsTheme, craft, ui, ...props } = defineProps<SwitchProps>()
const emit = defineEmits<SwitchRootEmits>()
const switchRoot = useSwitch(useForwardProps(props), emit)

// theme
const theme = useTheme(() => propsTheme, undefined, () => craft)
useProvideComponentTheme(theme, () => propsTheme)
const crafts = useCraft(theme, 'tvSwitch')

// expose
defineExpose({ $api: switchRoot })
useForwardExpose()
</script>

<template>
  <Switch.RootProvider
    :value="switchRoot"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >      <Switch.Control :class="crafts.control(cxc(ui?.control))">
        <Switch.Thumb :class="crafts.thumb(cxc(ui?.thumb))" />
      </Switch.Control>
      <Switch.HiddenInput />
      <slot />  </Switch.RootProvider>
</template>

// packages/react/core/src/components/switch/Switch.tsx
import type { SwitchProps } from './props'
import { Switch as ArkSwitch } from '@ark-ui/react/switch'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const SwitchRoot = forwardRef<HTMLLabelElement, SwitchProps>(
  ({ className, theme: propsTheme, craft, ui, children, ...props }, ref) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvSwitch', craft)
    const crafts = useCraft(themed, 'tvSwitch')

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkSwitch.Root
          ref={ref}
          className={crafts.root(cxc(ui?.root, className))}
          {...props}
        >
          <ArkSwitch.Control className={crafts.control(cxc(ui?.control))}>
            <ArkSwitch.Thumb className={crafts.thumb(cxc(ui?.thumb))} />
          </ArkSwitch.Control>
          {children}
          <ArkSwitch.HiddenInput />
        </ArkSwitch.Root>
      </ProvideComponentTheme>
    )
  },
)

SwitchRoot.displayName = 'Switch'
