// packages/vue/core/src/components/switch/SwitchLabel.vue
<script setup lang="ts">
import type { SwitchLabelProps } from '.'
import { Switch } from '@ark-ui/vue/switch'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const { class: propsClass, theme: propsTheme, asChild } = defineProps<SwitchLabelProps>()

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvSwitch')
</script>

<template>
  <Switch.Label
    :class="crafts.label(cxc(propsClass))"
    :as-child="asChild"
  >
    <slot />
  </Switch.Label>
</template>

// packages/react/core/src/components/switch/SwitchLabel.tsx
import type { SwitchLabelProps } from './props'
import { Switch as ArkSwitch } from '@ark-ui/react/switch'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const SwitchLabel = forwardRef<HTMLSpanElement, SwitchLabelProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvSwitch')

    return (
      <ArkSwitch.Label
        ref={ref}
        className={crafts.label(cxc(className))}
        {...props}
      >
        {children}
      </ArkSwitch.Label>
    )
  },
)

SwitchLabel.displayName = 'Switch.Label'
