// packages/react/core/src/components/pin-input/PinInput.tsx
import type { ReactNode } from 'react'
import type { PinInputProps } from './props'
import { PinInput as ArkPinInput } from '@ark-ui/react/pin-input'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, Fragment } from 'react'

function gapAt(separator: PinInputProps['separator'], index: number): ReactNode {
  if (separator == null || index <= 0)
    return null
  if (Array.isArray(separator))
    return separator[index - 1]
  return separator
}

export const PinInput = forwardRef<HTMLDivElement, PinInputProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      ui,
      count = 4,
      separator,
      size,
      label,
      prefix,
      suffix,
      ...props
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvPinInput', craft)
    const crafts = useCraft(themed, 'tvPinInput', size != null ? { size } : undefined)
    const cells = Array.from({ length: count }, (_, index) => index)
    const showLabel = label != null && label !== ''

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkPinInput.Root
          ref={ref}
          className={crafts.root(cxc(ui?.root, className))}
          count={count}
          {...props}
        >
          {showLabel && (
            <ArkPinInput.Label className={crafts.label(cxc(ui?.label))}>
              {label}
            </ArkPinInput.Label>
          )}
          <ArkPinInput.Control className={crafts.control(cxc(ui?.control))}>
            {prefix}
            {cells.map((index) => {
              const gap = gapAt(separator, index)
              return (
                <Fragment key={index}>
                  {gap != null && gap !== false && gap !== '' && (
                    <span
                      className={crafts.separator(cxc(ui?.separator))}
                      aria-hidden="true"
                    >
                      {gap}
                    </span>
                  )}
                  <ArkPinInput.Input
                    className={crafts.input(cxc(ui?.input))}
                    index={index}
                  />
                </Fragment>
              )
            })}
            {suffix}
          </ArkPinInput.Control>
          <ArkPinInput.HiddenInput />
        </ArkPinInput.Root>
      </ProvideComponentTheme>
    )
  },
)

PinInput.displayName = 'PinInput'

// packages/vue/core/src/components/pin-input/PinInput.vue
<script setup lang="ts">
import type { PinInputRootEmits } from '@ark-ui/vue/pin-input'
import type { PinInputProps } from '.'

import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { PinInput, usePinInput } from '@ark-ui/vue/pin-input'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme } from '@raxium/vue/composables'
import { computed } from 'vue'

const {
  class: propsClass,
  theme: propsTheme,
  craft,
  count = 4,
  separator,
  ui,
  ...props
} = defineProps<PinInputProps>()
const emits = defineEmits<PinInputRootEmits>()

const forwarded = useForwardProps(computed(() => ({ ...props, count })))
const pinInput = usePinInput(forwarded, emits)

// theme
const theme = useTheme(
  () => propsTheme,
  undefined,
  () => craft,
)
const crafts = useCraft(theme, 'tvPinInput')
// expose
defineExpose({ $api: pinInput })
useForwardExpose()
</script>

<template>
  <PinInput.RootProvider
    :value="pinInput"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <PinInput.Label
      v-if="$slots.label"
      :class="crafts.label(cxc(ui?.label))"
    >
      <slot name="label" />
    </PinInput.Label>
    <PinInput.Control :class="crafts.control(cxc(ui?.control))">
      <slot name="prefix" />
      <slot name="default" :count="count">
        <template
          v-for="(num, index) in count"
          :key="num"
        >
          <slot name="separator" :number="num" :index="index">
            <span
              v-if="separator && index > 0"
              :class="crafts.separator(cxc(ui?.separator))"
              aria-hidden="true"
            >
              {{ separator }}
            </span>
          </slot>
          <PinInput.Input
            :index="index"
            :class="crafts.input(cxc(ui?.input))"
          />
        </template>
      </slot>
      <slot name="suffix" />
    </PinInput.Control>
    <PinInput.HiddenInput />
  </PinInput.RootProvider>
</template>
