// packages/vue/core/src/components/date-picker/DatePicker.vue
<script setup lang="ts">
import type { UseDatePickerProps } from '@ark-ui/vue'
import type { DatePickerProps, DatePickerRootEmits } from '.'
import { DatePicker, useDatePicker, useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { useConfig } from '@raxium/vue/composables/useConfig'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { useTheme } from '@raxium/vue/composables/useTheme'
import { defaults } from 'es-toolkit/compat'
import { computed, mergeProps } from 'vue'

const {
  theme: themeProps,
  lazyMount,
  unmountOnExit,
  craft,
  ...props
} = defineProps<DatePickerProps>()
const emit = defineEmits<DatePickerRootEmits>()

const datePickerOptions = useConfig('date-picker', () => ({ unmountOnExit, lazyMount }))
const forwarded = useForwardProps<DatePickerProps, UseDatePickerProps>(props)
const datePicker = useDatePicker(
  computed(
    () =>
      mergeProps(forwarded.value as Record<string, unknown>, {
        positioning: defaults(
          { ...(forwarded.value.positioning ?? {}) },
          { placement: datePickerOptions.value?.placement },
        ),
      }) as UseDatePickerProps,
  ),
  emit,
)

// theme
const theme = useTheme(
  () => themeProps,
  () => datePickerOptions.value?.theme,
  () => craft,
)
useProvideComponentTheme(theme, () => themeProps)
// expose
defineExpose({ $api: datePicker })
useForwardExpose()
</script>

<template>
  <DatePicker.RootProvider
    :value="datePicker"
    :lazy-mount="datePickerOptions?.lazyMount"
    :unmount-on-exit="datePickerOptions?.unmountOnExit"
  >
    <slot />
  </DatePicker.RootProvider>
</template>

// packages/react/core/src/components/date-picker/DatePicker.tsx
import type { DatePickerProps } from './props'
import { DatePicker as ArkDatePicker } from '@ark-ui/react/date-picker'
import { useConfig } from '@raxium/react/hooks/useConfig'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { defaults } from 'es-toolkit/compat'
import { forwardRef, useMemo } from 'react'

export const DatePickerRoot = forwardRef<HTMLDivElement, DatePickerProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      lazyMount,
      unmountOnExit,
      positioning,
      children,
      ...props
    },
    ref,
  ) => {
    const datePickerOptions = useConfig('date-picker', { lazyMount, unmountOnExit })
    const mergedPositioning = useMemo(
      () => defaults({ ...(positioning ?? {}) }, { placement: datePickerOptions?.placement }),
      [datePickerOptions?.placement, positioning],
    )
    const theme = useTheme(propsTheme, datePickerOptions?.theme)
    const themed = useThemeCraft(theme, 'tvDatePicker', craft)
    const crafts = useCraft(themed, 'tvDatePicker')

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkDatePicker.Root
          ref={ref}
          className={crafts.root(cxc(className))}
          lazyMount={datePickerOptions?.lazyMount}
          unmountOnExit={datePickerOptions?.unmountOnExit}
          positioning={mergedPositioning}
          {...props}
        >
          {children}
        </ArkDatePicker.Root>
      </ProvideComponentTheme>
    )
  },
)

DatePickerRoot.displayName = 'DatePicker'
