// packages/vue/core/src/components/date-picker/DatePickerContent.vue
<script setup lang="ts">
import type { DatePickerContentProps, DatePickerContentProvide } from '.'
import { DatePicker } from '@ark-ui/vue'
import { ark } from '@ark-ui/vue/factory'
import { useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import {
  useCraft,
  useProvideStructuralComponentTheme,
  useTeleportDetection,
  useTeleportedDepthOwner,
} from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'
import { findVNodeByName, findVNodesByName } from '@raxium/vue/utils/vnode'
import { compact, isNil } from 'es-toolkit'
import { computed, provide, useSlots } from 'vue'
import { DATE_PICKER_CONTENT_PROVIDE_KEY } from '.'

const { class: propsClass, theme: propsTheme, ...props } = defineProps<DatePickerContentProps>()
const forwarded = useForwardProps(props)

const slots = useSlots()
const defaultSlots = computed(() => slots.default?.())
const viewsState = computed(() => {
  const state = {
    count: 0,
    hasDayView: false,
    hasMonthView: false,
    hasYearView: false,
  }
  state.count = compact(
    ['DatePickerDayView', 'DatePickerMonthView', 'DatePickerYearView'].map((name) => {
      return findVNodesByName(defaultSlots.value, name).length > 0
    }),
  ).length
  state.hasDayView = !isNil(findVNodeByName(defaultSlots.value, 'DatePickerDayView'))
  state.hasMonthView = !isNil(findVNodeByName(defaultSlots.value, 'DatePickerMonthView'))
  state.hasYearView = !isNil(findVNodeByName(defaultSlots.value, 'DatePickerYearView'))
  return state
})

// teleport detection
const { isTeleported, setElementRef: setPositionerRef } = useTeleportDetection()
const depth = useTeleportedDepthOwner({
  type: 'popover',
  active: isTeleported,
  fallbackZIndex: 'var(--z-popover, var(--z-index))',
})

// theme
const theme = useInheritedTheme(() => propsTheme)
useProvideStructuralComponentTheme(theme, () => propsTheme)
const crafts = useCraft(theme, 'tvDatePicker')
const positionerStyle = computed(() => ({
  '--rui-z-index': isTeleported.value ? depth.zIndex.value : 'auto',
}))

// provide
provide<DatePickerContentProvide>(DATE_PICKER_CONTENT_PROVIDE_KEY, { viewsState })
</script>

<template>
  <DatePicker.Positioner
    :ref="setPositionerRef"
    :style="positionerStyle"
  >
    <DatePicker.Content
      v-bind="forwarded"
      :class="crafts.content(cxc(propsClass))"
    >
      <slot name="prefix" />
      <ark.div
        :class="crafts.contentInner()"
        data-scope="date-picker"
        data-part="content-inner"
      >
        <slot />
      </ark.div>
      <slot name="suffix" />
    </DatePicker.Content>
  </DatePicker.Positioner>
</template>

// packages/react/core/src/components/date-picker/DatePickerContent.tsx
import type { CSSProperties } from 'react'
import type { DatePickerContentProps } from './props'
import { DatePicker as ArkDatePicker } from '@ark-ui/react/date-picker'
import { ark } from '@ark-ui/react/factory'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useTeleportedDepthOwner } from '@raxium/react/hooks/useDepth'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTeleportDetection } from '@raxium/react/hooks/useTeleportDetection'
import { useComposedRefs } from '@raxium/react/utils'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useMemo } from 'react'
import { collectDatePickerViews } from './collect-views'
import { DatePickerContentContext } from './date-picker-content-context'

export const DatePickerContent = forwardRef<HTMLDivElement, DatePickerContentProps>(
  ({ className, theme: propsTheme, prefix, suffix, children, ...props }, ref) => {
    const { isTeleported, setElementRef } = useTeleportDetection()
    const depth = useTeleportedDepthOwner({
      type: 'popover',
      active: isTeleported,
      fallbackZIndex: 'var(--z-popover, var(--z-index))',
    })
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvDatePicker')
    const viewsState = useMemo(() => collectDatePickerViews(children), [children])
    const positionerRef = useComposedRefs(setElementRef, ref)

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <DatePickerContentContext.Provider value={viewsState}>
          <ArkDatePicker.Positioner
            ref={positionerRef}
            style={
              {
                '--rui-z-index': isTeleported ? depth.zIndex : 'auto',
              } as CSSProperties
            }
          >
            <ArkDatePicker.Content
              className={crafts.content(cxc(className))}
              {...props}
            >
              {prefix}
              <ark.div
                className={crafts.contentInner()}
                data-scope="date-picker"
                data-part="content-inner"
              >
                {children}
              </ark.div>
              {suffix}
            </ArkDatePicker.Content>
          </ArkDatePicker.Positioner>
        </DatePickerContentContext.Provider>
      </ProvideStructuralComponentTheme>
    )
  },
)

DatePickerContent.displayName = 'DatePicker.Content'
