// packages/vue/core/src/components/collapsible/Collapsible.vue
<script setup lang="ts">
import type { CollapsibleRootEmits } from '@ark-ui/vue/collapsible'
import type { CollapsibleProps } from '.'
import { Collapsible, useCollapsible } from '@ark-ui/vue/collapsible'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { useTheme } from '@raxium/vue/composables/useTheme'

const {
  class: propsClass,
  theme: propsTheme,
  asChild,
  craft,
  ...props
} = defineProps<CollapsibleProps>()
const emit = defineEmits<CollapsibleRootEmits>()
const forwarded = useForwardProps(props)
const collapsiable = useCollapsible(forwarded, emit)

// theme
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvCollapsible', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvCollapsible')

// expose
defineExpose({ $api: collapsiable })
useForwardExpose()
</script>

<template>
  <Collapsible.RootProvider
    :value="collapsiable"
    :class="crafts.root(cxc(propsClass))"
  >
    <slot v-bind="collapsiable" />
  </Collapsible.RootProvider>
</template>

// packages/react/core/src/components/collapsible/Collapsible.tsx
import type { CollapsibleProps } from './props'
import { Collapsible as ArkCollapsible } from '@ark-ui/react/collapsible'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const CollapsibleRoot = forwardRef<HTMLDivElement, CollapsibleProps>(
  ({ className, theme: propsTheme, craft, children, ...props }, ref) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvCollapsible', craft)
    const crafts = useCraft(themed, 'tvCollapsible')

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkCollapsible.Root
          ref={ref}
          className={crafts.root(cxc(className))}
          {...props}
        >
          {children}
        </ArkCollapsible.Root>
      </ProvideComponentTheme>
    )
  },
)

CollapsibleRoot.displayName = 'Collapsible'
