// packages/vue/core/src/components/collapsible/CollapsibleContent.vue
<script setup lang="ts">
import type { CollapsibleContentProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Collapsible } from '@ark-ui/vue/collapsible'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'

const {
  class: propsClass,
  theme: propsTheme,
  ...props
} = defineProps<CollapsibleContentProps>()
const forwarded = useForwardProps(props)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvCollapsible')
</script>

<template>
  <Collapsible.Content
    v-bind="forwarded"
    :class="crafts.content(cxc(propsClass))"
  >
    <slot />
  </Collapsible.Content>
</template>

// packages/react/core/src/components/collapsible/CollapsibleContent.tsx
import type { CollapsibleContentProps } from './props'
import { Collapsible as ArkCollapsible } from '@ark-ui/react/collapsible'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const CollapsibleContent = forwardRef<HTMLDivElement, CollapsibleContentProps>(
  ({ className, theme: propsTheme, children, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvCollapsible')

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <ArkCollapsible.Content
          ref={ref}
          className={crafts.content(cxc(className))}
          {...props}
        >
          {children}
        </ArkCollapsible.Content>
      </ProvideStructuralComponentTheme>
    )
  },
)

CollapsibleContent.displayName = 'Collapsible.Content'
