// packages/vue/core/src/components/collapsible/CollapsibleTrigger.vue
<script setup lang="ts">
import type { CollapsibleTriggerProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Collapsible, useCollapsibleContext } from '@ark-ui/vue/collapsible'
import { ChevronDown } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useInheritedTheme } from '@raxium/vue/composables/useInheritedTheme'

const {
  class: propsClass,
  theme: propsTheme,
  indicator = true,
  ui,
  ...props
} = defineProps<CollapsibleTriggerProps>()
const forwarded = useForwardProps(props)
const context = useCollapsibleContext()

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvCollapsible')
</script>

<template>
  <Collapsible.Trigger
    v-bind="forwarded"
    :class="crafts.trigger(cxc(ui?.root, propsClass))"
  >
    <slot v-bind="{ open: context.open, visible: context.visible }" />
    <slot
      name="indicator"
      v-bind="{ open: context.open, visible: context.visible }"
    >
      <Collapsible.Indicator
        v-if="indicator"
        :class="crafts.indicator(cxc(ui?.indicator))"
      >
        <ChevronDown />
      </Collapsible.Indicator>
    </slot>
  </Collapsible.Trigger>
</template>

// packages/react/core/src/components/collapsible/CollapsibleTrigger.tsx
import type { CollapsibleTriggerProps } from './props'
import { Collapsible as ArkCollapsible } from '@ark-ui/react/collapsible'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { ChevronDown } from 'lucide-react'
import { forwardRef } from 'react'

export const CollapsibleTrigger = forwardRef<HTMLButtonElement, CollapsibleTriggerProps>(
  ({
    className,
    theme: propsTheme,
    indicator = true,
    ui,
    children,
    ...props
  }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvCollapsible')

    return (
      <ArkCollapsible.Trigger
        ref={ref}
        className={crafts.trigger(cxc(ui?.root, className))}
        {...props}
      >
        {children}
        {indicator !== false && (
          <ArkCollapsible.Indicator className={crafts.indicator(cxc(ui?.indicator))}>
            {indicator === true ? <ChevronDown /> : indicator}
          </ArkCollapsible.Indicator>
        )}
      </ArkCollapsible.Trigger>
    )
  },
)

CollapsibleTrigger.displayName = 'Collapsible.Trigger'
