// packages/react/core/src/components/rating-group/RatingGroup.tsx
import type { RatingGroupProps } from './props'
import { RatingGroup as ArkRatingGroup } from '@ark-ui/react/rating-group'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const RatingGroupRoot = forwardRef<HTMLDivElement, RatingGroupProps>(
  ({ className, theme: propsTheme, craft, ui, prefix, suffix, children, ...props }, ref) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvRatingGroup', craft)
    const crafts = useCraft(themed, 'tvRatingGroup')

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkRatingGroup.Root
          ref={ref}
          className={crafts.root(cxc(ui?.root, className))}
          {...props}
        >
          {prefix}
          <ArkRatingGroup.Control className={crafts.control(cxc(ui?.control))}>
            {children}
          </ArkRatingGroup.Control>
          {suffix}
        </ArkRatingGroup.Root>
      </ProvideComponentTheme>
    )
  },
)

RatingGroupRoot.displayName = 'RatingGroup'

// packages/vue/core/src/components/rating-group/RatingGroup.vue
<script setup lang="ts">
import type { RatingGroupRootEmits } from '@ark-ui/vue/rating-group'
import type { RatingGroupProps } from '.'
import { RatingGroup, useRatingGroup } from '@ark-ui/vue/rating-group'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue/utils'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'

const { class: propsClass, theme: propsTheme, craft, ui, ...props } = defineProps<RatingGroupProps>()
const emit = defineEmits<RatingGroupRootEmits>()
const ratingGroup = useRatingGroup(useForwardProps(props), emit)

// theme
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvRatingGroup', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvRatingGroup')

// expose
defineExpose({ $api: ratingGroup })
useForwardExpose()
</script>

<template>
  <RatingGroup.RootProvider
    :value="ratingGroup"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <slot name="prefix" />
    <RatingGroup.Control :class="crafts.control(cxc(ui?.control))">
      <slot :items="ratingGroup.items" />
    </RatingGroup.Control>
    <slot name="suffix" />
  </RatingGroup.RootProvider>
</template>
