// packages/react/core/src/components/tabs/examples/disabled-and-no-indicator.tsx
import { Tabs } from '../index'

export function TabsDisabledAndNoIndicatorExample() {
  return (
    <Tabs defaultValue="tab-1">
      <Tabs.List className="w-80">
        <Tabs.Trigger value="tab-1">
          Tab 1
        </Tabs.Trigger>
        <Tabs.Trigger value="tab-2" disabled>
          Tab 2 (disabled)
        </Tabs.Trigger>
        <Tabs.Trigger value="tab-3">
          Tab 3
        </Tabs.Trigger>
      </Tabs.List>
      <Tabs.Content value="tab-1">
        Content 1
      </Tabs.Content>
      <Tabs.Content value="tab-2">
        You shouldn't see this
      </Tabs.Content>
      <Tabs.Content value="tab-3">
        Content 3
      </Tabs.Content>
    </Tabs>
  )
}

// packages/vue/core/src/components/tabs/examples/disabled-and-no-indicator.vue
<script setup lang="ts">
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../index'
</script>

<template>
  <Tabs default-value="tab-1">
    <TabsList class="w-80">
      <TabsTrigger value="tab-1">
        Tab 1
      </TabsTrigger>
      <TabsTrigger value="tab-2" disabled>
        Tab 2 (disabled)
      </TabsTrigger>
      <TabsTrigger value="tab-3">
        Tab 3
      </TabsTrigger>
    </TabsList>

    <TabsContent value="tab-1">
      Content 1
    </TabsContent>
    <TabsContent value="tab-2">
      You shouldn't see this
    </TabsContent>
    <TabsContent value="tab-3">
      Content 3
    </TabsContent>
  </Tabs>
</template>
