// packages/react/core/src/components/tabs/examples/scrollable-list.tsx
import { Tabs } from '../index'

const items = Array.from({ length: 12 }, (_, i) => {
  const n = i + 1
  return { value: `tab-${n}`, label: `Tab ${n}`, content: `Content ${n}` }
})

export function TabsScrollableListExample() {
  return (
    <Tabs defaultValue="tab-7">
      <Tabs.List className="w-80">
        {items.map(item => (
          <Tabs.Trigger key={item.value} value={item.value}>
            {item.label}
          </Tabs.Trigger>
        ))}
        <Tabs.Indicator />
      </Tabs.List>
      {items.map(item => (
        <Tabs.Content key={item.value} value={item.value}>
          {item.content}
        </Tabs.Content>
      ))}
    </Tabs>
  )
}

// packages/vue/core/src/components/tabs/examples/scrollable-list.vue
<script setup lang="ts">
import { Tabs, TabsContent, TabsIndicator, TabsList, TabsTrigger } from '../index'
</script>

<template>
  <Tabs default-value="tab-7">
    <TabsList class="w-80">
      <TabsTrigger v-for="index in 12" :key="index" :value="`tab-${index}`">
        Tab {{ index }}
      </TabsTrigger>
      <TabsIndicator />
    </TabsList>
    <TabsContent v-for="index in 12" :key="index" :value="`tab-${index}`">
      Content {{ index }}
    </TabsContent>
  </Tabs>
</template>
