// packages/vue/core/src/components/tags-input/examples/programmatic.vue
<script setup lang="ts">
import { TagsInput as ArkTagsInput } from '@ark-ui/vue/tags-input'
import { X } from '@lucide/vue'
import { ref } from 'vue'
import { Button } from '../../button'
import { TagsInput, TagsInputItem } from '../index'

const value = ref<string[]>(['vue', 'react'])
const tagsRef = ref<any>(null)
</script>

<template>
  <div class="w-full flex flex-col gap-3">
    <div class="flex flex-wrap items-center gap-2">
      <Button variant="outlined" @click="tagsRef?.$api?.focus()">
        Focus
      </Button>
      <Button variant="outlined" @click="tagsRef?.$api?.addValue('solid')">
        Add solid
      </Button>
      <Button variant="outlined" @click="tagsRef?.$api?.setValue(['vue', 'svelte'])">
        Set [vue, svelte]
      </Button>
      <Button variant="outlined" @click="tagsRef?.$api?.clearValue()">
        Clear
      </Button>
      <div class="text-sm text-gray-cc">
        value: <span class="text-gray-ff">{{ value.join(', ') || '(empty)' }}</span>
      </div>
    </div>

    <div class="w-full max-w-[560px] rounded-md border border-gray-33 p-3">
      <TagsInput ref="tagsRef" v-model="value">
        <template #default="{ items }">
          <TagsInputItem
            v-for="(v, index) in items"
            :key="`${v}-${index}`"
            :index="index"
            :value="v"
          >
            <ArkTagsInput.ItemDeleteTrigger class="ml-1 text-gray-55 hover:text-gray-ff">
              <X class="size-3.5" />
            </ArkTagsInput.ItemDeleteTrigger>
          </TagsInputItem>
        </template>
      </TagsInput>
    </div>
  </div>
</template>

// packages/react/core/src/components/tags-input/examples/programmatic.tsx
import { X } from 'lucide-react'
import { Button } from '../../button'
import { TagsInput, useTagsInputContext } from '../index'

function TagsInputToolbar() {
  const api = useTagsInputContext()

  return (
    <div className="mb-2 flex flex-wrap items-center gap-2">
      <Button variant="outlined" onClick={() => api.focus()}>
        Focus
      </Button>
      <Button variant="outlined" onClick={() => api.addValue('solid')}>
        Add solid
      </Button>
      <Button variant="outlined" onClick={() => api.setValue(['vue', 'svelte'])}>
        Set [vue, svelte]
      </Button>
      <Button variant="outlined" onClick={() => api.clearValue()}>
        Clear
      </Button>
      <div className="text-sm text-gray-cc">
        value:
        {' '}
        <span className="text-gray-ff">{api.value.join(', ') || '(empty)'}</span>
      </div>
    </div>
  )
}

function TagsInputItems() {
  const { value } = useTagsInputContext()

  return value.map((item, index) => (
    <TagsInput.Item key={`${item}-${index}`} index={index} value={item}>
      <TagsInput.ItemDeleteTrigger className="ml-1 text-gray-55 hover:text-gray-ff">
        <X className="size-3.5" />
      </TagsInput.ItemDeleteTrigger>
    </TagsInput.Item>
  ))
}

export function TagsInputProgrammaticExample() {
  return (
    <div className="w-full flex flex-col gap-3">
      <div className="w-full max-w-[560px] rounded-md border border-gray-33 p-3">
        <TagsInput defaultValue={['vue', 'react']} prefix={<TagsInputToolbar />}>
          <TagsInputItems />
        </TagsInput>
      </div>
    </div>
  )
}
