// packages/react/core/src/components/tags-input/TagsInput.tsx
import type { TagsInputProps } from './props'
import { TagsInput as ArkTagsInput, useTagsInputContext } from '@ark-ui/react/tags-input'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useEffect, useMemo, useRef } from 'react'
import { ScrollArea } from '../scroll-area'
import { TagsInputInlineProvider } from './tags-input-inline-context'

function TagsInputControl({
  inline,
  ui,
  children,
}: {
  inline: boolean
  ui: TagsInputProps['ui']
  children: TagsInputProps['children']
}) {
  const tagsInput = useTagsInputContext()
  const theme = useInheritedTheme()
  const empty = tagsInput.value.length === 0
  const variants = useMemo(() => ({ inline, empty }), [inline, empty])
  const crafts = useCraft(theme, 'tvTagsInput', variants)
  const inputCrafts = useCraft(theme, 'tvInput')
  const viewportRef = useRef<HTMLDivElement>(null)
  const previousLengthRef = useRef(tagsInput.value.length)
  const scrollbarSize = theme.size === 'sm' ? 'xs' : 'sm'

  useEffect(() => {
    const nextLength = tagsInput.value.length
    if (nextLength > previousLengthRef.current) {
      viewportRef.current?.scrollTo({
        left: 9999,
        behavior: 'smooth',
      })
    }
    previousLengthRef.current = nextLength
  }, [tagsInput.value.length])

  return (
    <ArkTagsInput.Control className={inputCrafts.root(cxc(crafts.control(), ui?.control))}>
      {inline
        ? (
            <ScrollArea className={crafts.scrollArea()}>
              <ScrollArea.Viewport ref={viewportRef} ui={{ content: crafts.scrollAreaContent() }}>
                {children}
              </ScrollArea.Viewport>
              <ScrollArea.Scrollbar
                orientation="horizontal"
                theme={{ size: scrollbarSize }}
              />
            </ScrollArea>
          )
        : children}
      <ArkTagsInput.Input className={inputCrafts.input(cxc(crafts.input(), ui?.input))} />
    </ArkTagsInput.Control>
  )
}

export const TagsInputRoot = forwardRef<HTMLDivElement, TagsInputProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      inline = true,
      ui,
      prefix,
      suffix,
      children,
      ...props
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvTagsInput', craft)
    const crafts = useCraft(themed, 'tvTagsInput', { inline })

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <TagsInputInlineProvider value={inline}>
          <ArkTagsInput.Root
            ref={ref}
            className={crafts.root(cxc(ui?.root, className))}
            {...props}
          >
            {prefix}
            <TagsInputControl inline={inline} ui={ui}>
              {children}
            </TagsInputControl>
            {suffix}
            <ArkTagsInput.HiddenInput />
          </ArkTagsInput.Root>
        </TagsInputInlineProvider>
      </ProvideComponentTheme>
    )
  },
)

TagsInputRoot.displayName = 'TagsInput'

// packages/vue/core/src/components/tags-input/TagsInput.vue
<script setup lang="ts">
import type { TagsInputRootEmits } from '@ark-ui/vue/tags-input'
import type { TagsInputProps } from '.'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { TagsInput, useTagsInput } from '@ark-ui/vue/tags-input'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { computed, nextTick, provide, useTemplateRef, watch } from 'vue'
import { TAGS_INPUT_PROVIDE_KEY } from '.'
import { ScrollArea, ScrollAreaScrollbar } from '../scroll-area'

const {
  class: propsClass,
  theme: propsTheme,
  craft,
  inline = true,
  ui,
  ...props
} = defineProps<TagsInputProps>()
const emits = defineEmits<TagsInputRootEmits>()
const forwarded = useForwardProps(props)
const tagsInput = useTagsInput(forwarded, emits)

const scrollAreaRef = useTemplateRef('scrollArea')
watch(
  () => tagsInput.value.value,
  (newValue, oldValue) => {
    nextTick(() => {
      if (newValue.length > oldValue.length) {
        // add items
        scrollAreaRef.value?.$el.querySelector('[data-part="viewport"]')?.scrollTo({
          left: 9999,
          behavior: 'smooth',
        })
      }
    })
  },
)

// theme
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvTagsInput', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const inputCrafts = useCraft(themed, 'tvInput')
const crafts = useCraft(themed, 'tvTagsInput', () => ({
  inline,
  empty: tagsInput.value.value.length === 0,
}))

// provide
provide(TAGS_INPUT_PROVIDE_KEY, {
  inline: computed(() => inline),
})

// expose
defineExpose({ $api: tagsInput })
useForwardExpose()
</script>

<template>
  <TagsInput.RootProvider
    :value="tagsInput"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <slot name="prefix" />
    <TagsInput.Control :class="inputCrafts.root(cxc(crafts.control(), ui?.control))">
      <ScrollArea
        v-if="inline"
        ref="scrollArea"
        :class="crafts.scrollArea()"
        :ui="{ content: crafts.scrollAreaContent() }"
      >
        <slot :items="tagsInput.value" />
        <ScrollAreaScrollbar
          orientation="horizontal"
          :theme="{ size: theme.size === 'sm' ? 'xs' : 'sm' }"
        />
      </ScrollArea>
      <slot
        v-else
        :items="tagsInput.value"
      />
      <TagsInput.Input :class="inputCrafts.input(cxc(crafts.input(), ui?.input))" />
    </TagsInput.Control>
    <slot name="suffix" />    <TagsInput.HiddenInput />
  </TagsInput.RootProvider>
</template>
