// packages/react/core/src/components/tags-input/TagsInputItem.tsx
import type { ReactNode, RefObject } from 'react'
import type { TagsInputItemProps } from './props'
import { TagsInput as ArkTagsInput, useTagsInputItemContext } from '@ark-ui/react/tags-input'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useEffect, useMemo, useRef } from 'react'
import { useTagsInputInline } from './tags-input-inline-context'

export const TagsInputItem = forwardRef<HTMLDivElement, TagsInputItemProps>(
  ({ className, theme: propsTheme, ui, value, children, ...props }, ref) => {
    const inline = useTagsInputInline()
    const theme = useInheritedTheme(propsTheme)
    const variants = useMemo(() => ({ inline }), [inline])
    const crafts = useCraft(theme, 'tvTagsInput', variants)
    const inputCrafts = useCraft(theme, 'tvInput')
    const previewRef = useRef<HTMLDivElement>(null)

    return (
      <ArkTagsInput.Item
        ref={ref}
        className={crafts.item(cxc(ui?.root, className))}
        value={value}
        {...props}
      >
        <TagsInputItemPreview
          previewRef={previewRef}
          className={crafts.itemPreview(cxc(ui?.preview))}
        >
          <ArkTagsInput.ItemText className={crafts.itemText(cxc(ui?.text))}>
            {value}
          </ArkTagsInput.ItemText>
          {children}
        </TagsInputItemPreview>
        <ArkTagsInput.ItemInput className={inputCrafts.root(cxc(crafts.itemInput(), ui?.input))} />
      </ArkTagsInput.Item>
    )
  },
)

function TagsInputItemPreview({
  previewRef,
  className,
  children,
}: {
  previewRef: RefObject<HTMLDivElement | null>
  className?: string
  children: ReactNode
}) {
  const item = useTagsInputItemContext()

  useEffect(() => {
    if (item.highlighted) {
      previewRef.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' })
    }
  }, [item.highlighted, previewRef])

  return (
    <ArkTagsInput.ItemPreview ref={previewRef} className={className}>
      {children}
    </ArkTagsInput.ItemPreview>
  )
}

TagsInputItem.displayName = 'TagsInput.Item'

// packages/vue/core/src/components/tags-input/TagsInputItem.vue
<script setup lang="ts">
import type { TagsInputItemProps, TagsInputProvide } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { TagsInput, useTagsInputContext } from '@ark-ui/vue/tags-input'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'
import { computed, inject, useTemplateRef, watchEffect } from 'vue'
import { TAGS_INPUT_PROVIDE_KEY } from '.'

const { class: propsClass, theme: propsTheme, ui, ...props } = defineProps<TagsInputItemProps>()
const { inline } = inject<TagsInputProvide>(TAGS_INPUT_PROVIDE_KEY, {
  inline: computed(() => true),
})
const forwarded = useForwardProps(props)
const context = useTagsInputContext()
const itemsState = computed(() => context.value.getItemState(forwarded.value))

const preview = useTemplateRef('preview')
watchEffect(
  () => {
    if (itemsState.value.highlighted) {
      preview.value?.$el.scrollIntoView({ behavior: 'smooth', block: 'nearest' })
    }
  },
  { flush: 'post' },
)

// theme
const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvTagsInput', () => ({ inline: inline.value }))
const inputCrafts = useCraft(theme, 'tvInput')
</script>

<template>
  <TagsInput.Item
    v-bind="forwarded"
    :class="crafts.item(cxc(ui?.root, propsClass))"
  >
    <TagsInput.ItemPreview
      ref="preview"
      :class="crafts.itemPreview(cxc(ui?.preview))"
    >
      <TagsInput.ItemText :class="crafts.itemText(cxc(ui?.text))">
        {{ value }}
      </TagsInput.ItemText>
      <slot />
    </TagsInput.ItemPreview>
    <TagsInput.ItemInput :class="inputCrafts.root(cxc(crafts.itemInput(), ui?.input))" />
  </TagsInput.Item>
</template>
