// packages/vue/core/src/components/checkbox/Checkbox.vue
<script setup lang="ts">
import type { CheckboxRootEmits, UseCheckboxProps, UseCheckboxReturn } from '@ark-ui/vue/checkbox'
import type { CheckboxProps, CheckedState } from './props'
import { Checkbox, useCheckbox } from '@ark-ui/vue/checkbox'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue/utils'
import { Check, Minus } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft } from '@raxium/vue/composables'
import { useTheme } from '@raxium/vue/composables/useTheme'

const {
  class: propsClass,
  theme: propsTheme,
  label,
  ui,
  craft,
  ...props
} = defineProps<CheckboxProps>()
const emit = defineEmits<CheckboxRootEmits>()
const slots = defineSlots<{
  indicator: (props: { checkedState: CheckedState }) => any
  label: () => any
}>()

const forwarded = useForwardProps<CheckboxProps, UseCheckboxProps>(props)
const checkbox = useCheckbox(forwarded, emit)

// theme
const theme = useTheme(
  () => propsTheme,
  undefined,
  () => craft,
)
const crafts = useCraft(theme, 'tvCheckbox', () => ({
  disabled: forwarded.value.disabled,
}))

// expose
defineExpose({ $api: checkbox as UseCheckboxReturn })
useForwardExpose()
</script>

<template>
  <Checkbox.RootProvider
    :value="checkbox"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <Checkbox.Control :class="crafts.control(cxc(ui?.control))">
      <Checkbox.Indicator :class="crafts.indicator(cxc(ui?.indicator))">
        <slot
          name="indicator"
          v-bind="{ checkedState: checkbox.checkedState }"
        >
          <Check :class="crafts.indicatorChecked()" />
        </slot>
      </Checkbox.Indicator>
      <Checkbox.Indicator
        :class="crafts.indicator(cxc(ui?.indicator))"
        indeterminate
      >
        <slot
          name="indicator"
          v-bind="{ checkedState: checkbox.checkedState }"
        >
          <Minus :class="crafts.indicatorMinus()" />
        </slot>
      </Checkbox.Indicator>
    </Checkbox.Control>
    <Checkbox.Label
      v-if="label || slots.label?.()"
      :class="crafts.label(cxc(ui?.label))"
      :as-child="!!label"
    >
      <slot name="label">
        <span>{{ label }}</span>
      </slot>
    </Checkbox.Label>
    <Checkbox.HiddenInput />
  </Checkbox.RootProvider>
</template>

// packages/react/core/src/components/checkbox/Checkbox.tsx
import type { ReactNode } from 'react'
import type { CheckboxProps } from './props'
import { Checkbox as ArkCheckbox } from '@ark-ui/react/checkbox'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { cxc } from '@raxium/themes/utils'
import { Check, Minus } from 'lucide-react'
import { cloneElement, forwardRef, isValidElement, useMemo } from 'react'

function renderIndicator(indicator: ReactNode | undefined, fallback: ReactNode) {
  if (indicator == null)
    return fallback
  if (isValidElement(indicator))
    return cloneElement(indicator)
  return indicator
}

export const CheckboxRoot = forwardRef<HTMLLabelElement, CheckboxProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      label,
      ui,
      indicator,
      disabled,
      ...props
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const variants = useMemo(() => ({ disabled }), [disabled])
    const crafts = useCraft(theme, 'tvCheckbox', variants, craft)
    const showLabel = label != null && label !== ''

    return (
      <ArkCheckbox.Root
        ref={ref}
        className={crafts.root(cxc(ui?.root, className))}
        disabled={disabled}
        {...props}
      >
        <ArkCheckbox.Control className={crafts.control(cxc(ui?.control))}>
          <ArkCheckbox.Indicator className={crafts.indicator(cxc(ui?.indicator))}>
            {renderIndicator(indicator, <Check className={crafts.indicatorChecked()} />)}
          </ArkCheckbox.Indicator>
          <ArkCheckbox.Indicator className={crafts.indicator(cxc(ui?.indicator))} indeterminate>
            {renderIndicator(indicator, <Minus className={crafts.indicatorMinus()} />)}
          </ArkCheckbox.Indicator>
        </ArkCheckbox.Control>
        {showLabel && (
          <ArkCheckbox.Label className={crafts.label(cxc(ui?.label))} asChild={typeof label === 'string'}>
            {typeof label === 'string' ? <span>{label}</span> : label}
          </ArkCheckbox.Label>
        )}
        <ArkCheckbox.HiddenInput />
      </ArkCheckbox.Root>
    )
  },
)

CheckboxRoot.displayName = 'Checkbox'
