// packages/react/core/src/components/message/Message.tsx
import type { MessageProps } from './props'
import { ark } from '@ark-ui/react/factory'
import {
  ToastCloseTrigger,
  ToastDescription,
  ToastRoot,
  useToastContext,
} from '@ark-ui/react/toast'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cn, cxc } from '@raxium/themes/utils'
import { CircleAlert, CircleCheck, CircleX, Info, LoaderCircle, X } from 'lucide-react'

function TypeIcon({ className, type }: { className?: string, type?: string }) {
  const props = { className, 'data-type': type }
  switch (type) {
    case 'success':
      return <CircleCheck {...props} />
    case 'error':
      return <CircleX {...props} />
    case 'warning':
      return <CircleAlert {...props} />
    case 'loading':
      return <LoaderCircle {...props} className={cn(className, 'animate-spin')} />
    case 'info':
    default:
      return <Info {...props} />
  }
}

export function Message({
  className,
  theme: propsTheme,
  options,
  ui,
  icon,
  close,
  ...props
}: MessageProps) {
  const toast = useToastContext()
  const theme = useInheritedTheme({ ...propsTheme, ...options?.theme })
  const crafts = useCraft(theme, 'tvMessage')
  const showClose = options.showClose !== false && toast.type !== 'loading'

  return (
    <ToastRoot className={crafts.root(cxc(ui?.root, className))} {...props}>
      <ark.div
        className={crafts.content(cxc(ui?.content))}
        data-scope="toast"
        data-part="content"
        data-placement={toast.placement}
        data-type={toast.type}
      >
        {options.render
          ? options.render()
          : (
              <>
                {icon ?? <TypeIcon className={crafts.icon(cxc(ui?.icon))} type={toast.type} />}
                {options.description != null && (
                  <ToastDescription className={crafts.description(cxc(ui?.description))}>
                    {options.description}
                  </ToastDescription>
                )}
                {showClose && (
                  close ?? (
                    <ToastCloseTrigger className={crafts.close(cxc(ui?.close))}>
                      <X />
                    </ToastCloseTrigger>
                  )
                )}
              </>
            )}
      </ark.div>
    </ToastRoot>
  )
}

Message.displayName = 'Message'

// packages/vue/core/src/components/message/Message.vue
<script lang="ts">
/**
 * deal with ts-2742
 */
import type * as toast from '@zag-js/toast'
import type {
  ComputedRef,
  CSSProperties,
  HTMLAttributes,
  NativeElements,
  ReservedProps,
  UnwrapRef,
} from 'vue'

type Attrs<T> = T & ReservedProps
type PropTypes = NativeElements & {
  element: Attrs<HTMLAttributes>
  style: CSSProperties
}
interface UseToastContext extends ComputedRef<toast.Api<PropTypes>> {}
</script>

<script setup lang="ts">
import type { MessageProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { ark } from '@ark-ui/vue/factory'
import { Toast, useToastContext } from '@ark-ui/vue/toast'
import { CircleAlert, CircleCheck, CircleX, Info, LoaderCircle, X } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'
import { computed, h } from 'vue'

const { class: propsClass, theme: propsTheme, options, ui, ...props } = defineProps<MessageProps>()
defineSlots<{
  default: (props: UnwrapRef<typeof slotBindings>) => any
  icon: (props: UnwrapRef<typeof slotBindings>) => any
  inner: (props: UnwrapRef<typeof slotBindings>) => any
  close: (props: UnwrapRef<typeof slotBindings>) => any
}>()
const forwarded = useForwardProps(props)
const messageContext: UseToastContext = useToastContext()
const slotBindings = computed(() => ({
  options,
  context: messageContext.value,
}))

const theme = useInheritedTheme(() => Object.assign({}, propsTheme, options?.theme))
const crafts = useCraft(theme, 'tvMessage')
const iconVNode = computed(() => {
  const className = crafts.value.icon(cxc(ui?.icon))
  switch (messageContext.value.type) {
    case 'info':
      return h(Info, {
        'class': className,
        'data-type': messageContext.value.type,
      })
    case 'success':
      return h(CircleCheck, {
        'class': className,
        'data-type': messageContext.value.type,
      })
    case 'error':
      return h(CircleX, {
        'class': className,
        'data-type': messageContext.value.type,
      })
    case 'warning':
      return h(CircleAlert, {
        'class': className,
        'data-type': messageContext.value.type,
      })
    case 'loading':
      return h(LoaderCircle, {
        'class': className,
        'data-type': messageContext.value.type,
      })
    default:
      return h(Info, {
        'class': className,
        'data-type': messageContext.value.type,
      })
  }
})
</script>

<template>
  <Toast.Root
    v-bind="forwarded"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <ark.div
      :class="crafts.content(cxc(ui?.content))"
      data-scope="toast"
      data-part="content"
      :data-placement="messageContext.placement"
      :data-type="messageContext.type"
    >
      <component
        :is="options?.render(messageContext)"
        v-if="options?.render"
      />
      <slot
        v-else
        name="default"
        v-bind="slotBindings"
      >
        <slot
          name="icon"
          v-bind="slotBindings"
        >
          <component :is="iconVNode" />
        </slot>
        <slot
          name="inner"
          v-bind="slotBindings"
        >
          <template v-if="typeof options?.description === 'function'">
            <component :is="options?.description(messageContext)" />
          </template>
          <template v-else-if="options?.description">
            <Toast.Description :class="crafts.description(cxc(ui?.description))">
              {{ options.description }}
            </Toast.Description>
          </template>
        </slot>
        <slot
          v-if="options?.showClose"
          name="close"
          v-bind="slotBindings"
        >
          <Toast.CloseTrigger
            v-if="messageContext.type !== 'loading'"
            :class="crafts.close(cxc(ui?.close))"
          >
            <X />
          </Toast.CloseTrigger>
        </slot>
      </slot>
    </ark.div>
  </Toast.Root>
</template>
