// packages/vue/core/src/components/tree/Tree.vue
<script setup lang="ts" generic="T extends TreeNode = TreeNode, V extends TreeValueType = TreeValueType">
import type { TreeNode } from '@ark-ui/vue/tree-view'
import type { TreeProps, TreeValueType, TreeViewRootEmits } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { TreeView, useTreeView } from '@ark-ui/vue/tree-view'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { provideTreeContext } from './tree-context'

const {
  class: propsClass,
  theme: propsTheme,
  craft,
  ui,
  ...props
} = defineProps<TreeProps<T, V>>()
const emits = defineEmits<TreeViewRootEmits<T, V>>()
const forwarded = useForwardProps<TreeProps<T, V>, any>(props)
const treeView = useTreeView<T>(forwarded, emits)

// theme（根节点统一 provide，供 TreeNode/TreeCheckboxNode inject，避免每节点 useTheme）
const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvTree', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvTree')

// context
provideTreeContext({
  branchCrafts: useCraft(themed, 'tvTreeBranch'),
  itemCrafts: useCraft(themed, 'tvTreeItem'),
  checkboxCrafts: useCraft(themed, 'tvCheckbox'),
})
</script>

<template>
  <TreeView.RootProvider
    :value="treeView"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <slot name="prefix" />
    <TreeView.Tree :class="crafts.tree(cxc(ui?.tree))">
      <slot />
    </TreeView.Tree>
    <slot name="suffix" />
  </TreeView.RootProvider>
</template>

// packages/react/core/src/components/tree/Tree.tsx
import type { TreeNode } from '@ark-ui/react/tree-view'
import type { TreeProps } from './props'
import { TreeView } from '@ark-ui/react/tree-view'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { TreeContextProvider } from './tree-context'

export function TreeRoot<T extends TreeNode>({
  className,
  theme: propsTheme,
  craft,
  ui,
  prefix,
  suffix,
  children,
  ...props
}: TreeProps<T>) {
  const theme = useTheme(propsTheme)
  const themed = useThemeCraft(theme, 'tvTree', craft)
  const crafts = useCraft(themed, 'tvTree')
  const branchCrafts = useCraft(themed, 'tvTreeBranch')
  const itemCrafts = useCraft(themed, 'tvTreeItem')
  const checkboxCrafts = useCraft(themed, 'tvCheckbox')

  return (
    <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
      <TreeContextProvider value={{ branchCrafts, itemCrafts, checkboxCrafts }}>
        <TreeView.Root className={crafts.root(cxc(ui?.root, className))} {...props}>
          {prefix}
          <TreeView.Tree className={crafts.tree(cxc(ui?.tree))}>
            {children}
          </TreeView.Tree>
          {suffix}
        </TreeView.Root>
      </TreeContextProvider>
    </ProvideComponentTheme>
  )
}

TreeRoot.displayName = 'Tree'
