// packages/vue/core/src/components/slider/Slider.vue
<script setup lang="ts">
import type { SliderRootEmits } from '@ark-ui/vue/slider'
import type { ComponentPublicInstance } from 'vue'
import type { SliderProps } from '.'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { Slider, useSlider } from '@ark-ui/vue/slider'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme, useThemeCraft } from '@raxium/vue/composables'
import { useProvideComponentTheme } from '@raxium/vue/composables/useProvideComponentTheme'
import { computed, useTemplateRef } from 'vue'
import SliderBoundaryProvider from './SliderBoundaryProvider.vue'

const { class: propsClass, theme: propsTheme, craft, ui, ...props } = defineProps<SliderProps>()
const emit = defineEmits<SliderRootEmits>()
const forwarded = useForwardProps(props)

const slider = useSlider(forwarded, emit)
const controlRef = useTemplateRef<ComponentPublicInstance | null>('control')
const controlEl = computed((): HTMLElement | undefined => {
  const root = controlRef.value?.$el
  return root instanceof HTMLElement ? root : undefined
})

const theme = useTheme(() => propsTheme)
const themed = useThemeCraft(theme, 'tvSlider', () => craft)
useProvideComponentTheme(themed, () => propsTheme)
const crafts = useCraft(themed, 'tvSlider', () => ({
  orientation: forwarded.value.orientation ?? 'horizontal',
}))

// expose
defineExpose({ $api: slider })
useForwardExpose()
</script>

<template>
  <Slider.RootProvider
    :value="slider"
    :class="
      crafts.root(cxc(ui?.root, propsClass))
    "
  >
    <SliderBoundaryProvider :boundary="controlEl">
      <slot name="prefix" />
      <Slider.Control
        ref="control"
        :class="
          crafts.control(cxc(ui?.control))
        "
      >
        <Slider.Track
          :class="
            crafts.track(cxc(ui?.track))
          "
        >
          <Slider.Range
            :class="
              crafts.range(cxc(ui?.range))
            "
          />
        </Slider.Track>
        <slot />
      </Slider.Control>
      <slot name="suffix" />
    </SliderBoundaryProvider>
  </Slider.RootProvider>
</template>

// packages/react/core/src/components/slider/Slider.tsx
import type { SliderProps } from './props'
import { Slider as ArkSlider } from '@ark-ui/react/slider'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { forwardRef, useCallback, useMemo, useState } from 'react'
import { SliderBoundaryProvider } from './slider-boundary-context'

export const SliderRoot = forwardRef<HTMLDivElement, SliderProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      ui,
      prefix,
      suffix,
      orientation = 'horizontal',
      children,
      ...props
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvSlider', craft)
    const variants = useMemo(() => ({ orientation }), [orientation])
    const crafts = useCraft(themed, 'tvSlider', variants)
    const [controlEl, setControlEl] = useState<HTMLElement | undefined>()
    const setControlRef = useCallback((node: HTMLDivElement | null) => {
      setControlEl(node ?? undefined)
    }, [])

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkSlider.Root
          ref={ref}
          className={crafts.root(cxc(ui?.root, className))}
          orientation={orientation}
          {...props}
        >
          <SliderBoundaryProvider value={controlEl}>
            {prefix}
            <ArkSlider.Control ref={setControlRef} className={crafts.control(cxc(ui?.control))}>
              <ArkSlider.Track className={crafts.track(cxc(ui?.track))}>
                <ArkSlider.Range className={crafts.range(cxc(ui?.range))} />
              </ArkSlider.Track>
              {children}
            </ArkSlider.Control>
            {suffix}
          </SliderBoundaryProvider>
        </ArkSlider.Root>
      </ProvideComponentTheme>
    )
  },
)

SliderRoot.displayName = 'Slider'
