// packages/vue/core/src/components/slider/SliderThumb.vue
<script setup lang="ts">
import type { SliderThumbProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Slider } from '@ark-ui/vue/slider'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useInheritedTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  ...props
} = defineProps<SliderThumbProps>()
const forwarded = useForwardProps(props)

const theme = useInheritedTheme(() => propsTheme)
const crafts = useCraft(theme, 'tvSlider')
</script>

<template>
  <Slider.Thumb
    v-bind="forwarded"
    :class="crafts.thumb(cxc(propsClass))"
    :data-theme-size="theme.size"
  >
    <Slider.HiddenInput />
  </Slider.Thumb>
</template>

// packages/react/core/src/components/slider/SliderThumb.tsx
import type { SliderThumbProps } from './props'
import { Slider as ArkSlider } from '@ark-ui/react/slider'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { cxc } from '@raxium/themes/utils'
import { forwardRef } from 'react'

export const SliderThumb = forwardRef<HTMLDivElement, SliderThumbProps>(
  ({ className, theme: propsTheme, ...props }, ref) => {
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvSlider')

    return (
      <ArkSlider.Thumb
        ref={ref}
        className={crafts.thumb(cxc(className))}
        data-theme-size={theme.size}
        {...props}
      >
        <ArkSlider.HiddenInput />
      </ArkSlider.Thumb>
    )
  },
)

SliderThumb.displayName = 'Slider.Thumb'
