// packages/vue/core/src/components/slider/SliderTooltipMarker.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import type { SliderTooltipMarkerProps } from '.'
import { useForwardProps } from '@ark-ui/vue'
import { Slider, useSliderContext } from '@ark-ui/vue/slider'
import { TooltipRootProvider, useTooltip } from '@ark-ui/vue/tooltip'
import { cxc } from '@raxium/themes/utils'
import { TooltipArrow, TooltipContent, TooltipTrigger } from '@raxium/vue/components/tooltip'
import { useCraft, useTheme } from '@raxium/vue/composables'
import { useConfig } from '@raxium/vue/composables/useConfig'
import { ThemeProvider } from '@raxium/vue/providers/theme'
import { pick } from 'es-toolkit'
import { merge } from 'es-toolkit/compat'
import { computed } from 'vue'
import { injectSliderBoundaryContext } from './SliderBoundaryProvider.vue'

const {
  theme: propsTheme,
  value,
  open, // tooltip prop
  class: propsClass,
  ui,
  widget,
  ...props
} = defineProps<SliderTooltipMarkerProps>()
const context = useSliderContext()

const boundary = injectSliderBoundaryContext()
const tooltipForwarded = useForwardProps(props)
const configs = useConfig('tooltip')
const tooltip = useTooltip(
  computed(() =>
    merge(
      {
        open: true,
        positioning: {
          boundary: boundary.value,
          overflowPadding: 0,
          placement: 'bottom',
          shift: 0,
          flip: false,
        },
      },
      configs.value,
      tooltipForwarded.value,
    ),
  ),
)

// theme
const theme = useTheme(() => propsTheme)
const tooltipTheme = useTheme(() => ({ ...configs.value?.theme, ...propsTheme }))
const crafts = useCraft(theme, 'tvSlider')
</script>

<template>
  <ThemeProvider :value="theme">
    <TooltipRootProvider :value="tooltip">
      <TooltipTrigger as-child>
        <Slider.Marker
          :value="value"
          :class="crafts.marker(cxc(ui?.root, propsClass))"
        >
          <slot>
            <div
              v-bind="pick(context.getMarkerProps({ value }), ['data-state' as keyof HTMLAttributes])"
              :class="crafts.markerDot(cxc(ui?.dot))"
              data-scope="slider"
              data-part="marker-dot"
            />
          </slot>
        </Slider.Marker>
      </TooltipTrigger>
      <ThemeProvider :value="tooltipTheme">
        <Teleport
          v-if="tooltipForwarded.positioning?.strategy === 'fixed'"
          to="body"
        >
          <TooltipContent v-bind="widget?.tooltipContent">
            <slot name="arrow">
              <TooltipArrow v-bind="widget?.tooltipArrow" />
            </slot>
            <slot name="content">
              <span :class="crafts.markerValue(cxc(ui?.value))">
                {{ value }}
              </span>
            </slot>
          </TooltipContent>
        </Teleport>
        <TooltipContent
          v-else
          v-bind="widget?.tooltipContent"
        >
          <slot name="arrow">
            <TooltipArrow v-bind="widget?.tooltipArrow" />
          </slot>
          <slot name="content">
            <span
              v-bind="pick(context.getMarkerProps({ value }), ['data-state' as keyof HTMLAttributes])"
              :class="crafts.markerValue(cxc(ui?.value))"
            >
              {{ value }}
            </span>
          </slot>
        </TooltipContent>
      </ThemeProvider>
    </TooltipRootProvider>
  </ThemeProvider>
</template>

// packages/react/core/src/components/slider/SliderTooltipMarker.tsx
import type { MouseEvent } from 'react'
import type { SliderTooltipMarkerProps } from './props'
import { Slider as ArkSlider, useSliderContext } from '@ark-ui/react/slider'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { useInheritedTheme } from '@raxium/react/hooks/useInheritedTheme'
import { ProvideStructuralComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { cxc } from '@raxium/themes/utils'
import { merge } from 'es-toolkit/compat'
import { forwardRef, useMemo } from 'react'
import { Tooltip } from '../tooltip'
import { useSliderBoundary } from './slider-boundary-context'
import { SliderTooltipReposition } from './SliderTooltipReposition'

export const SliderTooltipMarker = forwardRef<HTMLSpanElement, SliderTooltipMarkerProps>(
  (
    {
      theme: propsTheme,
      value,
      index = 0,
      open: _open,
      className,
      ui,
      widget,
      interactive,
      content,
      children,
      positioning,
      onTooltipClick,
      ...tooltipProps
    },
    ref,
  ) => {
    const context = useSliderContext()
    const boundary = useSliderBoundary()
    const theme = useInheritedTheme(propsTheme)
    const crafts = useCraft(theme, 'tvSlider')
    const markerState = (context.getMarkerProps({ value }) as { 'data-state'?: string })['data-state']
    const mergedPositioning = useMemo(
      () =>
        merge(
          {
            boundary: () => boundary,
            overflowPadding: 0,
            placement: 'bottom',
            flip: false,
            shift: true,
            slide: true,
            overlap: false,
          },
          positioning,
        ),
      [boundary, positioning],
    )

    function handleTooltipContentClick(event: MouseEvent<HTMLDivElement>) {
      onTooltipClick?.(event)
      if (interactive)
        context.setThumbValue(index, value)
    }

    return (
      <ProvideStructuralComponentTheme theme={theme}>
        <Tooltip
          open
          interactive={interactive}
          positioning={mergedPositioning}
          theme={propsTheme}
          {...tooltipProps}
        >
          <SliderTooltipReposition valueKey={`${value}`} />
          <Tooltip.Trigger asChild>
            <ArkSlider.Marker
              ref={ref}
              value={value}
              className={crafts.marker(cxc(ui?.root, className))}
            >
              {children ?? (
                <div
                  className={crafts.markerDot(cxc(ui?.dot))}
                  data-scope="slider"
                  data-part="marker-dot"
                  data-state={markerState}
                />
              )}
            </ArkSlider.Marker>
          </Tooltip.Trigger>
          <Tooltip.Content {...widget?.tooltipContent} onClick={handleTooltipContentClick}>
            <Tooltip.Arrow {...widget?.tooltipArrow} />
            {content ?? (
              <span
                className={crafts.markerValue(cxc(ui?.value))}
                data-state={markerState}
              >
                {value}
              </span>
            )}
          </Tooltip.Content>
        </Tooltip>
      </ProvideStructuralComponentTheme>
    )
  },
)

SliderTooltipMarker.displayName = 'Slider.TooltipMarker'
