// packages/react/core/src/components/number-input/NumberInput.tsx
import type { NumberInputProps } from './props'
import { NumberInput as ArkNumberInput } from '@ark-ui/react/number-input'
import { useCraft } from '@raxium/react/hooks/useCraft'
import { ProvideComponentTheme } from '@raxium/react/hooks/useProvideComponentTheme'
import { useTheme } from '@raxium/react/hooks/useTheme'
import { useThemeCraft } from '@raxium/react/hooks/useThemeCraft'
import { cxc } from '@raxium/themes/utils'
import { ChevronDown, ChevronUp } from 'lucide-react'
import { forwardRef } from 'react'

export const NumberInput = forwardRef<HTMLInputElement, NumberInputProps>(
  (
    {
      className,
      theme: propsTheme,
      craft,
      ui,
      showTrigger = false,
      prefix,
      suffix,
      onFocus,
      onBlur,
      ...props
    },
    ref,
  ) => {
    const theme = useTheme(propsTheme)
    const themed = useThemeCraft(theme, 'tvNumberInput', craft)
    const crafts = useCraft(themed, 'tvNumberInput')
    const inputCrafts = useCraft(themed, 'tvInput')

    return (
      <ProvideComponentTheme theme={themed} propsTheme={propsTheme}>
        <ArkNumberInput.Root
          className={crafts.root(cxc(ui?.root, className))}
          {...props}
        >
          {prefix}
          <ArkNumberInput.Control className={inputCrafts.root(cxc(crafts.control(), ui?.control))}>
            <ArkNumberInput.Input
              ref={ref}
              className={inputCrafts.input(cxc(crafts.input(), ui?.input))}
              onFocus={onFocus}
              onBlur={onBlur}
            />
            {showTrigger && (
              <div
                className={crafts.triggerGroup(cxc(ui?.triggerGroup))}
                data-scope="number-input"
                data-part="trigger-group"
              >
                <ArkNumberInput.IncrementTrigger className={crafts.trigger(cxc(ui?.trigger))}>
                  <ChevronUp />
                </ArkNumberInput.IncrementTrigger>
                <ArkNumberInput.DecrementTrigger className={crafts.trigger(cxc(ui?.trigger))}>
                  <ChevronDown />
                </ArkNumberInput.DecrementTrigger>
              </div>
            )}
          </ArkNumberInput.Control>
          {suffix}
        </ArkNumberInput.Root>
      </ProvideComponentTheme>
    )
  },
)

NumberInput.displayName = 'NumberInput'

// packages/vue/core/src/components/number-input/NumberInput.vue
<script setup lang="ts">
import type { NumberInputRootEmits } from '@ark-ui/vue/number-input'
import type { NumberInputProps } from '.'
import { useForwardExpose, useForwardProps } from '@ark-ui/vue'
import { NumberInput, useNumberInput } from '@ark-ui/vue/number-input'
import { ChevronDown, ChevronUp } from '@lucide/vue'
import { cxc } from '@raxium/themes/utils'
import { useCraft, useTheme } from '@raxium/vue/composables'

const {
  class: propsClass,
  theme: propsTheme,
  craft,
  ui,
  showTrigger = false,
  ...props
} = defineProps<NumberInputProps>()
const emits = defineEmits<
  NumberInputRootEmits & {
    focus: [event: FocusEvent]
    blur: [event: FocusEvent]
    focusin: [event: FocusEvent]
    focusout: [event: FocusEvent]
  }
>()
const numberInput = useNumberInput(useForwardProps(props), emits)

function onFocusin(event: FocusEvent) {
  emits('focusin', event)
  emits('focus', event)
}
function onFocusout(event: FocusEvent) {
  emits('focusout', event)
  emits('blur', event)
}

// theme
const theme = useTheme(() => propsTheme)
const inputCrafts = useCraft(theme, 'tvInput')
const crafts = useCraft(theme, 'tvNumberInput', undefined, () => craft)

// expose
defineExpose({ $api: numberInput })
useForwardExpose()
</script>

<template>
  <NumberInput.RootProvider
    :value="numberInput"
    :class="crafts.root(cxc(ui?.root, propsClass))"
  >
    <slot name="prefix" />
    <NumberInput.Control :class="inputCrafts.root(cxc(crafts.control(), ui?.control))">
      <NumberInput.Input
        :class="inputCrafts.input(cxc(crafts.input(), ui?.input))"
        @focusin="onFocusin"
        @focusout="onFocusout"
      />
      <div
        v-if="showTrigger"
        :class="crafts.triggerGroup(cxc(ui?.triggerGroup))"
        data-scope="number-input"
        data-part="trigger-group"
      >
        <NumberInput.IncrementTrigger :class="crafts.trigger(cxc(ui?.trigger))">
          <ChevronUp />
        </NumberInput.IncrementTrigger>
        <NumberInput.DecrementTrigger :class="crafts.trigger(cxc(ui?.trigger))">
          <ChevronDown />
        </NumberInput.DecrementTrigger>
      </div>
    </NumberInput.Control>
    <slot name="suffix" />
  </NumberInput.RootProvider>
</template>
