// packages/vue/core/src/components/pin-input/examples/separator.vue
<script setup lang="ts">
import { PinInput } from '../index'
</script>

<template>
  <div class="flex flex-col gap-4">
    <div class="flex flex-col gap-2">
      <span class="text-sm text-gray-cc">With dash separator</span>
      <PinInput :count="4" separator="-" placeholder="○" />
    </div>

    <div class="flex flex-col gap-2">
      <span class="text-sm text-gray-cc">6-digit OTP with separator</span>
      <PinInput :count="6" separator="·" otp placeholder="○" />
    </div>

    <div class="flex flex-col gap-2">
      <span class="text-sm text-gray-cc">6-digit OTP with separator</span>
      <PinInput :count="6" otp>
        <template #separator="{ index }">
          <span v-if="index === 2" class="text-gray-cc">·</span>
        </template>
      </PinInput>
    </div>
  </div>
</template>

// packages/react/core/src/components/pin-input/examples/separator.tsx
import { PinInput } from '../index'

export function PinInputSeparatorExample() {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-2">
        <span className="text-sm text-gray-cc">With dash separator</span>
        <PinInput count={4} separator="-" placeholder="○" />
      </div>

      <div className="flex flex-col gap-2">
        <span className="text-sm text-gray-cc">6-digit OTP with separator</span>
        <PinInput count={6} separator="·" otp placeholder="○" />
      </div>

      <div className="flex flex-col gap-2">
        <span className="text-sm text-gray-cc">6-digit OTP with separator</span>
        <PinInput count={6} otp separator={['', '', '·', '', '']} />
      </div>
    </div>
  )
}
